### ISSUE TITLE
跨系统选择操作编辑实例时优化

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#1010]
1. 各系统可以通过区域区分，加强视角交互
2. “无需关联资源实例”的操作可以减弱展示效果
3. 「复制粘贴」交互效果要加强，用户目前很少能感知到

**Comment by zhu327** [comment]
前端处理

**Comment by Xmandon** [comment]
1. “无需关联资源实例”的操作可以减弱展示效果
2. 「复制粘贴」交互效果要加强，用户目前很少能感知到
------
1. 解决方案是：把相同系统的，无需关联资源类型的操作合并在一个表格里
2. 解决方案是：把单个的粘贴按钮也放出来，另外增加“格式刷”的icon
<img width="178" alt="image" src="https://user-images.githubusercontent.com/19284021/170450424-33ae9d16-7655-4a1d-a526-5bde137906be.png">
