### ISSUE TITLE
分级管理员模板

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#1017]
分级管理员模板 -》 权限模板 -〉 用户组模板

**Comment by Xmandon** [comment]
https://s5lbt3.axshare.com/#id=2ig68c&p=index&g=1

**Comment by zhu327** [comment]
大需求, 初步评估工作量比较大

15人天, 不包括前端

**Comment by zhu327** [comment]
协作开发可能不行

**Comment by Xmandon** [comment]
评审，需求不够明确，找准需求点再重新理方案
