### ISSUE TITLE
导航调整

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#1031]
原型稿：https://s5lbt3.axshare.com/#id=2ig68c&p=index&g=1

**Comment by zhu327** [comment]
前端处理

**Comment by Xmandon** [comment]
设计稿已交付实现

**Comment by Xmandon** [comment]
<img width="698" alt="image" src="https://user-images.githubusercontent.com/19284021/174210706-a4602f91-5c5a-4f54-a2c3-30ac42aef2fc.png">

**Comment by Xmandon** [comment]
<img width="749" alt="image" src="https://user-images.githubusercontent.com/19284021/174211041-cfff5351-4f87-4991-b0d0-feae831eff3f.png">

**Comment by Xmandon** [comment]
<img width="1048" alt="image" src="https://user-images.githubusercontent.com/19284021/174211995-d3bdb90a-2cd8-423e-9914-b846f05b151e.png">

**Comment by Xmandon** [comment]
<img width="1048" alt="image" src="https://user-images.githubusercontent.com/19284021/174212121-e534b911-5713-4543-8108-0c266772923a.png">

**Comment by Xmandon** [comment]
<img width="726" alt="image" src="https://user-images.githubusercontent.com/19284021/174212327-56f08d14-54cc-4f98-97d0-6594d88bbc88.png">
