### ISSUE TITLE
推荐权限里包含已有权限时样式优化

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#1033]
## 问题背景：
当用户点击「推荐权限」时，如果对应的操作已经包含用户已有权限时，用户不清楚推荐权限到底包含了哪些操作。

## 解决方案：
增加样式优化
<img width="2210" alt="image" src="https://user-images.githubusercontent.com/19284021/167052453-7620221a-ef05-4a95-b17b-b75b2fd6c925.png">

**Comment by lhzzforever** [comment]
done
