### ISSUE TITLE
实例有效期方案

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#106]
关联issue https://github.com/TencentBlueKing/bk-iam-saas/issues/15

**Comment by Xmandon** [comment]
## 方案一：
一个操作 + 多组实例 + 多组有效期，存在问题：实例组数存在限制，比如10条，有效期过期时处理问题，包括 无权限跳转，用户的理解问题

## 方案二：
一个操作 + 1组实例 + 实例有效期

**Comment by wklken** [comment]
# 实例有效期

权限中心v3的目标是实现范围授权及支持实例授权. 主推范围授权(属性/拓扑).

## 现状

有效期是操作维度的, 即策略中同一个操作下的所有实例有效期一致

```
用户 - 操作 - 资源表达式 - 有效期
```

这样做的问题, 无法进一步精细化控制`实例-有效期`的权限, 例如, 用户申请查看主机权限, 其所有主机列表的策略过期时间是一致的, 无法单独申请某台主机更长的有效期.

## 需求

最早来自蓝盾, 需求: `用户-流水线` 每条流水线有效期成不一样; 最近bf接入, 也有一样的需求, `用户-主机` 用户登录主机, 每一台有效期不一样.

权限中心目前无法支持

## 需求分析

原先: `resource.id in [1, 2, 3]`
现在: 
- 变成多条 `policy1 - expire1; policy2 - expire2`
- 还是一条, 表达式层面处理 `resource.id in [1, 2, 3] AND _bk_iam_expire_ lte 12345678`

### 方案 1: 多条策略

> 变成多条, 每一条独立有效期

每多一条`实例-有效期`, 独立存储为一条策略

优点:
- 简单
- 过期/续期方便
- 授权/回收相对简单, 都是独立的

缺点:
- 性能差, 1000 个实例可能有 1000 条, 整体加载/反序列化/计算都会慢, 且无法优化; 
- 查询: 得全部查回来
- 加载: 得全部加载, 因为无法知道表达式中的内容
- 计算: 得全部计算

方案 1 改进:

> 独立一个表, 保存多条, 每条独立有效期; 原先主表不变

保留了方案 1 的优点; 
- 避免给现有代码带来复杂度;
- 也隔离了没有用到实例有效期的系统鉴权不受影响)
但是, 两个缺点没有得到改进

### 方案 2: 一条策略表达式支持过期时间

> 还是一条, 表达式层面处理

表达式

```
resource.id in [1, 2, 3]
AND
_bk_iam_expire_ lte 1632886268

host.id in [1, 2, 3]
AND
job.path = '/biz,1/'
AND
_bk_iam_expire_ lte 1632896408
```

配置时, 将过期时间存入; 计算时, 会走两阶段计算, 先将过期时间执行完, 再返回给应用;

优点:
- 对于接入系统透明无感知

缺点:
- 后台复杂, 表达式必须内置`_bk_iam_expire_`
- SaaS 实现成本高: SaaS 表达式的存储/展示复杂度提升
- 加载: 表达式变大, 过期势必不会立即清理
- 计算: 即使过期, 也会参与计算, 影响整体性能; 
- 过期: 无法在外部感知到, 需要遍历分析每条确定过期;
- 续期: 怎么进行续期? 
- 授权及回收:
    - 再次授权, 时间不一样, 怎么处理?
    - 如何进行回收?
- 对外: 
    - 接入系统查询回去的表达式里面的实例可能随时过期; 得理解`_bk_iam_expire_`
    - 对engine不友好, 需要考虑如何筛选掉已过期的

- 授权回收: 如何操作?

### 方案 3: 折中-两条策略

> 方案 1+方案 2 的折中, 存两条; 复杂度和实现成本最低的方案
> 相当于实现一套完备的表达式配置逻辑, 未来可扩展, 收益最大

存两条策略:(一个人的自定义权限, 最多两条)
1. `type=default` 原先的默认策略, 操作维度的有效期
2. `type=instance_expire` 新增表达式有效期策略, 操作维度有效期是`永久`或`所有有效期里面最大的一个值`, 表达式层面`存储实例+有效期`; 并且, 需要实现完备的表达式, 即, 支持`去除笛卡尔积`的权限配置. (带过期时间/要求非笛卡尔积方式)

**注意**: 实现了完备的表达式, 一并解决了笛卡尔积的问题

```
resource.id in [1, 2, 3]
AND
_bk_iam_expire_ lte 1632886268

(
host.id in [1, 2, 3]
AND
job.path = '/biz,1/'
AND
_bk_iam_expire_ lte 1632896408
) OR (
host.id in [4, 5, 6]
AND
job.path = '/biz,2/'
AND
_bk_iam_expire_ lte 1632896408
) 
AND _bk_iam_expire_ lte 1632896408  [有效期也可以放在外头]
```

逻辑:
- 配置, 保留原先的策略配置逻辑, 产品上支持新的配置交互, 支持非笛卡尔积+过期时间+其他更多功能的处理逻辑.
- 鉴权, 捞取出来全部算, 对于`type=instance_expire`策略, 需要提前算过期时间
- 过期通知: 只遍历`type=instance_expire`策略
- `type=instance_expire`的策略, 需要感知到, 及时回收

优点:
- 加载: 策略数量没有增加, 只多了一条
- 可控: 可以限制另外这条中的实例配额
- SaaS 及后台: 对现有影响最小, 相当于分两类, 原先的逻辑不动, 新增一种类型支持; 每一种类型对应一条策略; 

缺点:
- 后台复杂, 表达式必须内置`_bk_iam_expire_`
- 计算: 多一条策略参与计算, 过期的也会参与, 可能影响性能;(但是已经最小化影响了, 因为可以根据操作的过期时间筛掉一部分)
- SaaS的实现成本: SaaS 和产品需要针对这种更通用灵活的场景处理, 实现成本比较高; 

#### 方案 3 实现分析

##### SaaS 数据

```
用户 - 操作 - 策略+基本信息 - 最小过期时间 - 最大过期时间
```

(需要考虑最大过期时间是否支持永久? 理论上应该不支持?)

##### 产品上配置策略

> 如果实现, 就是一个完备的表达式配置, 产品具象化, 可能需要抛弃原先基于固定结构化的存储和展示, 需要考虑下未来的扩展;

复杂度在于, `策略+基本信息` 的保存/操作/展示等

##### 过期及回收

每天扫描 `最小过期时间`已经小于当前时间的策略, 解析, 发送通知; 

并且对超过 1 个月没有续期的, 直接回收? (需要确认回收的策略)

必须要有回收, 如果不回收, 会给计算带来很大压力, 配额也会无法释放

##### 授权/续期

需要合并过期时间相同的; 续期需要精准变更; 同时修改`最小过期时间 - 最大过期时间`

如果授权同一个实例的不同过期时间, 需要使用最大的那个? 并且最终根据过期时间合并`可以合并的策略`

问题: 同一个`resource.id`理论上只能有一个?

##### 主动回收

怎么处理? 遍历实例 ID, 命中即回收?

##### 往后台同步数据

同步一条策略 + `最大过期时间`; 

##### 后台计算逻辑

查询`最大过期时间`没有过期的策略 + 原先的策略; 一共两条; 

如果只有原先的策略, 走原先计算逻辑; 如果策略是带过期时间的, 将当前时间带进去计算;

表达式中过期时间`_bk_iam_expire_ lte 1632904741`

##### 后台策略查询接口及发布订阅

计算, 丢弃`_bk_iam_expire_`已经过期的, 返回未过期的(需要带`_bk_iam_expire_`;

或者前期粗暴一点直接返回; 接入系统/sdk需要理解这个字段的计算逻辑;

##### 后台policy接口

auth接口无需处理, 直接计算结束

query接口需要考虑, 是否返回`_bk_iam_expire_`? 如果认为是实时的, 不需要, 只返回当前时刻有效的; 如果不是, 那么应该返回, 由接入系统/SDK进行二次计算;(后者主要担心策略被cache后导致计算不准)

##### 发布订阅

返回完整的表达式; 有 iam 自己发现过期, 变更表达式, 触发表达式更新事件; 

接入系统及sdk需要理解`_bk_iam_expire_`

##### Engine

理论上带过期时间的策略都是`复杂表达式`, 无法入es; 这也会给engine的查询带来负担

**Comment by wklken** [comment]
## 方案 3

#230   实例有效期作为独立的资源类型, 关联特殊的实例视图

**Comment by wklken** [comment]
#350 

最新方案(方案 5)

**Comment by wklken** [comment]
最后结论: 环境属性 + 临时权限;

这个issue 可以关闭了
