### ISSUE TITLE
蓝鲸权限中心--用户组--用户组成员莫名其妙丢失

### ISSUE THREAD

**Issue by leezer3379** [TencentBlueKing/bk-iam-saas#1061]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):

**bk-iam-saas SaaS版本/bk-iam后台版本(The versions used): 1.4.24

**发生了什么(What happened):**
蓝鲸权限中心--用户组--用户组成员莫名其妙丢失

**期望是什么(What you expected to happen):**
1. 蓝鲸权限中心--用户组--用户组成员不丢失
2. 希望能在数据库中找到对应的关联关系

**如何复现(How to reproduce it):**
目前不知道

图片展示
![image](https://user-images.githubusercontent.com/37136385/167766014-47dca44f-d909-4e10-a4c3-383919938b53.png)
点分组后并不能发现里面的用户
![image](https://user-images.githubusercontent.com/37136385/167766101-634279fb-fe75-46ed-a694-f6ab3c161897.png)
且新增用户不受影响，可以正常增加用户
![image](https://user-images.githubusercontent.com/37136385/167766144-7219e526-53b3-4582-8d1e-d2bd73ce10bb.png)

**Comment by zhu327** [comment]
看一下审计信息是否有删除成员的操作

**Comment by leezer3379** [comment]
没有删除操作，现在ad同步莫名其奥妙的还失败了
![image](https://user-images.githubusercontent.com/37136385/168600988-e2f91793-0329-4076-9740-8fc9f932e0af.png)
![image](https://user-images.githubusercontent.com/37136385/168601064-a75634e3-fd5a-4728-8f10-0ecbe7cedee2.png)
![image](https://user-images.githubusercontent.com/37136385/168601138-41b19038-e118-4372-b8ff-b949fde96870.png)

**Comment by leezer3379** [comment]
我有一个复现的方法，在用户管理应用中，配置好AD删除bk_user数据库，没错就是整个数据库，我认为这个系统中我没有使用本地用户，只有一个AD的配置用户，因为信息无法同步，整个系统陷入瘫痪，所以想到django删除数据库后可以重建各种表，于是删除了bk_user数据库，重装了一下usermgr应用，重新配置AD，用户系统恢复，用户可以正常登录。但是权限中心同步组织架构失败
![image](https://user-images.githubusercontent.com/37136385/168715623-2fd3020e-963d-44b3-bda4-a2c33b397b87.png)
然而让我疑惑的是用户管理系统中是有组织架构的
![image](https://user-images.githubusercontent.com/37136385/168715744-50be1dc8-d0dd-47a2-8ea6-eeec4b7426de.png)

**Comment by wklken** [comment]
权限中心同步了用户管理的组织架构, 并且是根据用户管理提供的唯一id确定的用户状态;
如果用户管理删除重建, 即使相同的 AD 用户/部门, 其在用户管理中的唯一 ID 也是不一样的, 此时, 权限中心无法正确识别用户及部门的变化; 

-------
如果重建了用户管理的组织架构, 那么权限中心的也许要删除重建;
