### ISSUE TITLE
[SaaS] RBAC方案下OpenAPI设计

### ISSUE THREAD

**Issue by nannan00** [TencentBlueKing/bk-iam-saas#1070]
1. url 需要带system_id
2. v2 API
------
OpenAPI尽可能分布到后台，除非涉及数据只有SaaS有才放到SaaS 

管理类 API, 考虑是否满足 OpenAPI 3.x ? 是的话, 可以考虑生成管理类API 的多语言 SDK

**Comment by wklken** [comment]
协议先行
