### ISSUE TITLE
[RBAC] issues汇总

### ISSUE THREAD

**Issue by zhu327** [TencentBlueKing/bk-iam-saas#1073]
RBAC 相关需求分为3块

## 1. 用户组授权

- [ ] [2022-05-31] #1083
- [ ] [2022-06-02] #1087
- [ ] [2022-06-07] #1072 
- [ ] [2022-06-10] #1082
- [ ] [0222-06-15] #1084
- [ ] [2022-06-20] #1085
- [ ] [2022-06-23] #1086

## 2. 鉴权支持RBAC

- [ ] [2022-06-15] #1080
- [ ] [2022-06-23] #1077

## 3. 用户组管理

- [ ] [2022-06-01] #1113 -- 出beta测试
- [ ] [2022-06-02] #1075 
- [ ] [2022-06-08] #1076 

## 4. 收尾

- [ ] [2022-06-28] #1212 
- [ ] [2022-06-29] #1214 
- [ ] [2022-07-01] #1213 

## 4. 其他
- [ ] #1116 
- [ ] #1108 
- [ ] #1148

**Comment by wklken** [comment]
事项:
1. 梳理并给到蓝盾相关 API 协议(delay 了)
2. 离线计算 RBAC 的表达式(目前高风险, 需尽快开始)
3. 重点模块单元测试补齐
4. rbac 权限配置功能测试
5. rbac 各种场景鉴权功能测试
6. 压测, 确认热点, 可能需要做优化
7. 重点模块代码线下review, 可能需要做调整
8. 提测(需要尽早测试接入, 给到足够多信息, 测试理论上能协助构造 rbac 相关的用例, 完成接口测试)
9. 开发联调环境更新(支持蓝盾联调)

**Comment by nannan00** [comment]
1.  梳理并给到蓝盾相关 API 协议(delay 了)  => `2天`

2. 离线计算 RBAC 的表达式(目前高风险, 需尽快开始)
- GroupSystemActionResource缓存模块  => `1天`
- SubjectActionGroupResource 同步到SubjectActionExpression => `2天`
- 查询SubjectActionExpression => `1天`
- 消费者事件处理模块 - 查询缓存GroupSystemActionResource、变更SubjectActionGroupResource表数据  =>  `3天`
- 生产者事件处理模块 - 多种事件产生逻辑(包括触发事件、删除缓存) => `2天`
- 异步机制、补偿机制 => `？天、待定？`

**Comment by nannan00** [comment]
3. SaaS 代码重点模块单元测试补齐 => 2天

**Comment by zhu327** [comment]
6.28 合第一个版本 后台/saas
