### ISSUE TITLE
[RBAC] 蓝盾以RBAC方式接入

### ISSUE THREAD

**Issue by nannan00** [TencentBlueKing/bk-iam-saas#1105]
### 后台

1. [api v1] 注册Action / 更新Action
    - 支持声明是否支持RBAC  #1106 

2. [api v1] 注册屏蔽功能的json配置  #1107

3. [api v2] auth 接口
    - 与api v1 Auth不同，该接口同时考虑RBAC和ABAC，主要是resources字段的不一样，且对于RBAC是必填

4. [api v2] 查询有权限的资源列表    #1108
    - Action必须是仅仅配置RBAC
    - 该接口由IAM Search Engine提供

5. [api v2] [非鉴权接口] 校验用户是否某个用户组的成员(支持批量用户组，批量数有限制)  #1109

6. 对于api v1接口需要根据system.action是否支持rbac，提示不可调用，比如支持rbac的系统不可调用api v1 policy list等等   #1110

### SaaS

> 管理类API后台由于无法感知到系统管理员与用户组关系，所以管理类API必须在SaaS该类RBAC API 必须在系统管理员下，即路径里包含system_id

1. [api v2] 创建用户组

2. [api v2] 用户组更新基本信息

3. [api v2] 删除用户组

4. [api v2] 用户组授权

5. [api v2] 用户组删除权限

7. [api v2] 查询用户组已配置的操作列表

8. [api v2] 用户组移出成员[批量]

9. [api v2] 主动给用户组成员续期[批量]

10. [api v2] 分页查询用户组成员列表

11. [api v2] 创建加入用户组的申请单据

**Comment by wklken** [comment]
@nannan00 梳理, 列出需要给到蓝盾的 API 文档
