### ISSUE TITLE
[RBAC] iam-search-engine支持新表数据同步

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-iam-saas#1108]
- [ ] 新表数据同步, 刷到当前engine (需要考虑如何同现有的数据兼容, 理论上, 不影响老的接口)
- [ ] 支持查询有权限的资源列表
    - 仅RBAC支持? 
    - 此时只能查groups
    - 用户的继承关系怎么办? 是否需要支持? 
- [ ] 原先的逻辑怎么处理? 推荐有资源权限的用户组逻辑

**Comment by wklken** [comment]
> 直接把生成的策略, 刷过去就行, 无需做额外的操作

行为是一致的, 只是需要看一下, policy是否是单独存的, 是的话, 需要拆开

**Comment by wklken** [comment]
- 需要做相关的同步
- 需要变成核心服务(稳定性,监控,图表,高可用)
- 需要提供相关的 API 给到外部


目前search-engine只支持查询有权限的subject列表，对于RBAC相关的策略，需支持查询某个subject有权限的资源实例列表？

-------
问题: 支持查询某个有权限的资源列表, 开放 API, 并声明(同步时间差/数据一致性保证)等等逻辑

**Comment by wklken** [comment]
旧有提供的API

```go
func Register(r *gin.RouterGroup) {
	// GET /api/v1/engine/policies 拉取指定条件的策略列表
	r.GET("/policies", handler.ListPolicy)

	// GET /api/v1/engine/policies/ids 查询指定条件的策略ID List
	r.GET("/policies/ids", handler.ListPolicyPKs)

	// GET /api/v1/engine/policies/ids/max 查询指定条件的策略最大ID
	r.GET("/policies/ids/max", handler.GetMaxPolicyPK)

	// GET /api/v1/engine/systems/:system_id 查询系统信息
	r.GET("/systems/:system_id", handler.GetSystem)

	// POST /api/v1/engine/credentials/verify 认证信息验证
	r.POST("/credentials/verify", handler.CredentialsVerify)
}
```

旧有的 policy结构

```go
policy = enginePolicyResponse{
		Version: service.PolicyVersion,
		ID:      p.PK,
		System:  action.System,
		Action: policyResponseAction{
			ID: action.ID,
		},
		Subject: policyResponseSubject{
			Type: subj.Type,
			ID:   subj.ID,
			Name: subj.Name,
		},
		Expression: translatedExpr,
		TemplateID: p.TemplateID,
		ExpiredAt:  p.ExpiredAt,
		UpdatedAt:  p.UpdatedAt,
	}
```

所以, 处理方式上

1. 保持策略结构一致, 即, 对于engine拿到的数据是一致的, 需要有相应的字段, 例如`ExpiredAt`
2. 接口, 新增一批接口, 或现有接口支持`不同类型`(调用不同的service)
3. 同步, 还是一个? 或者变成两套?  (最好一套)


所以, 有没有可能, 虽然后台是两个表, 但是对外提供服务的时候, 像是一个表?

**Comment by wklken** [comment]
决策: 使用一套syncer, 还是两套? 

如果使用一套, 那么, 要么下层接口封装了abac/rbac两次调用, 要么上层明确调用abac/rbac; => 在IAMBackendClient 这里消化掉?

**Comment by wklken** [comment]
会有: _bk_iam_path_ string_contains 操作符
此时, 
- 分解入库的逻辑, 应该拆成nodes
- 查询的逻辑, 应该使用`in`

**Comment by zhu327** [comment]
subject_action_expression 表中的subject为 user/department 检索相关权限时，检索出来的subject没有group信息

group action 的 rbac 权限查询方法

```sql
SELECT action_pks, resource_type_pk, resource_id FROM group_resource_policy WHERE group_pk=? AND system_id=? AND action_related_resource_type_pk=?
```

在iam后台有 group_action_resource 的缓存

**Comment by wklken** [comment]
两种处理方案:
1. 落地 rbac_group_expression 表, 使用issue中同一套api, 拉取后建索引
2. 不落地, 直接查 `group_resource_policy` 表, 此时需要增加一批 API -> sync层(可能需要重构)
    - 问题: 流水线查看, 配置了项目, 此时怎么确保传流水线能够推荐到这个组? 翻译成 string_contains?
    - 如果是, 问题: 查询需要支持string_contains这种表达式?

**Comment by wklken** [comment]
有没有版本合二为一? group_resource_policy mock 原先的接口, 保持一致

**Comment by nannan00** [comment]
ID如何处理? => 区间分段后，选择方案1，在input/output处理方便后续扩展，比如rbac 5亿(500,000,000 - 1,000,000,000) 不够的情况下，可以再取后续预留的30亿进行扩展

**Comment by wklken** [comment]
新的问题:
1. 删除事件没有触发点(即, 这条记录在什么时候被删除, 没有触发delete事件)
2. 原先建es索引, `action: {id: abc}`, 并不能同时再保存 `action_ids`
