### ISSUE TITLE
[RBAC] 接口列表review

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-iam-saas#1128]
当前是: [用户 - 组(角色) - 操作 - 资源]

要求:
1. 接口url一致性
2. 接口协议一致性
3. 易用性, 是否对普通系统足够友好
4. 系统管理员/分级管理员概念
5. 是否定义模型后, 可以非常便捷接入? 

## 基础:

- 新建组(角色) / 删除组/ 更新组
- 组加人/ 减人 / 续期
- 组 授权 / 回收权限 (增删操作/ 增删操作+资源)

## 组列表:

- 查询一个用户的组(角色)列表
    - 查询一个用户的全局组(角色)列表
    - 查询一个用户 项目级/流水线级 的组(角色)列表 (用户的角色列表)
    - 查询一个用户 某个项目/某个流水线 的组(角色)列表 (用户对某个具体资源的角色列表)
    - 查询一个用户是否属于某一批组(数量限制)

- 查询一个资源的组(角色)列表
    - 查询一个项目的组(角色)列表
    - 查询一个流水线的组(角色)列表
    - 查询一个资源一个操作的组(角色)列表(审计? 重中之重，控制一个资源的角色数量关系)

## 资源列表:

- 查询一个组一个操作的资源列表
    - 查询一个用户一个操作的资源列表? (继承, 是否支持?)

## 操作列表:

- 查询一个组(角色)的操作列表? (怎么实现)
    - 查询一个用户的操作列表(继承, 是否支持?)

**Comment by zhu327** [comment]
iwiki文档中缺少api v2_management_groups_policies_revoke 的说明

**Comment by zhu327** [comment]
授权api system填与不填, 如何界定

**Comment by zhu327** [comment]
bugfix, 测试完成

---

剩下:

1. 到处yml
2. 补全文档
