### ISSUE TITLE
[RBAC] 离线计算rbac的expression

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-iam-saas#1148]
- [ ] 计算机制
- [ ] 同步机制(数据一致性/延时)

相关issue
- #1108  需要考虑这个issue中提到的字段一致

**Comment by wklken** [comment]
并在policy query接口中返回;

**Comment by wklken** [comment]
优先级提升

**Comment by zhu327** [comment]
RBAC的前缀处理方式特殊性, 导致转换成ABAC的expression是需要有特殊的处理方式, 比如:

用户在配置权限时的路径时: /a/b/*/ 

RBAC的处理会丢失a, 只保留b, 在rbac的计算中会处理成b的equel

在RBAC转换成ABAC的过程中, 需要有完整的 /a/b 路径信息才能正常转为 startwiths 操作符

这里不能再用startwiths, 有2中解:

1. 新增操作符判断只要 iam path 中包含 b就算通过
2. 用equel rt.id, 在query时把iam path解开生成对应的rt.id的属性, 通过equel计算通过

**Comment by wklken** [comment]
contains操作符在所有sdk及服务端都有实现, 但是有差异
- https://github.com/TencentBlueKing/iam-php-sdk/blob/master/src/Evaluation/Eval.php#L69 php sdk 要求 object.attribute必须是个 `[]` 才能调用 contains
- https://github.com/TencentBlueKing/iam-go-sdk/blob/master/expression/eval/contain.go#L87 go sdk没有限制,  如果 object.attribute是个string, 会使用`strings.Contains`; 是个list, 使用`list has that element`
- https://github.com/TencentBlueKing/iam-python-sdk/blob/965f436733e2dfd655d465a0552ccedc03e48aab/iam/eval/operators.py#L143 python sdk, 单个, 直接 `exprvalue in object.attribute`; 多个, for判断 `exprvalue in object.attribute`

**Comment by zhu327** [comment]
其余问题:

1. 消息队列拿数据去重
2. 消息队列拿消息限流, 考虑通过令牌桶
3. 数据校验, 需要有定时任务校验相关数据是否一致, 如果不一致则重新发送消息

**Comment by wklken** [comment]
https://github.com/adjust/rmq

1. 消息体结构
2. 如何去重
3. 如何避免无限重试
4. 是否区分更多队列? 隔离/可扩展
5. 可观测性: 日志/metrics等暴露

**Comment by zhu327** [comment]
拆分issue

1. 用户组RBAC策略变革/成员变更, 发送变更消息
2. 事件消息处理
3. 事件回溯检查机制

**Comment by zhu327** [comment]
消息去重, 通过查询 group_alter_event, group_pk=? status=0 的数据, 如果有数据还没有处理, 直接去重, 最终一致由检查逻辑保证
