### ISSUE TITLE
持续集成平台鉴权缓存问题

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#1170]
持续集成平台目前鉴权做了缓存（处于性能的考虑），5分钟，导致iam的权限更新在该平台是不及时的，iam需要做个机制，比如hook来解决这个问题。缓存不可避免（需要让接入系统感知到变化实时刷新）。

**Comment by wklken** [comment]
> 权限变更很复杂, 并不是这个人的权限变更才会触发, 这个人继承的权限变更/过期, 自己权限变更/过期等等, 都会引起其权限变更; 并且, 环境属性是实时变化的, 例如时间段因素/来源系统/来源 IP

- 目前的策略: 非敏感权限, 可以缓存, 敏感权限, 不建议缓存

--------

如果搞`变更-通知`机制, 整体非常复杂
1. 需要感知继承的变更`组-人`/`组-部门-人`
2. 需要感知过期
3. 无法感知环境变更
4. 放大, 即一个权限变更, 可能触发整个部门/整个公司人缓存失效, 系统抖动

--------

所以, 还是建议: 非敏感权限缓存, 敏感权限不缓存

**Comment by Xmandon** [comment]
嗯嗯，先记录下问题，后面再看具体方案。

**Comment by zhu327** [comment]
不考虑
