### ISSUE TITLE
下半年产品功能梳理

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#1192]
- [x] 初始化权限数据	
- [ ] 通知设置
- [ ]  页面开发接入（实现页面化注册、内置系统权限模型展示）
- [x]  对接审计中心
- [ ]  申请加入分级管理员 
- [ ]  申请有效期和审批决策（是否统一又管理员负责，用户申请不再关注有效期）
- [ ] 	生效条件二期
- [ ]  整体交互优化 （主要选择操作实例页面）
- [ ]  分级管理员模板（再审）
- [ ] 	实例权限支持分级管理员审批 
- [ ] 	批量移除权限/一键清理个人权限
- [ ] 	冻结权限/删除某人权限
- [ ]  离职转岗权限交接二期：通知、审批、删除权限缓冲区		
- [ ] 	申请权限支持“权限获得者”为其他人	  	
- [ ]  用户权限策略接近限制值告警  	
- [ ]  策略扫描和数据清理机制  	
- [ ]  首页dashboard  
- [ ]  运营分析（考虑接入bkbase）	
- [ ] 	分级管理员支持人员权限管理

**Comment by zhu327** [comment]
1. 初始化权限数据
    - 用户组/成员
    - 分级管理员/成员
    - 模板
2. 页面接入
    - 接入如何注册
    - 接入如何调试
    - 接入如何模拟
    - 接入如何删除
3. 审计中心对接
    - 对接方式
    - 开发量
4. 分级管理员模板
    - 怎么控制数据量
5. 实例权限支持分级管理员审批
    - 通过分级管理员的权限范围回溯
    - 可能会命中很多个分级管理员 * 分级管理员的成员很多, 导致审批的人很多
6. 通知设置
    - 通知框架
7. 离职转岗权限交接
    - 数据量很大的情况下怎么创建审批单
    - 缓冲区如何的概念
8. 生效条件
    - 来源ip怎么传
9. 用户申请权限“有效期” 逻辑优化
    - 有效期绑定在操作上, 需要针对不同的操作做定制?
10. 推荐用户组策略优化
    - 排序策略?
11. 个人权限一键冻结、一键回收
    - 长时任务处理, 或者定时处理
    - 是否需要反悔
12. 支持“隐藏”功能配置
    - 系统
    - 操作
13. 分级管理员支持「用户&组织架构」权限管理
    - 怎么区分分级管理员授权的用户与组织
    - 分级管理员授权的范围只能是模板, 只能管理员已授权的数据? 需要回溯授权的来源?
14. 接口类需求: 支持实例维度的授权策略查询
    - 只有RBAC能支持?
