### ISSUE TITLE
【问题反馈】单个权限添加操作提示错误，批量添加才能成功

### ISSUE THREAD

**Issue by atmaybe** [TencentBlueKing/bk-iam-saas#1208]
社区版本：6.0.5
bk_iam：1.4.24

  在进行用户组权限添加时，单个添加操作后提交会显示“系统: bk_log_search 模板: 3 校验错误: 接入系统资源接口请求失败: unreachable interface call”，无法提交保存配置。
  点击开启“批量编辑”后再提交，即可成功。

**Comment by zhu327** [comment]
https://bk.tencent.com/docs/document/6.0/160/8403

**Comment by zhu327** [comment]
请参考以上文档
