### ISSUE TITLE
[RBAC] RBAC下各种维度对象数量的限制调整

### ISSUE THREAD

**Issue by nannan00** [TencentBlueKing/bk-iam-saas#1227]
1.  一个用户可加入的用户组，按系统区分？
2. 一个资源实例可被授予的用户组数量
...

需要重新review之前的限制 https://bk.tencent.com/docs/document/6.0/160/10834

**Comment by zhu327** [comment]
1个用户组能够授权的实例数量限制

**Comment by zhu327** [comment]
按系统放开用户组的数量

**Comment by zhu327** [comment]
一个group能加入多少个成员，直接影响rbac_subject_group表的大小

一个subject能被多少个group关联

一个资源实例能绑定多少个group

一个group能关联多少个不关联资源实例的操作/任意资源实例的操作

group递归继承有几级

**Comment by zhu327** [comment]
1. 以系统为维度，一个系统内最多一个用户组最多能加入多少用户组

- 查询subject已加入的所有用户组
- 查询这些用户组的system_id
- 得到 subject 的 system_id -> 用户组数量 map
- 新加的用户组，查询system_id

---

往已有的系统的用户组map上+新增的用户组system_id +1, 并判断是否操过system_id配置数量的限制，如果操过则报错


---

另外一种方式

saas上通过api创建的用户组是绑定了创建的系统的，那么只对这些用户组做数量限制，配置在saas上

**Comment by zhu327** [comment]
- 先从 subject_system_group 考虑计算数量限制, 不需要绝对的精确
- 再考虑下是否在用户组成员续期的时候, 判断已有的数量, 如果超限, 不能续期

**Comment by zhu327** [comment]
用户组一个操作的能授权的实例数量, 会影响到用户组权限变更时的同步任务的速率:

1. 1000个时没有影响
2. 10000个时会有影响

**Comment by zhu327** [comment]
1. 后台 group 新增成员 api 增加 系统 数量限制
2. saas去除已有的1个用户只能加入100个用户组的限制

---

后台需要返回详细的错误信息, 并且saas能在这个错误信息的基础上能展示明确的信息, 提示用户删除已有的用户组
