### ISSUE TITLE
分级管理员优化

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#1280]
<img width="1420" alt="image" src="https://user-images.githubusercontent.com/19284021/179198660-90695287-0511-4280-ada8-f898ae99b7de.png">

**Comment by Xmandon** [comment]
补充：
1. 分级管理员里，新建模板的系统下拉列表需要增加授权范围的跳转（新窗口打开）。
<img width="1505" alt="image" src="https://user-images.githubusercontent.com/19284021/180400544-4e00c4ce-0e58-4273-8da1-60583dc82bfd.png">

2. 分级管理员里，新建用户组，添加自定义权限时，也需要增加指引。
<img width="1414" alt="image" src="https://user-images.githubusercontent.com/19284021/180400690-46a83a9a-2f3a-41e6-88d0-cdd646a3304d.png">

**Comment by leafage-collb** [comment]
> 1. 分级管理员里，新建模板的系统下拉列表需要增加授权范围的跳转（新窗口打开）。

新建分级管理员，怎么跳转至对应的分级管理员编辑页？
