### ISSUE TITLE
[FAQ] 补充: 分级管理员/用户组等关系及说明

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-iam-saas#1294]
大体的权限关系: 

系统 -> 分级管理员 -> 用户组

每个系统只能操作 自己创建的分级管理员下的用户组

-----

权限中心对用户组的管理逻辑是:

1. 先有分级管理员
2. 在分级管理员下创建用户组, 在该分级管理员下创建的用户组只能由该分级管理员管理

open api对用户组的创建和管理做了进一步的限制:

1. 先通过api创建分级管理员, 这个分级管理员绑定了调用系统的信息
2. 通过api创建用户组, 这个时候需要在url中传入上一步创建的分级管理员id, 这个用户组能正常通过api做管理, 只能由这个系统来调用

-----

调用报错:

> role[1] can not be operated by app_code[bk_sops], since role source not exists

这里可能需要更清晰一些

**Comment by zhu327** [comment]
已补充
