### ISSUE TITLE
[可观测性] checker/iam-search-engine等

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-iam-saas#1345]
- 新增的进程的port暴露
- 配置采集/metrics

**Comment by zhu327** [comment]
同时暴露profile

**Comment by wklken** [comment]
https://github.com/adjust/rmq/blob/master/stats.go

iam /metrics中加入响应的 rmq数据, 用于监控告警

**Comment by zhu327** [comment]
https://github.com/pffreitas/rmqprom

**Comment by zhu327** [comment]
- 存活
- 队列长度
- 消费数量/速率之类的
