### ISSUE TITLE
[Backend] 优化event创建去重, 避免group频繁变更权限，产生事件风暴，重复执行

### ISSUE THREAD

**Issue by zhu327** [TencentBlueKing/bk-iam-saas#1349]
1. 在event表中新增 signature， status字段

- signatrue字段包含group_pk, action_pks, subject_pks 的特征值
- status 0 表示还未开始计算，1 running
- 增加signature status唯一索引

2. 在group授权的场景下，创建event的逻辑

- 每个action一个event，对subject_pks做拆分后计算signature，如果插入唯一冲突，直接忽略

3. 在group成员变更的场景下

- 逻辑不变

**Comment by wklken** [comment]
> group - action_pks - group_members - status

- group和action_pks不可控, 取决于接入系统的使用方式, 但是大概率是固定的 (同一个系统的授权api, 短时间内其action_pks是一致的)
- group_members, 上限 1000; 并且在权限变更的时候, 成员变动的概率是不大的
- 额外的极端场景: group + action_pks + group_members 全部不变, 循环调用 1000次, 会放大 1W 倍到db

----------

所以, 目标是
1. 避免极端场景导致数据库问题
2. 非极端场景, 也尽量能保证去重, 减少计算逻辑
3. 除了去重, 剩余的就是单次事件处理时的数据库操作次数(当前是 6 次)

**Comment by wklken** [comment]
另外, 单条event 100个 message, 处理大概 1s; 

此时, 未去重的情况下, 2 个操作+500个成员, 会产生 20000 个event, 需要处理 5 小时

**Comment by wklken** [comment]
## 方案

event还是按照原先的模式切分, 保证 1s 能处理完一个event

----

groupPK - actionPK - subjectPKs

发消息的时候, 顺带放到cache

Key=groupPK:actionPK:subjectPK

如果key存在, 则消息不发送; 
否则, 发送消息, 并set key(TODO: ttl?)

------

消费者, 消费一个event的时候, 从redis删除这个key(TODO: 处理失败怎么办? no acked? )

保证, 一个消息未处理前, 队列中有且仅有一条;

------

这样, 如果的确是队列很慢, checker也无法重复放消息进去;

checker 需要改机制, 如果 100 条, 处理了 50 条, 还有 50 没处理, checker的时候怎么保证已处理的不会被重新放入队列?

**Comment by wklken** [comment]
https://github.com/adjust/rmq#push-queues


incomingQ     ------------->    actual queue
set the key     wait 5s/30s     delete the key

incomingQ 进来, 第一个consumer, 需要确保消息delay 5s消费, 之后放入actual queue

**Comment by zhu327** [comment]
触发事件的场景：

1. 用户组授权

- 授权会同时有多个操作
- 用户组的所有的成员的rbac表信息都是需要变更

2. 用户组成员变更（新增/删除）

- 批量变更成员
- 用户组所授权的所有操作都需要变更成员对应的rbac数据

---

事件定义：

subject action group

变更成员的场景下基本不会有重复的情况出现，即使是api也不会

用户组授权的场景，频繁的变更实例权限，但是操作是固定的，会导致出现重复的事件， 单个用户组重复操作可解，通过signature

---

大规模api请求：

1000个用户组，每个用户组有1000个成员，每个用户组授权5个操作，会突发产生 1000 * 1000 * 5 个事件

1000个用户组，已授权5个操作， 每个用户组变更成员100个， 会突发产生 1000 * 5 * 100 个事件

措施：

1. api限流，没分钟只能有多少次调用

---

假设抛开存储，有kv的方式来管理事件

可以对单个事件去重，对事件消费限流，延迟实现，不怕突发

**Comment by zhu327** [comment]
队列1

- 消息格式 subject action group
- 比如用户组有成员1000个，授权5个操作，则会产生5000个事件
- 消费者拿到消息后，写入 subject action groupSet 存储， 同一个subject action的数据只有一条，groupSet用来去重，并合并所有变更的group
- 存储中的数据创建操过 一定时间 （比如1分钟） 后，发送到队列2

队列2

- 消息格式 subejct action groupSet
- 消费者拿到后handler操作不变，更新对应的subject action rbac数据

**Comment by zhu327** [comment]
存储：

redis set

key: subject + action
value: groupPK set

添加：

SADD key group_pk

获取：

pipline： 同时进行

SMEMBERS key
DEL key

延迟队列：

redis zset

key：ts_set_key
score: ts
value: 以上key

设置：

ZRANK key member
如果不存在
ZADD key score1 member1

查询：

获取小于制定时间的所有数据
ZRANGEBYLEX key min max [LIMIT offset count]

---

当有事件产生时：

向redis key：subject + action

SADD key group_pk
ZRANK ts_set_key key 判断是否有
如果没有
ZADD ts_set_key ts key

数据消费：

定时获取zset中小于当前时间1分钟之前的所有key

ZRANGEBYLEX ts_set_key 0 ts-1min [LIMIT offset count]
ZREMRANGEBYLEX ts_set_key 0 ts-1min 获取之后再移除

遍历以上keys

SMEMBERS key
DEL key

发送消息到队列2
