### ISSUE TITLE
【废弃】分级管理员支持二级权限分治

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#1358]

**Comment by Xmandon** [comment]
上周讨论： 有些空间，比如项目，涉及到的团队比较泛，项目管理员无法精确管理所有资源的权限，需要将「授权权限」进一步下放，下放方案：
1. 分级管理员再创建子分级管理员，划分授权范围子集；（方案存在分级管理员嵌套，无法支持多层）
2. 分级管理员将用户组分类组合，每个组合可定义「管理员」，该管理员可以授权组合下的用户组和相关审批，比较符合LD的预期，每条流水线的用户组组成一个集合，然后指定管理员；（本质上跟实例分级管理员没有区别？）
3. 分级管理员下每个用户组支持「组管理员」定义，类似「主机负责人」；（ld的话，同一条流水线的用户组统一设置？）

**Comment by Xmandon** [comment]
蓝盾最后一次评审结论：权限中心支持用户组分组管理能力。 具体形态本周再做一次评审

**Comment by zhu327** [comment]
分级管理员将用户组分类组合，每个组合可定义「管理员」，该管理员可以授权组合下的用户组和相关审批，比较符合LD的预期，每条流水线的用户组组成一个集合，然后指定管理员；（本质上跟实例分级管理员没有区别？）

---

需要在组成员上打标记, 涉及相关逻辑:

1. 用户组在成员时, 打标记
2. 标记是否可以更新, 即是否可以回收标记, 是否可以新增
3. 提供相关api
4. 审批时用户组如果没有标记的管理员如何处理

---

saas增加标记的表, 后台不处理该逻辑

**Comment by zhu327** [comment]
在itsm增加用户组管理员的审批节点

**Comment by Xmandon** [comment]
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/19284021/188031356-8edf998b-0cb7-4c94-b672-7621995c9cc9.png">

<img width="1249" alt="image" src="https://user-images.githubusercontent.com/19284021/188031376-f7cc2050-f1b7-4082-9191-1b974e657aa8.png">

<img width="1903" alt="image" src="https://user-images.githubusercontent.com/19284021/188031583-3b4ea7bc-8eb8-4887-bc03-299d390ddf00.png">

<img width="1254" alt="image" src="https://user-images.githubusercontent.com/19284021/188031603-e9e2e07a-e21d-4f83-a737-9fc578e7d873.png">

**Comment by Xmandon** [comment]
对于ci系统来说，每条流水线会对应一个二级管理员，二级管理员下会有内置3个用户组。

**Comment by EchoQT** [comment]
给蓝盾内置的所有相关设定在权限系统上是如何落地的？
最终的完整方案请在帖子正文中完整阐述。

**Comment by zhu327** [comment]
### 疑问

1. 二极管理员未创建时, 用户组是直接与分级管理员关联, 这个时候如果没有二级管理员, 怎么切换到全局的用户组?
2. 用户本身没有分级管理员身份, 怎么切换到二级管理员, 如何体现这个用户组他不是分级管理员, 但是是二级管理员?

**Comment by zhu327** [comment]
目前用户组只能是 对应的分级管理员审批，但在RBAC下，需要由接入系统决定每个用户组对应的审批者

---

二级管理员涉及到用户组的申请加入的审批

**Comment by Xmandon** [comment]
方案原型需重新评审

**Comment by Xmandon** [comment]
分级管理员边界范围缩减的时候，子分级管理员的处理逻辑

**Comment by Xmandon** [comment]
重新评审原型方案，转新issue：#1528
