### ISSUE TITLE
支持代替他人/组织申请权限

### ISSUE THREAD

**Issue by Zoeyzhou11** [TencentBlueKing/bk-iam-saas#1360]
**需求背景**
当前权限只能通过管理员授权/用户自己申请；需要支持代替他人申请权限的功能

**需求描述**
一）申请前
1、支持代替他人申请加入用户组
（1）在【申请权限】上方，增加【权限获得者】配置项，输入框类型为下拉搜索。支持模糊搜索组织/用户。（需要技术评估是否支持代替组织申请权限）
<img width="842" alt="image" src="https://user-images.githubusercontent.com/110165979/184595762-a686fd7d-012f-4ae2-90dc-dead0d022835.png">
2、支持代替他人申请自定义权限
<img width="852" alt="image" src="https://user-images.githubusercontent.com/110165979/184595952-4c9c531a-e8c6-486b-b0d5-198e967f9aa4.png">
3、从saas页面点击无权限操作并前往权限中心申请权限时，支持代替他人/组织申请权限
<img width="845" alt="image" src="https://user-images.githubusercontent.com/110165979/184596125-c83ec16a-6c1d-4626-85a1-82e9b6dbab90.png">

二）申请时
申请权限流程中，添加【权限获得者】字段
<img width="950" alt="image" src="https://user-images.githubusercontent.com/110165979/184596957-615ee9a2-daba-4d77-9821-e4b626e24ee3.png">
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/110165979/184599773-11d309de-e86c-453b-8e34-36e719a81bb3.png">

三）申请后
若申请成功，权限获得者会在【自定义权限】中查看到自己拥有的权限

**Comment by zhu327** [comment]
自定义权限只能授权到用户, 不能授权的组织, 所以这里只能申请用户的自定义权限

**Comment by zhu327** [comment]
- 自定义权限申请增加被授权人字段, 允许为空/不传, 如果为空需要补充为当前操作人自己
- 自定义申请详情中需要给到权限申请人字段
- ITSM自定义申请单中需要补充到被申请人信息
- 申请单回调处理时需要批量处理申请人

---

问题:

当前在处理申请人为自己时, 会把提交的信息中剔除已有的权限, 如果是为他人申请这里怎么处理, 批量的人怎么处理

**Comment by Xmandon** [comment]
保留现有逻辑，只判断跟“申请人”是否有权限，跟“其他权限获得者”无关

**Comment by lhzzforever** [comment]
done

**Comment by lhzzforever** [comment]
done
