### ISSUE TITLE
无权限跳转申请有效期变成“永久”问题

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#1364]
<img width="2508" alt="image" src="https://user-images.githubusercontent.com/19284021/184784110-72b09229-51b9-4d75-b170-3a8d5677e74e.png">

<img width="2506" alt="image" src="https://user-images.githubusercontent.com/19284021/184784178-b7217298-a744-41f5-bee6-50566d8f1962.png">

**Comment by lhzzforever** [comment]
这边环境测试正常，无法复现
