### ISSUE TITLE
[蓝盾] 蓝盾对接跟进

### ISSUE THREAD

**Issue by zhu327** [TencentBlueKing/bk-iam-saas#1384]
1. 跟进对接进度
2. 跟进对接中的问题
3. 跟进蓝盾新的对接相关的需求

**Comment by zhu327** [comment]
https://github.com/TencentBlueKing/bk-iam-saas/issues/1358

**Comment by zhu327** [comment]
通用的内嵌页面需求: 蓝盾或其他系统, 都可以内嵌页面 => 过多的定制, 如何进一步解耦

- 内嵌权限中心的页面, 都需要能隐藏左侧导航 / 
- 蓝盾: 红点 => 事件发生时, 需要推送 => 蓝盾需要有链接
            -> 不用推, 权限中心提供接口可以查, 是否有事件
- 所有内嵌页面, 只展示蓝盾的数据
   - 我的权限页面: 去掉`权限申请`按钮, 列表中只展示蓝盾的数据
- 我的申请单  => 拉的itsm接口 => 是否能过滤 iam下蓝盾的这个人的申请单
- 申请权限 => 申请加入用户组 => 给一个流水线, 需要给到 流水线拓扑, 查出所有的组列表 (项目->流水线组->流水线)
- 申请权限 => 过滤分级管理员下用户组列表 => 根据 资源名称 过滤 / 根据操作id过滤
- 拉去用户组在iam 的权限列表 

- 额外的需求: iam 提供功能, 给用户组打标记 相当于根据label
- 流水线的用户组的权限是锁死的 => 超管进来也不能编辑; 相当于这里的组权限是锁死的, 无法增删改咋   => readonly标记的组不能改权限 / 前端交互需要屏蔽变更的入口
- 申请创建分级管理员 => 申请内容完全自己填充
   - 标题  / 申请内容  => 蓝盾提单的时候传: 内容蓝盾自己根据 ITSM 协议拼接
   - 申请理由(应该目前可以传)

=========================

刚才记录的会议纪要

会引入两个复杂度:
1. 前端, 页面如何被内嵌, 并且被内嵌页面需要感知到被什么系统内嵌
    - 根据后台配置, 按钮屏蔽/页面屏蔽/交互差异等等
    - 发起后台接口时, 需要附带系统参数
2. 后台
    - 如何做差异化的配置
    - 所有展示页面, 如何只获取某个系统的数据

需要整体讨论下, 再考虑怎么做, 理论上我们应该做到任意系统可以内嵌我们的页面, 并且页面元素使可配置的; 
但是需要考虑, 这种定制化的处理给代码带来的复杂度. 

权限中心要做可配置, 但是不应该主体逻辑变成`定制的`

**Comment by zhu327** [comment]
- 前端内嵌页面
- 后台接口数据隔离
- 基于系统的功能屏蔽设置(相当于全局有一批配置, 前端拉取后, 根据配置展示)

**Comment by zhu327** [comment]
1. 我的权限页面展示指定系统的用户组
   - 包括已过期的用户组
   - 用户组列表需要筛选
2. 申请单列表筛选指定系统的申请单
3. 用户组权限详情
   - 无法修改权限的用户组 -- 问题? 什么情况下无法修改用户组
4. 屏蔽
   - 系统列表指定系统屏蔽
   - 权限列表中指定系统屏蔽
   - 申请单列表指定系统屏蔽
   - 用户组列表指定系统屏蔽
5. 分级管理员的创建指定邮件中title, 描述, 范围信息等
   - 问题? 这里的分级管理员是什么概念, 直接对的是统一使用系统管理员
6. 分级管理员的审批人需要是上级
7. 分级管理员的创建申请

---

原型相关问题:

1. 用户组权限的展示还是按照操作-资源实例维度
2. 所以每个项目都需要创建一个分级管理员, 需要评估分级管理员的数量, 以及在权限中心如何屏蔽分级蓝盾的分级管理员
3. 在权限中心这里对用户组的操作是需要有分级管理员身份的, 这个身份在蓝盾的页面上如何处理
4. 蓝盾原型上的权限模板是什么东西, 如何维护?
5. 项目的停用, 在权限中心如何处理?
6. 项目的信息中, 人员的范围怎么传过来, 部门的id是怎么体现出来的, 限制权限中心用的部门id是用户管理来的
7. 查询资源实例的有权限的用户组 -- 需要特定的rbac api支持
8. 查询项目下的用户组
9. 什么身份, 什么人能进入权限管理的页面
10. 资源管理员是什么???
11. 资源名称筛选用户组做不了
12. 输入操作筛选用户组
13. 我的权限/我的申请/我的审批的红点什么意思

---

前端处理的问题:

1. 分级管理员的身份怎么过来, 切换身份怎么实现

**Comment by zhu327** [comment]
1. 提供创建项目管理分级管理员的api
   1. 分级管理员名称
   2. 分级管理员描述
   3. 分级管理员的授权范围: 权限/人员
   4. 分级管理员的成员
   5. itsm审批单的回调callback地址
   6. 需要有一个蓝盾申请创建分级管理员的默认流程
   7. 返回权限中心申请单id, itsm审批单sn -- ci可以拿sn到itsm查询审批单状态
2. 权限中心审批单状态变更接口 -- 需要白名单
   1. itsm回调ci后, 需要通知申请单id对应的审批状态
3. 项目选择列表实现 -- ci到权限中心查询用户的项目查看操作表达式, 解析表达式得到有权限的列表
   1. 项目的选择列表, 权限中心这里只能提供有权限了, 是否能满足ci需求
   2. ci这里还存在创建还没审批的项目?
4. 分级管理员授权范围更新 -- 人员/权限, 确认是否需要 -- ci这边有编辑
5. 申请加入用户组api
6. 项目管理的列表上只能显示用户有权限的 -- 需要确认是否满足ci的需求
7. 分级管理员查询用户组列表, 列表需要有人员数量 -- 不包含二级管理员的用户组列表, 可以通过参数分割
8. 分级管理员创建用户组api -- 已有
9. 管理视图上, 怎么确认用户是否能看到管理视图 ???
10. 创建二级管理员api, 二级管理员在概念上与分级管理员一致
11. 查询用户是否属于用户组, 并且返回过期时间 -- 判断现有的接口是否满足
12. 流水线管理权限是什么意思 ???
13. 筛选分级管理员下的用户组 + 操作, 资源实例, 包括二级管理员的用户组
14. 我的申请单如何筛选来源为蓝盾的 -- api需要支持
15. 我的审批这里如何体现是蓝盾的 -- 需要与itsm沟通

---

前端配置相关:

1. open api支持接入系统注册前端页面配置信息
2. 前端通过web api查询页面系统页面的配置信息

**Comment by zhu327** [comment]
初步评估 2周

**Comment by zhu327** [comment]
1. 我的权限 我的申请 我的审批 小红点数据来源

**Comment by zhu327** [comment]
API列表:

0. 申请model需要增加来源系统, 是否是api的来源
1. 提供创建项目管理分级管理员的api
   1. 分级管理员名称
   2. 分级管理员描述
   3. 分级管理员的授权范围: 权限/人员
   4. 分级管理员的成员
   5. itsm审批单的回调callback地址
   6. 走权限中心现有分级管理员创建的流程
   7. 返回权限中心申请单id, itsm审批单sn -- ci可以拿sn到itsm查询审批单状态
   8. 标识申请来源系统与api类型
2. 权限中心审批单状态变更接口 -- 需要白名单
    1. 传入申请单的id与itsm给的单状态
    2. 需要校验申请单的来源与调用系统是否一致
3. 分级管理员修改申请单创建api
    1. 参考现有web上对分级管理员的修改申请
4. 申请加入用户组api需要增加申请单来源系统
5. 增加查询分级管理员/二级管理员下所属用户组api
    - 返回用户组id, 名称, user_count, department_count
6. 增加分级管理员下用户组搜索api
    - 只有操作id搜索, 走saas policy表
    - 只有资源实例搜索, 走后台rbac筛选api
    - 有操作id, 与资源实例组合, 走后台rbac筛选api
7. 创建二级管理员api
    1. 二级管理员名称
    2. 二级管理员描述
    3. 二级管理员的授权范围: 权限/人员
    4. 二级管理员的成员
    5. url上提供上级分级管理员的id
8. 提供查询用户是否属于指定的用户组
    - 返回true/false
    - 返回过期时间
9. 申请单api处理: 申请创建分级管理员/申请修改分级管理员/申请加入分级管理员
    - 需要添加来源系统
    - 来源场景: api/web
    - 申请单列表支持筛选来源系统与来源场景
    - 创建itsm审批单时提供来源系统: 待沟通
10. 提供按系统注册前端页面配置api
    - 保存一个json
11. web上提供前端配置查询api
    - 按系统筛选

**Comment by zhu327** [comment]
itsm创建审批单时可以传入tag，权限中心通过api创建的申请单，可以把来源系统作为tag给到

**Comment by zhu327** [comment]
- 二级管理员的人员范围需要能同步一级管理员的人员范围, 实时同步

**Comment by zhu327** [comment]
- 实现分级管理员自动授权到成员

**Comment by zhu327** [comment]
用户组成员申请续期

**Comment by mingshewhe** [comment]
- 增加分级管理员下用户组搜索api，待确定，如果页面内嵌，可以暂时不提供
- 用户组成员申请续期，待确定，如果页面跳转，可以先不提供

**Comment by zhu327** [comment]
- 分级管理员的创建, 修改申请谁来审批, 审批流程怎么配置
- 申请加入用户组, 怎么配置审批流程, 二级管理员的用户组需要多个审批吗, 如何配置

**Comment by zhu327** [comment]
项目的成员在哪里管理, 怎么管理, 分级管理员默认关联的权限用户组, 是只读的, 不能管理成员, 成员只能是分级管理员自己的成员管理

**Comment by zhu327** [comment]
需要屏蔽的资源数据:

1. 系统
2. 分级管理员
3. 二级管理员
4. 用户组
5. 申请单

**Comment by zhu327** [comment]
用户组/分级管理员/二级管理员 资源回收

**Comment by zhu327** [comment]
问题:

- 蓝盾的我的有权限的用户组列表, 即将过期的用户组列表, 怎么按系统筛选出来
- 权限中心的我的有权限的用户组列表, 即将过期的用户组列表, 怎么屏蔽不需要的系统

**Comment by zhu327** [comment]
- 提供给蓝盾的接口
- 给到前端定制的接口

都已完成上线到dev
