### ISSUE TITLE
引导问题

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#1396]
<img width="745" alt="企业微信截图_3d779adc-9a96-4717-8254-738d3572aa73" src="https://user-images.githubusercontent.com/19284021/187825792-8bfe91ce-87bb-4624-8973-1719dff3a76b.png">
<img width="351" alt="image" src="https://user-images.githubusercontent.com/19284021/187825839-6d85df5e-6c8f-49eb-a4c9-0cfb6e098a3d.png">

**Comment by lhzzforever** [comment]
done
