### ISSUE TITLE
[Engine] 生产版本待处理问题

### ISSUE THREAD

**Issue by zhu327** [TencentBlueKing/bk-iam-saas#14]
1. [x] 日志优化
   - ES日志中需要写入同步task_id
     - 当前index的task_id是index本身的, 与sync task无关, 任务的执行在同一个goroutine中不好区分, 结论: 不做
   - search api 链路的日志需要写入 request_id 
     - 在search的入口传递 context with value request_id
1. [x] Metric生成
   - 最后同步时间的时间戳: Gauge
   - 同步任务耗时: HistogramVec 同步类型: 全量同步/间隔同步/增量同步 task_id policy_count
   - 同步失败: Gauge
1. [x] Debug info
   ```
   type DebugEntry struct {
       Context  // 上下文, request的相关信息
       Steps  // 步骤, 大步骤就3个, any - doc - eval
       AnyQuery  // 查询表达式与subject结果
       DocQuery
       EvalPolicies  // 匹配的策略信息
       Error  // 错误信息
       SubEntries  // 批量查询时多个Search的子集
   }
   ```
1. [x] 全局state接口
   - 当前时间戳
   - 总的策略数量, 大于过期时间的策略
   - any的策略数量
   - es的策略数量
   - eval的策略数量
   - 最后全量同步时间
   - 最新增量同步时间
1. [x] system - action state
1. [x] 全量同步触发任务
1. [ ] 上云版处理
   - 接入日志采集
   - 接入sentry
   - metric告警
     - 操过5分钟没有进行增量同步
   - healthz监控
   - 接入普罗米修斯
     - dashboard api/task
1. [ ] 快速恢复
1. [x] 慢请求记录
   - es search增加metric
   - 超过2秒的请求记录详细的请求信息

**Comment by wklken** [comment]
1. 改名叫 iam-search-engine
2. 确定swagger的文档是最新的, 且配置正确可以调试
3. 确定api logger的字段满足日常问题排查
4. 上云预发布/正式需要配置日志采集
5. 需要有metrics, 记录最后一次增量同步时间+同步结果 => 配置告警规则, 例如 5 分钟之前一直没有同步, 告警
6. metrics, 记录每一次增量同时耗时/同步记录数
7. 上云环境开启容器监控, 配置图表, 除了常规api请求的metrcis耗时, 增加同步类图表
8. 上云环境配置监控告警, healthz等等
9. 问题: 如何快速知道 目前内存记录数+ES 记录数 = DB 记录数(某个系统/全局)?
10. 记录慢请求: 例如一个搜索耗时 5s, 除了请求详情, 还需要有一些可以排查问题的上下文, 例如es耗时/内存耗时, 命中记录数之类的; 可以考虑引入context? or tracing?
11. 问题: 从saas或 APIGateway 来的请求, 是否带了request_id, 能在所有层的日志中作为一个字段?(这是iam backend没有实现的)
12. 需要确认: 容器化方案, 挂了重新拉起/调度, 能走增量而不是全量
13. 问题: 是否有入口, 可以发起全量更新? 例如发现线上数据差异越来越大想快速先同步一致
14. 上云版接入sentry

------

上面的点很杂, 可以按照分类梳理下, 例如日志/metrics/grafana/告警等等维度都需要做什么

**Comment by wklken** [comment]
> * Gauge

DebugEntry. EvalPolicies 改个名字, 这里没有eval

需要考虑:
1. 单个查询, 会查doc/any/eval, 有顺序, 且每一个有返回数据及统计
2. 批量查询, 是 1 的批量; 存在嵌套关系(列表?)

-----

state 接口需要考虑调用频率过高是否可能给整体服务带来负载, 如果是, 可能做频率控制

-----

期望通过 API 可以触发同步; 也可以查询同步进度(nice to have)

-----

prometheus需要配置
1. up=0 告警
2. 慢请求告警 (5 分钟平均耗时大于多少告警), 此时慢, 但是服务存活的

-----

像 IAM Backend 一样, 在iwiki上给到部署文档(先写, 需要review, 外发时一起放出去)

**Comment by nannan00** [comment]
1. 上云版/企业版 ping拨测告警配置， 企业版需要给到运维同学
2. Metric需要将配置完成的promql给到运维同学，用于企业版统一配置
3. 日志模块可以调整为zap模块，避免后续再生产环境需要切换
4. 性能测试报告数据

**Comment by zhu327** [comment]
### 蓝盾独立实例处理方式

1. 单独一个实例处理蓝盾的数据
   - 不同的实例需要挂载不同的pvc
   - 同步的策略不变, 在同步时根据配置判断该系统的策略是否需要同步
1. 怎么路由不同系统的search请求
   - group cache 类似的路由策略
1. 配置怎么写
1. 怎么部署
   - 运维脚本怎么部署
   - helm怎么部署
1. 监控/日志/metrics

**Comment by zhu327** [comment]
### 全量同步耗时

```
MariaDB [bkiam]> select count(*) from policy;
+----------+
| count(*) |
+----------+
|  1501159 |
+----------+
1 row in set (3.49 sec)
```

372 秒

#### Gap同步耗时

选取updateAt中更新数量最多的一天, 不到

```
MariaDB [bkiam]> select LEFT( updated_at, 10 ), count(*) as cnt from policy Group by LEFT( updated_at, 10 ) order by cnt desc limit 10;
+------------------------+---------+
| LEFT( updated_at, 10 ) | cnt     |
+------------------------+---------+
| 2021-05-17             | 1480634 |
| 2020-09-11             |   12425 |
| 2020-09-14             |    3390 |
| 2020-09-17             |     770 |
| 2020-10-22             |     472 |
| 2021-04-15             |     261 |
| 2020-10-14             |     152 |
| 2021-03-09             |     131 |
| 2021-04-23             |     127 |
| 2020-09-13             |     108 |
+------------------------+---------+
10 rows in set (3.43 sec)
```

383 秒

线上当前数据:

```
MySQL [bkiam]> select LEFT( updated_at, 10 ), count(*) as cnt from policy Group by LEFT( updated_at, 10 ) order by cnt desc limit 10;
+------------------------+--------+
| LEFT( updated_at, 10 ) | cnt    |
+------------------------+--------+
| 2020-09-15             | 195261 |
| 2021-05-24             |  68055 |
| 2020-09-17             |  21731 |
| 2021-05-27             |  16420 |
| 2020-09-16             |  12966 |
| 2020-09-18             |  12512 |
| 2021-07-15             |   4413 |
| 2021-08-24             |   3435 |
| 2021-06-01             |   3329 |
| 2020-10-22             |   3093 |
+------------------------+--------+
10 rows in set (0.39 sec)
```

不到20万, 大概在 52 秒左右

**Comment by zhu327** [comment]
### 问题

1. 全量同步太慢, 150万策略 372秒
1. Gap同步太慢, 一天20万策略, 52秒
1. 策略不区分系统, 导致蓝盾的大量数据影响到其它系统不能ready

### 分析

1. 全量同步
   - 策略的数量不可能变少
   - 还有没有别的同步方式? -- 暂时没有其它好的方式, 之前分析过
   - 同步的过程中, 拉取, 建立索引, task pool有没有优化空间 -- 全链路调优, 代价有点大
1. 增量同步
   - 还有没有别的同步方式? -- 暂时没有
   - 每小时的间隔查询, 是否能优化  -- 全链路调优, 代价有点大
1. 区分系统多实例
   - 同步的方式是否能变更为按系统, 优化? -- 只能按当前的同步方式, 查询回来后再分系统
   - 不同系统的查询路由如何处理  -- 需要调研, 分布式处理复杂度上升
   - 运维部署, helm
   - 日志/监控/metric会更复杂

### 思路

1. 同步时对比update_at是否变更, 再同步
   - 可以实验下是否有效果

### 落地

- 当前每天最多一次变更策略数不超过 20万, Gap同步一次大概52秒, 如果权限中心挂了, 大概有1分钟的时间恢复到数据一致, 但是不影响查询本身, 所以是可以接受的
- *需要保证当前快照数据的正确性*, 不能出错, 否则进入全量同步, 系统会有7分钟左右的不可用

**Comment by zhu327** [comment]
![image](https://user-images.githubusercontent.com/873883/131277737-6064455c-6bb1-43a1-877c-29a01fcc16a9.png)

```
Running 20s test @ http://127.0.0.1:9001/api/v1/search
  8 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   103.78ms   45.41ms 307.02ms   67.62%
    Req/Sec   115.82     37.66   232.00     68.39%
  Latency Distribution
     50%  103.57ms
     75%  133.39ms
     90%  161.70ms
     99%  218.47ms
  18499 requests in 20.05s, 5.75MB read
Requests/sec:    922.59
Transfer/sec:    293.71KB
```

关闭debug, api日志修改为zap后压测结果, 耗时还是2次search上, 下一步计划把es search改为批量查询, 减少查询次数

**Comment by zhu327** [comment]
![image](https://user-images.githubusercontent.com/873883/131313956-f657b890-f136-43b0-bebd-c669aa7bc0a3.png)


初步改造为_msearch后压测数据:

```
Running 20s test @ http://127.0.0.1:9001/api/v1/search
  8 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   134.61ms  222.85ms   1.99s    89.07%
    Req/Sec   170.23     66.19   440.00     71.56%
  Latency Distribution
     50%   60.87ms
     75%  102.60ms
     90%  386.17ms
     99%    1.19s
  26624 requests in 20.07s, 8.28MB read
  Socket errors: connect 0, read 0, write 0, timeout 19
Requests/sec:   1326.38
Transfer/sec:    422.19KB
```

**Comment by wklken** [comment]
出包后, 发布到上云, 配置好响应的日志监控告警等

**Comment by zhu327** [comment]
职责拆分:

1. 拆分职责, IndexerEngine 只做 index 相关的事情
1. 新增 SearchEngine, 只做Search相关的事情
1. 把EvalEngine重新设计成不区分action相关的对象, 在下一层提供 search 的方法, eval engine 既要实现 IndexerEngine 的方法又要实现 SearchEngine 的方法
1. Any Doc相关的实例是否能不区分Engine

**Comment by zhu327** [comment]
重构后:

![image](https://user-images.githubusercontent.com/873883/131835236-b74210a0-a7d4-4d2f-a3d9-fed162dd4b75.png)

```
Running 20s test @ http://127.0.0.1:9001/api/v1/search
  8 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    52.87ms   31.26ms 261.49ms   70.40%
    Req/Sec   234.33     53.60   470.00     67.60%
  Latency Distribution
     50%   47.11ms
     75%   69.22ms
     90%   95.33ms
     99%  148.37ms
  37459 requests in 20.08s, 13.07MB read
Requests/sec:   1865.12
Transfer/sec:    666.63KB
```
