### ISSUE TITLE
我的分级管理员踢出人员问题

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#1400]
<img width="1291" alt="image" src="https://user-images.githubusercontent.com/19284021/187826477-f0a6da61-837a-4aa5-b9d1-67347bb2afd9.png">

<img width="1248" alt="image" src="https://user-images.githubusercontent.com/19284021/187826582-753790e3-c1b6-46ad-a6ce-ec211b42fbb5.png">

应该统一都能踢除其他人

**Comment by huangpeng0428** [comment]
done
