### ISSUE TITLE
【权限中心-已评审】初始化权限数据

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#1413]
## 方案阐述
外部用户需要有开箱即用的权限，那么我们可以根据我们腾讯的实践经验，初始化好一些固定的用户组（比如运维组、查看组），这样用户初次使用蓝鲸平台去申请权限的时候可以直接申请到对应业务的运维组，管理员也省去创建运维组的这一步：

1. 针对CD类的系统，我们可以统一做初始化的工作，因为都是属于「业务」这个空间下的管理模式。

2. 针对蓝盾、bcs这种既有项目、业务对应关系不是1对1的混合空间使用的场景（比如项目对应多个业务），权限中心没法做通用的初始化工作，现在都是这两个系统调接口去做初始化用户组（蓝盾走全托管的方式）。

3. 初始化工作是一次性的，后续系统新增操作不会自动同步到这些初始化的组，权限中心会通过其他的优化方案来达成，让系统一些新功能权限能够及时触达到对应的分级管理员，由分级管理员决定是否要纳入管控。

5. 用户可以在初始化的基础上，自定义用户组。

## 针对CD类的系统，初始化工作为：
<img width="794" alt="企业微信截图_32fdfc69-ea45-476f-9ed7-c3909dc3da18" src="https://user-images.githubusercontent.com/19284021/188612833-ac21d9e6-8547-41ce-bd03-702ea9efafa2.png">

<img width="677" alt="image" src="https://user-images.githubusercontent.com/19284021/188613872-38ad228f-77b7-4b04-9975-18f16aa07914.png">

**Comment by EchoQT** [comment]
每个默认创建的用户组的默认资源是什么，需说明完整。

**Comment by EchoQT** [comment]
ok

**Comment by zhu327** [comment]
做成一种规则, 以便扩充新增的操作, 操作的变更, 如果规则中的操作已经没有了, 需要兼容下, 直接跳过

**Comment by zhu327** [comment]
用聚合的数据结构简化规则

**Comment by zhu327** [comment]
需要确认操作的系统:

1. cmdb
2. 监控
3. 标准运维
4. 节点管理

**Comment by zhu327** [comment]
配置结构:

```json
[
    {
        "system_id": "bk_job",
        "aggregate_resource_type": {
            "system_id": "bk_cmdb",
            "id": "biz"
        },
        "attachment_actions": [] // 附加的操作, 操作可以不关联资源类型, 关联多个操作的资源类型视图的第一级必须为业务
    }
]
```

实现逻辑:

1. 遍历配置, 查询相关的聚合数据
2. 如果有额外的操作, 需要判断操作是否管理资源类型, 如果不关联直接创建, 如果关联多个资源类型需要展开

**Comment by Xmandon** [comment]
已沟通，按照以下方式来搞：
权限中心正在做「初始化权限数据」的功能，即：新建业务后自动创建「业务分级管理员」以及「查看组」、「运维组」。
这里需要各位产品简单配合下，权限中心需要知道运维组、查看组的操作权限结合，所以我想双方约定下，
各产品统一在推荐权限里，定义好：「业务运维」、「业务只读」，这两个常用操作，权限中心统一拉取对应的权限做相应的组初始化，大家看下是否ok？
           
     涉及产品：
           1. 配置平台
           2. 作业平台
           3. 节点管理
           4. 监控
           5. 日志
           6. GseKit
           7.  标准运维

**Comment by Xmandon** [comment]
运维组，描述：${biz}业务运维人员的权限
查看组，描述：仅包含${biz}各系统的查看权限
分级管理员，描述： 管理员可授予他人${biz}业务的权限
