### ISSUE TITLE
用户组添加人员支持“全员”选择

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#1422]

**Comment by Xmandon** [comment]
涉及人员选择器的设计

**Comment by Xmandon** [comment]
分级管理员的人员搜索，如果不在分级管理员下的用户是否可以被搜到，但是样式有区分，提醒管理员如果想添加需要取编辑授权人员范围

**Comment by Xmandon** [comment]
分级管理员有限制人员范围的，如果本身是“全员”是否可以支持？

**Comment by zhu327** [comment]
如果全员都有权限了, 权限的意义在哪里, 如果一定要, 可以考虑添加所有一级部门
