### ISSUE TITLE
常用操作选择覆盖问题

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#1430]
<img width="1396" alt="image" src="https://user-images.githubusercontent.com/19284021/189319491-9467def7-3765-4801-97b2-5c3d47a2b7b2.png">

<img width="1322" alt="image" src="https://user-images.githubusercontent.com/19284021/189319802-bf9fecd0-71ce-4476-aeb9-3f0f84fb3416.png">

**Comment by huangpeng0428** [comment]
done
