### ISSUE TITLE
发版前bugfix

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#1517]
<img width="2552" alt="image" src="https://user-images.githubusercontent.com/19284021/193178450-6a4df6f4-1198-46c8-8f06-d178a7f19295.png">

**Comment by Xmandon** [comment]
<img width="2533" alt="image" src="https://user-images.githubusercontent.com/19284021/193178629-0fdccace-91e8-43cc-b8a3-c9dbedc44f79.png">

**Comment by lhzzforever** [comment]
done
