### ISSUE TITLE
期望能够调整模板名称长度限制

### ISSUE THREAD

**Issue by Zoeyzhou11** [TencentBlueKing/bk-iam-saas#1518]
**需求背景**
客户通过调用接口可以创建超过32字符的权限模板名称，但是在前台修改权限的时候无法保存。
**需求描述**
希望能够调整模板名称长度限制
<img width="724" alt="image" src="https://user-images.githubusercontent.com/110165979/194692185-7e8ec963-f410-4e93-9938-b1fffba743ae.png">

**Comment by Xmandon** [comment]
调整为128

**Comment by zhu327** [comment]
前端处理, 后台默认是128
