### ISSUE TITLE
【已评审】蓝盾对接需求：空间管理员支持是否拥有空间下所有权限的配置

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#1543]
对于空间管理员来说，大部分场景需要同时拥有空间下所有权限，增加此配置来实现（默认关闭兼容存量数据）
<img width="1326" alt="image" src="https://user-images.githubusercontent.com/19284021/197318069-910a0c52-84f7-4ec7-accc-7a29c9057c80.png">

### 逻辑
1. 创建管理空间的时候，打开此配置，管理空间创建完成后，空间管理员自动拥有空间下操作和资源权限
2. 编辑管理空间，关闭此配置，空间管理员则不具备空间下操作和资源权限（除非管理员有添加到空间下其他用户组），即，此配置产生的权限和添加至其他用户组权限是叠加效果。

**Comment by zhu327** [comment]
分级管理员增加自动有权限的配置

- 创建一个分级管理员关联的用户组, 需要对用户组打上标签, 并且是readonly
- 配置打勾时需要自动创建用户组, 并授权, 添加人员
- 分级管理员增减人员时, 判断是否需要同步用户组的关系
- 分级管理员修改授权范围时, 判断是否需要同步用户组关系
	- 全部走自定义权限, 自动同步

**Comment by EchoQT** [comment]
ok

**Comment by EchoQT** [comment]
申请管理员的流程里也有这个feature吧，是的话记得同步加上

**Comment by Xmandon** [comment]
> 申请管理员的流程里也有这个feature吧，是的话记得同步加上

有的，会加上

**Comment by Xmandon** [comment]
显性的用户组的处理方案，人员只能单向管理，用户组侧是readonly？ -- 待确认
