### ISSUE TITLE
[运维] bkop环境纳管上云版集群及部署切换

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-iam-saas#1566]
- [x] 初始化业务/权限用户组/权限等
- [x] agent安装
- [x] bcs纳管
- [x] 监控: 主机监控(确认告警配置/是否能正常发送)
- [x] 监控: 配置拨测(ping/healthz等, 并且看看能否配置核心接口)
- [x] 监控: 开启容器监控, 配置prometheus图标/监控告警等
- [ ] 日志: 配置开发环境日志采集(需要按文件粒度拆分)
- [x] 日志: 配置预发布环境日志采集
- [x] 日志: 配置生产环境日志采集
- [x] 部署: 开发环境切换到bkop发布(需要确认能否使用蓝盾流水线)
- [x] 部署: 预发布环境切换到bkop发布
- [ ] 部署: 生产环境切换到bkop发布

待补充

**Comment by zhu327** [comment]
日志采集需要集群支持CRD, 当前k8s版本 1.14 不知道, 评估下升级影响, 如何升级

**Comment by zhu327** [comment]
跟进:

- 已接入bkop的监控operator
- 配置dashboard, 监控 查询指标报错, 等运维同学处理

**Comment by zhu327** [comment]
跟进:

监控已配置图表, 告警, 但是图表由于指标查询性能不行, 展示有问题, 反馈跟进中
