### ISSUE TITLE
[产品]开发接入页面二期功能设计

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#16]
原型

https://mce66n.axshare.com

**Comment by Xmandon** [comment]
节前设计稿评审

**Comment by wklken** [comment]
相关issue: #64 

![image](https://user-images.githubusercontent.com/2002216/139631679-5de2bc20-9585-433c-8a94-5b09cccf1a4d.png)

**Comment by wklken** [comment]
![image](https://user-images.githubusercontent.com/2002216/139631825-b4b5877c-63ac-4a2e-887c-4c7761338c32.png)

1. place holder目前没有任何意义, 变成: `请输入系统 ID, 一般为接入系统的app_code` 
2. 系统 ID 的place holder里面不应该出现app_code
3. 回调地址, 例如http://xxxxxxx
4. 健康检查路径, 例如 /healthz/
5. 帮助调试中, 注册的示例 跟 更新的示例, 应该保持一致

------

目前给curl调用示例:
1. 开发者可能会误导, 使用成本很高的 curl 方式来注册
2. 前后台的地址不好给到
3. 目前分为 ESB+直连 以及 直接调用 APIGateway 两种, 当前只能二者都存在, 不好提示
4. 复制过去执行, 意味着, 任何问题都可能再提问(大概率环境问题, app_code等错误); 
5. 复制过去执行, 意味着正式下载json执行时, 可能会失败(因为已经存在了) 
6. 相当于又多了一份文档, 目前已经会存在官网文档+APIGateway 文档, 这里未来还需要保证一致性, 代价比较大

------
![image](https://user-images.githubusercontent.com/2002216/139632538-e6d88136-b8fc-479d-a6e7-529321097f64.png)

带图示的说明过于隐晦, 需要更明确易用? 

----
