### ISSUE TITLE
需要支持512字符以上的用户组名

### ISSUE THREAD

**Issue by reggieisrunning** [TencentBlueKing/bk-iam-saas#1606]
场景：
     为了提高用户组辨识度，会出现“{资源类型名}-{资源名称}-{角色}”的用户组命名格式，资源名称会有128个字符左右
需求：
     希望支持512文字符的用户组名

**Comment by wklken** [comment]
如果设置成varchar 256, 大概能存 85 个汉字? 

不能不限制, 限制的话确定长度

**Comment by zhu327** [comment]
最长512

**Comment by zhu327** [comment]
只开给管理类api, web页面逻辑不变

**Comment by wklken** [comment]
512是上限了, 未来不能再往上加了, 如果业务方会超过, 业务方需要自己通过前缀加随机字符串或者db主键的方式标识这个name
