### ISSUE TITLE
在用户组管理时，可以看到用户当前所属的组织架构，以判断用户当前在项目中是否合适

### ISSUE THREAD

**Issue by reggieisrunning** [TencentBlueKing/bk-iam-saas#1609]
场景：
在周期性权限review时，看不到用户的所属组织架构，但是用户名很多不认识，需要反向一个个找用户所属的组织架构，再来判断用户在用户组的合法性，效率很低
需求：
希望在用户组界面中，能看到用户的所属组织架构，用来判断用户在用户组中的合法性

**Comment by Marrywithyou** [comment]
<img width="1668" alt="image" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/42159347/c7d17dd8-29f9-4fe4-9f01-ef6185964bc4">
1、新增「所属组织架构」字段
2、若成员的组织架构信息较多，则多行展示

**Comment by zhu327** [comment]
<img width="1440" alt="image" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/873883/ce4f4f4c-2f47-4d8b-9657-589be30b4ee7">
接口中如果成员类型是user, 增加了 user_departments

**Comment by lhzzforever** [comment]
Done

**Comment by Marrywithyou** [comment]
部门对应的所属组织架构，可以使用下面这个字段。需要前端同学做一个处理，把这个字段最后的部门给去掉（就是不要这个部门自身）
<img width="1068" alt="企业微信截图_7d11f45c-5db5-42cd-b2fb-6abfbb4492f1" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/42159347/54498dd4-d662-48b4-aea2-68d1b2e9b94f">

**Comment by Marrywithyou** [comment]
> 部门对应的所属组织架构，可以使用下面这个字段。需要前端同学做一下处理：
-- 把这个字段最后的部门给去掉（就是不要这个部门自身。例如技术运营部，只需要显示：腾讯公司/IEG 互动娱乐事业群）
--特殊case：如果组织是腾讯公司，这里显示“腾讯公司”即可
 <img alt="企业微信截图_7d11f45c-5db5-42cd-b2fb-6abfbb4492f1" width="1068" src="https://user-images.githubusercontent.com/42159347/251385181-54498dd4-d662-48b4-aea2-68d1b2e9b94f.png">

**Comment by lhzzforever** [comment]
Done

**Comment by Marrywithyou** [comment]
组织的架构没有展示出来，前端同学看一下
<img width="1445" alt="image" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/42159347/73c0bf66-240b-4ca5-8451-01d02abe6a28">
