### ISSUE TITLE
用户组删除权限优化

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#1635]
<img width="2235" alt="image" src="https://user-images.githubusercontent.com/19284021/201935013-ca5d1b8d-3517-47e9-abc3-a2c4ebdf8329.png">
<img width="2276" alt="image" src="https://user-images.githubusercontent.com/19284021/201935140-ef1e4a24-7258-4520-8541-0030e8aa5fc1.png">
<img width="2230" alt="image" src="https://user-images.githubusercontent.com/19284021/201935337-3183bd86-062a-400e-893e-f96918c20408.png">

**Comment by Marrywithyou** [comment]
我的权限界面
![image](https://github.com/TencentBlueKing/bk-iam-saas/assets/42159347/ce87e738-b1f5-4354-8afc-33a32faad9c9)


1、每个系统列表 title右侧新增【批量删除】图标，如上图，点击出现二次确认弹窗。

弹窗文案：确定删除该系统下所有的操作权限吗？

2、操作列表功能，从「删除」➡️「删除操作权限」和「删除实例权限」

4、点击「删除实例」，右侧出现实例详情的界面（且是批量删除状态），「删除部分实例」和「删除所有实例」出现的弹窗如下图
![image](https://github.com/TencentBlueKing/bk-iam-saas/assets/42159347/a6e2993f-716d-4e9a-8d2e-160de378fb40)

**Comment by lhzzforever** [comment]
![](https://user-images.githubusercontent.com/42159347/250738858-46b149ad-d438-4fc1-ba5a-8971b2081a92.png)

**Comment by lhzzforever** [comment]
![](https://user-images.githubusercontent.com/42159347/250738858-46b149ad-d438-4fc1-ba5a-8971b2081a92.png)
这个跟后台协商暂时先不处理

**Comment by lhzzforever** [comment]
![](https://user-images.githubusercontent.com/42159347/250737968-54da5d16-732a-4060-bf13-818da42d0008.png)
这里删除实例权限暂时先不做，只有查看实例权限和删除操作权限

**Comment by lhzzforever** [comment]
https://user-images.githubusercontent.com/42159347/250737679-9c1123bc-d5cc-4efa-bb99-5613b7583aee.png

这个需要提供新接口，相当于删除一个系统下所有的资源，如果一个系统既有权限模板又有自定义权限，该怎么处理

**Comment by Marrywithyou** [comment]
这是在我的权限页面中删除，删除的是当前用户在这个系统下的所有权限。不涉及系统级别的自定义权限和权限模板吧?

**Comment by lhzzforever** [comment]
现在暂时接口不支持同时删除权限模板和自定义权限，已跟edwin和后台确认了，可以先放后，先优化下删除、详情那些吧，删除当前系统下所有权限资源和批量删除关联操作下的资源实例这两个需求延后

**Comment by lhzzforever** [comment]
> 这是在我的权限页面中删除，删除的是当前用户在这个系统下的所有权限。不涉及系统级别的自定义权限和权限模板吧?

我的权限中是可以支持批量删除操作，但是用户组那块会存在权限模板和自定义权限问题，所以现在暂时只先处理我的权限那块的删除

**Comment by lhzzforever** [comment]
如果存在无实例的情况，可以支持删除操作吗
![image](https://github.com/TencentBlueKing/bk-iam-saas/assets/46641918/552e6e1b-c6be-490d-b25a-b59b1988be55)

**Comment by Marrywithyou** [comment]
> 现在暂时接口不支持同时删除权限模板和自定义权限，已跟edwin和后台确认了，可以先放后，先优化下删除、详情那些吧，删除当前系统下所有权限资源和批量删除关联操作下的资源实例这两个需求延后

OKK

**Comment by Marrywithyou** [comment]
> 如果存在无实例的情况，可以支持删除操作吗 ![image](https://user-images.githubusercontent.com/46641918/250849316-552e6e1b-c6be-490d-b25a-b59b1988be55.png)

可以的，这里查看实例资源这里置灰即可～

**Comment by Marrywithyou** [comment]
> > 这是在我的权限页面中删除，删除的是当前用户在这个系统下的所有权限。不涉及系统级别的自定义权限和权限模板吧?
> 
> 我的权限中是可以支持批量删除操作，但是用户组那块会存在权限模板和自定义权限问题，所以现在暂时只先处理我的权限那块的删除

好的

**Comment by lhzzforever** [comment]
![image](https://github.com/TencentBlueKing/bk-iam-saas/assets/46641918/3587cbdd-81d0-4686-a0b0-f75436a4aa6d)
![image](https://github.com/TencentBlueKing/bk-iam-saas/assets/46641918/53623f91-1001-4dad-8fb0-3f2d436736c9)
我的权限查看、删除资源实例icon无法移动到操作项，因为他们会存在有多个资源组的情况

**Comment by Marrywithyou** [comment]
> ![image](https://user-images.githubusercontent.com/46641918/251023763-3587cbdd-81d0-4686-a0b0-f75436a4aa6d.png) ![image](https://user-images.githubusercontent.com/46641918/251024542-90e70bf7-5bce-41b7-9133-d91bcf0a4e44.png)
> 
> ![image](https://user-images.githubusercontent.com/46641918/251023805-53623f91-1001-4dad-8fb0-3f2d436736c9.png) 我的权限查看、删除资源实例icon无法移动到操作项，因为他们会存在有多个资源组的情况，所以它们对应的详情数据和资源实例也有所不同

好的，这个减号图标改成垃圾桶的那个删除图标吧，鼠标hover 住的气泡文案为：去删除实例资源权限

**Comment by lhzzforever** [comment]
Done

**Comment by Marrywithyou** [comment]
1、删除操作下所有实例权限需要优化，参考下图和文案
--如果【不涉及】到依赖的操作：二次弹窗文案为：确认删除实例权限？删除所有实例权限，将一并删除该操作权限
--如果【涉及】到依赖的操作：二次弹窗文案为：确认删除实例权限？删除所有实例权限，将一并删除该操作权限和以下被依赖的操作权限。
![image](https://github.com/TencentBlueKing/bk-iam-saas/assets/42159347/dde562d6-c64b-4431-a32c-baa18c9d535f)

![image](https://github.com/TencentBlueKing/bk-iam-saas/assets/42159347/e855a657-e5cb-4a58-b8d7-1ef6b319c8a7)
3、资源实例列表中的删除图标为什么都是置灰的？  鼠标hover住的文案也不对，应该是：去删除实例资源权限
