### ISSUE TITLE
管理空间功能问题汇总

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#1636]
<img width="2559" alt="企业微信截图_bf0ae1a4-f96c-459b-b414-e03ba503535a" src="https://user-images.githubusercontent.com/19284021/202147003-29491978-ac3b-4f08-8626-6f015e3b3a43.png">

**Comment by Xmandon** [comment]
<img width="2553" alt="image" src="https://user-images.githubusercontent.com/19284021/202148908-6f9d756e-458b-4686-b920-a7bbb82a9f51.png">

**Comment by Xmandon** [comment]
<img width="2559" alt="image" src="https://user-images.githubusercontent.com/19284021/202150694-a6baaba8-c9b3-4650-a30a-acc7bb519951.png">

**Comment by Xmandon** [comment]
<img width="2549" alt="image" src="https://user-images.githubusercontent.com/19284021/202152476-410a0efc-c805-4f8f-b351-3abf6413a22c.png">

**Comment by Xmandon** [comment]
<img width="624" alt="image" src="https://user-images.githubusercontent.com/19284021/202152846-faffc873-cb12-4b6f-a847-c64e231af666.png">

**Comment by Xmandon** [comment]
<img width="907" alt="image" src="https://user-images.githubusercontent.com/19284021/202153319-007cec81-dd50-43ef-8f72-acc03b0d794a.png">

**Comment by Xmandon** [comment]
<img width="2545" alt="image" src="https://user-images.githubusercontent.com/19284021/202154428-eb991098-515b-4944-bcea-529614a44e8a.png">

**Comment by Xmandon** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/19284021/202154806-7aa56f0e-b9bc-4f34-98b3-09551cfe3247.png">

**Comment by Xmandon** [comment]
<img width="1685" alt="image" src="https://user-images.githubusercontent.com/19284021/202155186-400b6f72-0eb6-446f-9105-4b695d2e5bdd.png">

**Comment by Xmandon** [comment]
<img width="2548" alt="image" src="https://user-images.githubusercontent.com/19284021/202188307-b2b58ed5-9629-40ab-95ee-2a190b2a0a48.png">

**Comment by Xmandon** [comment]
<img width="2559" alt="image" src="https://user-images.githubusercontent.com/19284021/202188596-8ee4ffc4-4bd1-4e68-a4d9-829e3f80f8bf.png">

**Comment by Xmandon** [comment]
<img width="1493" alt="image" src="https://user-images.githubusercontent.com/19284021/202373343-33d82b9e-74a3-4c3d-8747-95d7d0ee67e7.png">

**Comment by Xmandon** [comment]
<img width="1462" alt="image" src="https://user-images.githubusercontent.com/19284021/202373471-0133ad42-7eb4-4c29-badd-c9a824498d5b.png">

**Comment by Xmandon** [comment]
<img width="1459" alt="image" src="https://user-images.githubusercontent.com/19284021/202373600-1b2ab6a4-d6b6-476b-9888-b9567d1946e7.png">

**Comment by huangpeng0428** [comment]
> <img alt="企业微信截图_bf0ae1a4-f96c-459b-b414-e03ba503535a" width="2000" src="https://user-images.githubusercontent.com/19284021/202147003-29491978-ac3b-4f08-8626-6f015e3b3a43.png">

done

**Comment by huangpeng0428** [comment]
> <img alt="image" width="2000" src="https://user-images.githubusercontent.com/19284021/202147481-31d82f7b-c7b7-4cfb-ad5f-dfbf1c9e7476.png">
> 
> <img alt="image" width="2000" src="https://user-images.githubusercontent.com/19284021/202147628-fe896bd4-7295-4839-8d64-985b9f191eda.png">
> 
> <img alt="image" width="2000" src="https://user-images.githubusercontent.com/19284021/202147991-1494dad7-49d8-43b0-876c-3aedc3a20157.png">
> 
> 描述、管理员字段是可以在表格直接编辑的，看下设计稿。

done

**Comment by huangpeng0428** [comment]
> <img alt="image" width="2000" src="https://user-images.githubusercontent.com/19284021/202148908-6f9d756e-458b-4686-b920-a7bbb82a9f51.png">

done

**Comment by huangpeng0428** [comment]
> <img alt="image" width="2000" src="https://user-images.githubusercontent.com/19284021/202152476-410a0efc-c805-4f8f-b351-3abf6413a22c.png">
> 
> <img alt="image" width="2000" src="https://user-images.githubusercontent.com/19284021/202155358-3047f4cc-5bf2-4aef-876a-ffdeb8231375.png">

done

**Comment by huangpeng0428** [comment]
> <img alt="image" width="624" src="https://user-images.githubusercontent.com/19284021/202152846-faffc873-cb12-4b6f-a847-c64e231af666.png">

done

**Comment by huangpeng0428** [comment]
> <img alt="image" width="854" src="https://user-images.githubusercontent.com/19284021/202153033-369ef364-e621-4622-9d36-238554975fdc.png">
> 
> <img alt="image" width="780" src="https://user-images.githubusercontent.com/19284021/202153463-ad541488-52b5-4bc7-88c9-efbb76548a51.png">

done

**Comment by huangpeng0428** [comment]
> <img alt="image" width="907" src="https://user-images.githubusercontent.com/19284021/202153319-007cec81-dd50-43ef-8f72-acc03b0d794a.png">
> 
> <img alt="image" width="340" src="https://user-images.githubusercontent.com/19284021/202155590-fee3a63f-9815-4373-bfb6-3fc1fe46463d.png">

done

**Comment by lhzzforever** [comment]
都已修改，有待检验

**Comment by lhzzforever** [comment]
done
