### ISSUE TITLE
权限体系支持三员分立

### ISSUE THREAD

**Issue by Zoeyzhou11** [TencentBlueKing/bk-iam-saas#1642]
### 核心场景描述
不同身份的用户，进入到平台时，会基于其身份授予不同范围菜单访问权限以及页面的操作权限。
例如审计人员只能看到各个saas的审计日志，对saas的其他功能页面没有访问权限。
### 痛点、动机
当前很多金融行业的客户都有审计人员的介入，需要查看平台下的各种操作和记录是否合规等等，于此同时也要求管理员和使用者要严格区分开。因此提出了三员分立的概念。
### 需求
需求约束：身份互斥，用户只能属于以下一种身份，例如用户A不能既是管理员，又是审计员。

审计员：只能查看平台中所有saas的审计日志，无其他页面的访问权限和功能操作权限

管理员：与先有管理员权限一致，用于对用户授权权限。不同在于管理员用户

操作员：即现在平台中的普通用户，能被管理员授予平台中产品的任何访问、操作权限

**Comment by wklken** [comment]
权限中心并不是一个经典的 RBAC 模型(是 ABAC 模型+RBAC 模型); 角色互斥是 RBAC2 里面的概念

目前大部分产品接的 ABAC; 没有`角色`的概念, 只有组(可以当做角色)的概念; 

所以除了超级管理员/普通用户是确认的`角色`, 没有其他确定的项

**Comment by zhu327** [comment]
蓝鲸内部暂无需求
