### ISSUE TITLE
确定单测优先级, 拆分issue

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-iam-saas#1650]
SaaS 目前权限变更逻辑越来越重, 需要有单元测试来保证未来的持续维护

需要从api调用分析, 自下而上确认需要做单测的模块/类/方法/工具等, 然后按照这个粒度拆分issue, 需要经过一个比较长的周期补齐; 

这样, 后面维护代码的时候才更有信心, 效率更高

-----

1. 产品页面核心权限新增/变更/删除/续期接口列表
2. open api核心权限相关接口列表

从上到下, 分析每个api调用的 模块/类/方法   `a.py -> b.py: xxService.call() -> c.py:xxBiz.xxx()`
会分出层级, 出现频率很高的类/方法等

优先级:
1. 工具类/公共类方法等, 不需要mock的, 但是一旦有问题影响范围很大
2. 中/底层调用频率较高的类/方法, 需要少量mock
3. service/biz等核心业务逻辑, 需要较多mock

------

从成本收益的角度去思考加某个单测的收益, 收益越高优先级越高, 越早处理

**Comment by zhu327** [comment]
<img width="898" alt="image" src="https://user-images.githubusercontent.com/873883/203006604-81505fc3-b53d-43f7-95e2-560766a645c6.png">

**Comment by zhu327** [comment]
单测试优先级排序：

1. open api创建分级管理员
2. open api创建用户组，管理员用户组成员，授权
3. open api直接授权

**Comment by zhu327** [comment]
- [ ] https://github.com/TencentBlueKing/bk-iam-saas/issues/321
- [ ] https://github.com/TencentBlueKing/bk-iam-saas/issues/318
- [ ] https://github.com/TencentBlueKing/bk-iam-saas/issues/319
- [ ] https://github.com/TencentBlueKing/bk-iam-saas/issues/317
- [ ] https://github.com/TencentBlueKing/bk-iam-saas/issues/316
- [ ] https://github.com/TencentBlueKing/bk-iam-saas/issues/314
- [ ] https://github.com/TencentBlueKing/bk-iam-saas/issues/315

**Comment by zhu327** [comment]
- [ ] https://github.com/TencentBlueKing/bk-iam-saas/issues/325
- [ ] https://github.com/TencentBlueKing/bk-iam-saas/issues/324
- [ ] https://github.com/TencentBlueKing/bk-iam-saas/issues/323

**Comment by zhu327** [comment]
backend/biz/action_group.py

ActionGroupBiz

- list_with_frontend_id_by_actions
- _fill_frontend_id
- get_actions_by_frontend_id
- _find_by_frontend_id
- get_action_same_group_dict
- _find_action_same_group

---

backend/biz/aggregate_action.py

AggregateActionsList

- _list_resource_type_system_id
- fill_action_name
- fill_resource_type_name

---

backend/biz/application_process.py

InstanceAproverHandler

- _list_approver_resource_node_by_policy
- _split_policy_process_by_resource_approver_dict
- handle

---

backend/biz/instance_selection.py

InstanceSelectionList

- _list_system_id
- fill_chain_node_name

---

backend/biz/policy.py

InstanceBean

- update_resource_name

RelatedResourceBean

- update_resource_name

ResourceGroupBean

- check_instance_selection
- update_resource_name

ResourceGroupBeanList

- _drop_duplicates

PolicyBean

- check_instance_selection
- list_resource_type_instance_count
- update_resource_name

PolicyBeanListMixin

- check_instance_selection
- check_resource_name
- check_instance_count_limit
- get_renamed_resources
- auto_update_resource_name

---

backend/biz/related_policy.py

RelatedPolicyBiz

- create_recommend_policies

---

backend/biz/template.py

ChainNodeList

- match_prefix
- is_match_path

ChainList

- append
- match_prefix

TemplatePolicyCloneBiz

- _gen_clone_policy
- _gen_policy_by_paths
- _gen_action_clone_config_dict
- _gen_action_instance_selection_chain_prefix_list

---

backend/service/models/action.py

Action

- index_of_related_resource_type

---

backend/service/models/policy.py

UniversalPolicy

- _init_abac_and_rbac_data

**Comment by zhu327** [comment]
action相关的方法比较问题, 测试收益不高, 暂不处理
