### ISSUE TITLE
[审计中心] 注册 resource_type&action 时，sensitivity不生效 

### ISSUE THREAD

**Issue by benero** [TencentBlueKing/bk-iam-saas#1670]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):
BUG反馈

**bk-iam-saas SaaS版本/bk-iam后台版本(The versions used):**
bk-iam后台版本

**发生了什么(What happened):**
注册 resource_type&action 时，sensitivity不生效 

**期望是什么(What you expected to happen):**
sensitivity 在查询时按实际注册返回

**如何复现(How to reproduce it):**
curl --request PUT 'http://xxxx/stage/api/v1/model/systems/bk_sam/resource-types/account' \
--header 'X-Bkapi-Authorization: {"bk_app_code": "xxx", "bk_app_secret": "xxxx"}' \
--header 'Content-Type: application/json' \
--data-raw '{
    "id": "account",
    "name": "系统账号",
    "name_en": "Account",
    "description": "",
    "description_en": "",
    "sensitivity": 1,
    "parents": [
        {
            "system_id": "bk_cmdb",
            "id": "biz"
        }
    ],
    "provider_config": {
        "path": "/api/v1/permission/resource/"
    },
    "version": 1
}'

**相关的日志详情(SaaS 及后台日志说明 https://bk.tencent.com/docs/document/6.0/160/8398)和截图等(Log & Screenshot):**

**备注(Anything else we need to know):**

**Comment by zhu327** [comment]
看了下逻辑, 数据库都是存了的, 这里的不生效是指get接口的时候不会给到吗? 具体是哪个接口呢

**Comment by zhu327** [comment]
https://github.com/TencentBlueKing/bk-iam/pull/226
