### ISSUE TITLE
用户组列表支持跨页选择结果展示

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#1680]
场景： 用户通过过滤条件1得到用户组1并勾选上，再次过滤条件得到用户组2并勾选上。并且在下面展示用户已勾选的用户组。

**Comment by Marrywithyou** [comment]
@lhzzforever

**Comment by lhzzforever** [comment]
Done

**Comment by Marrywithyou** [comment]
新交互设计
<img width="1541" alt="image" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/42159347/a37497fb-72f2-4372-82ed-efc5b60bc3f7">

**Comment by lhzzforever** [comment]
Done
