### ISSUE TITLE
[方案]RBAC权限模型对接方案

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#17]
满足内部基于角色授权的业务一个可以快速对接的方案。

**Comment by Xmandon** [comment]
内部产品讨论过一次，需要明确跟用户组本质区别和收益，另外权限策略不能在接入系统存储和管控。

**Comment by wklken** [comment]
https://github.com/TencentBlueKing/bk-iam-saas/issues/671

**Comment by wklken** [comment]
把用户组, 当成角色, 那么目前涉及的 独立的RBAC方案, 相当于是将用户组切分一个维度出来:  实例级别的用户组(支持配置ignore_path的实例视图)

此时, 用户组需要的形态变更: 全局继承(存在 100个限制), 变成几类:

1. 全局(现有的, 依旧存在 100 个限制)
2. 系统级别的(受限, 只能配置本系统权限, 可以再给 100个配额)
3. 实例级别的(暂时不限制, 只能配置本系统并且关联某些实例) 

实现上, `角色`模型套用现在的 `用户组`; 但是底层可能分表存; 

这样做对目前产品形态影响不大; 但是需要考虑这类组的各种`限制`

此时, 需要对应系统鉴权时传递`资源实例`, 才能命中这部分权限数据

**Comment by Xmandon** [comment]
https://yy745q.axshare.com/
