### ISSUE TITLE
【分级管理员】分级/系统管理员无法从用户维度查看权限，期望支持

### ISSUE THREAD

**Issue by pagezz-canway** [TencentBlueKing/bk-iam-saas#1708]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):

**bk-iam-saas SaaS版本/bk-iam后台版本(The versions used):**
最新版本

**发生了什么(What happened):**
【分级管理员】分级/系统管理员无法从用户维度查看权限 

**期望是什么(What you expected to happen):**
权限中心的管理角色有：超级管理员、分级管理员、系统管理员
切换至超级管理员身份时，有'用户'选项卡，可搜索查看用户的权限列表，即从用户维度查看其权限。
分级管理员/系统管理员，没有'用户'选项卡。示例：分级管理员要查看zhangsan的权限，且zhangsan在多个用户组，那么zhangsan的权限就需要到多个用户组中查看。
![image](https://user-images.githubusercontent.com/8849151/206394084-45f8bcd4-4f21-4690-9941-9c3985d7dd0c.png)

**如何复现(How to reproduce it):**

**相关的日志详情(SaaS 及后台日志说明 https://bk.tencent.com/docs/document/6.0/160/8398)和截图等(Log & Screenshot):**

**备注(Anything else we need to know):**

**Comment by Xmandon** [comment]
该需求目前评估没有比较好的方案，主要是：
1. 用户属于多个分级管理员管辖，那每个分级管理员是不是应该只能看到他授予的权限？先不说这个实现难度，总有种“管中窥豹”的感觉
2. 目前有的管理边界是“无限制”的，意味着这个分级管理员可以看到所有人的权限并且修改

**Comment by zhu327** [comment]
由关联issue跟进, close掉
