### ISSUE TITLE
【优化类需求】<生成聚合操作配置>相关任务优化

### ISSUE THREAD

**Issue by Canway-shiisa** [TencentBlueKing/bk-iam-saas#1753]
**问题描述**
目前生成聚合操作配置相关任务周期是每天执行一次，这个执行频率导致的问题：用户新注册操作或部署需要等待一天之后，后台任务才更新到聚合相关的配置，这个期间页面的批量编辑的操作等无法立刻生效

**版本信息**
目前权限中心最新版仍存在该问题

**期望的效果及相关建议**
1.是否能提供一个主动更新聚合操作配置的入口在页面
2.如果1.有实现上的困难，能否将周期任务的执行频率提高一些

**Comment by Xmandon** [comment]
1小时/刷新
