### ISSUE TITLE
【前端缺陷】页面出现<undefined>的展示异常

### ISSUE THREAD

**Issue by Canway-shiisa** [TencentBlueKing/bk-iam-saas#1764]
**bk-iam-saas SaaS版本/bk-iam后台版本(The versions used):**
v1.8.24及v1.8.25均会出现该显示异常

**异常描述及对应截图:**
1.超级管理员角色下，点击<权限管理>页面出现如下异常：
![image](https://user-images.githubusercontent.com/90179140/211703336-d8f4ad0b-df22-4672-aea1-3a1e346f7596.png)
2.<统计分析>页面显示错乱：
![image](https://user-images.githubusercontent.com/90179140/211703378-125f6d1c-3ed1-4d46-8c78-54f0026438e6.png)
3.console异常：
![image](https://user-images.githubusercontent.com/90179140/211703868-995b699a-6b58-4314-a00d-dd4e8845ed14.png)
4.roles/接口返回正常：
![image](https://user-images.githubusercontent.com/90179140/211704215-59ad4d88-2b38-4e39-abed-c7e4a2df7715.png)

**相关的日志详情(SaaS 及后台日志说明 https://bk.tencent.com/docs/document/6.0/160/8398)和截图等(Log & Screenshot):**
saas及后台均无返回相关异常日志

**期望处理:**
1.权限中心saas-v1.8.24是平台3.2的配套版本，这个版本很多项目会使用到，（新版本可能已经做了修复）能否提供基于该版本的临时修复方案便于使用方进行临时修复（需提供修复的具体的方案及变更操作指引）

**Comment by lhzzforever** [comment]
已提供解决方案，组件库版本版本问题

**Comment by lhzzforever** [comment]
组件库版本问题，需待跟后台人员一起讨论解方案

**Comment by Xmandon** [comment]
1.9.x 后的版本已修复，可以更新验证下
