### ISSUE TITLE
[SaaS] 二级管理员版本发布

### ISSUE THREAD

**Issue by zhu327** [TencentBlueKing/bk-iam-saas#1771]
- 与前端/产品确认相关版本的进度信息
- 从分支出alpha版本
- 提交测试, 主要测试点为二级管理员相关逻辑, 一级管理员二级管理员的相关操作
- 版本代码合并出正式包

**Comment by zhu327** [comment]
- 确认帮其它人申请权限功能

**Comment by zhu327** [comment]
蓝盾未支持的部分:

- 用户组名称长度限制
- 用户组成员同步到分级管理员

**Comment by zhu327** [comment]
更新内容:

1. 代码重构
2. 替他人申请权限 (前端)
3. 第三方依赖升级
4. saas redis配置增加sentinel支持
5. 对接审计中心
6. 支持创建二级管理员功能 (前端)

**Comment by lhzzforever** [comment]
更新内容:
1. 支持创建二级管理员功能
2. 支持代替他人/组织申请权限
3. 用户组成员续期页面增加用户单个移除和批量移除操作
4. 修复github上大部分关于前端问题的Issues(已修复的有备注done)

**Comment by zhu327** [comment]
- 体验问题回归

**Comment by zhu327** [comment]
- 已更新到stage环境, 等待前端修复相关问题
