### ISSUE TITLE
依赖操作权限删除问题

### ISSUE THREAD

**Issue by Canway-shiisa** [TencentBlueKing/bk-iam-saas#1799]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):
BUG反馈

**bk-iam-saas SaaS版本/bk-iam后台版本(The versions used):**
最新版本的权限中心仍存在该问题

**异常现象:**
关联权限删除：授权时 <项目编辑>依赖<项目查看>，但是页面可以单独删除<项目查看>权限 => 这里权限上跟授权逻辑就产生了矛盾，是否可以优化

**期望效果:**
实现依赖权限的级联删除，避免跟授权逻辑产生不一致的矛盾

**Comment by Xmandon** [comment]
这个需求合理，可以安排。

**Comment by lhzzforever** [comment]
Done

**Comment by Xmandon** [comment]
考虑接口调用的场景，似乎不需要判断依赖操作，也就是可以单独删掉依赖操作。

**Comment by Xmandon** [comment]
> **是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one): BUG反馈
> 
> **bk-iam-saas SaaS版本/bk-iam后台版本(The versions used):** 最新版本的权限中心仍存在该问题
> 
> **异常现象:** 关联权限删除：授权时 <项目编辑>依赖<项目查看>，但是页面可以单独删除<项目查看>权限 => 这里权限上跟授权逻辑就产生了矛盾，是否可以优化
> 
> **期望效果:** 实现依赖权限的级联删除，避免跟授权逻辑产生不一致的矛盾

涉及依赖操作删除的场景：
1. 删除自定义权限的时候
<img width="2121" alt="image" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/19284021/07fc43fe-1317-4b4f-ad3c-b6531d62a3b7">


3.  用户组删除权限
<img width="2244" alt="image" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/19284021/4bd68137-333f-4b43-a18f-a87da8d706dd">


<img width="1834" alt="image" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/19284021/b57048bd-b0eb-4623-97c3-a678f8272323">

**Comment by Xmandon** [comment]
关联需求：#2030

**Comment by zhu327** [comment]
> > **是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one): BUG反馈
> > **bk-iam-saas SaaS版本/bk-iam后台版本(The versions used):** 最新版本的权限中心仍存在该问题
> > **异常现象:** 关联权限删除：授权时 <项目编辑>依赖<项目查看>，但是页面可以单独删除<项目查看>权限 => 这里权限上跟授权逻辑就产生了矛盾，是否可以优化
> > **期望效果:** 实现依赖权限的级联删除，避免跟授权逻辑产生不一致的矛盾
> 
> 涉及依赖操作删除的场景：
> 
> 1. 删除自定义权限的时候
> 
> <img alt="image" width="2000" src="https://user-images.githubusercontent.com/19284021/243594698-07fc43fe-1317-4b4f-ad3c-b6531d62a3b7.png">
> 3. 用户组删除权限
> 
> <img alt="image" width="2000" src="https://user-images.githubusercontent.com/19284021/243595346-4bd68137-333f-4b43-a18f-a87da8d706dd.png"> <img alt="image" width="1834" src="https://user-images.githubusercontent.com/19284021/243596351-b57048bd-b0eb-4623-97c3-a678f8272323.png">

用户组的权限现在的操作是更新, 不是自定义权限的删除, 所以不能做对应的处理
