### ISSUE TITLE
蓝盾遗留需求

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#1811]
## IAM issue
1、IAM 需提供查询比如拥有「project_view」权限的用户列表接口 --- 暂时使用目前的接口，ed后续考虑支持方式
    - 目前的接口不实时，服务间同步没有保证100%
2、添加成员到用户组时，比如「项目管理员」，需要将用户添加成为分级管理员，存在问题：
    - 可以按照组织架构添加成员，但目前不能按照组织架构添加「分级管理员」--- ed
3、「设置项目最大可授权范围」支持传入初始化数据（内嵌页面，用户在蓝盾进入修改时需要默认选中历史） --- ed/xu
4、查看组权限页面，不希望展示「自定义权限」相关信息 --- ed
5、添加组权限时，去掉「新增模版」 --- ed
6、添加「项目」级别的用户组权限时，希望：--- ed
    - 关于项目的权限，自动选中项目
    - 关于资源的权限，自动选中项目并列出项目下的资源
7、「查看组详情」页面，希望去掉「组名称」、隐藏「组描述」编辑 --- ed
    - 由蓝盾实现编辑「组名称」和「组描述」 --- xu
8、项目级别「管理员」组，组名可以定为「管理员」，无需加前缀 --- ed/ty

**Comment by Xmandon** [comment]
5、添加组权限时，去掉「新增模版」
<img width="2559" alt="image" src="https://user-images.githubusercontent.com/19284021/221080347-10081690-9c94-4f1b-895d-33b0b7ec712a.png">

**Comment by lhzzforever** [comment]
3、4、5、7已完成，其他issues已协商待定

**Comment by lhzzforever** [comment]
因有关的人员目前需要看自定义权限信息，第四点目前已开放
