### ISSUE TITLE
授权/申请权限时，关联资源实例增加批量无限制选项

### ISSUE THREAD

**Issue by pagezz-canway** [TencentBlueKing/bk-iam-saas#1832]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):
需求提交

**bk-iam-saas SaaS版本/bk-iam后台版本(The versions used):**
最新版本

**发生了什么(What happened):**
再根据资源授权时，如果多个操作涉及的资源不一致，无法批量进行编辑，希望能有个批量设置无限制的功能，即都把这些资源实例设置为“*”。

**期望是什么(What you expected to happen):**
<img width="1423" alt="image" src="https://user-images.githubusercontent.com/8849151/223354642-f0dece9c-49d1-49ad-a818-ab30b54c4b43.png">
可以产品页面支持，也可以提供json的编辑方式，让用户手动复制粘贴

**如何复现(How to reproduce it):**

**相关的日志详情(SaaS 及后台日志说明 https://bk.tencent.com/docs/document/6.0/160/8398)和截图等(Log & Screenshot):**

**备注(Anything else we need to know):**

**Comment by pagezz-canway** [comment]
需要改动优化：
1、自定义权限申请页面
2、权限模板新建和编辑页面

**Comment by Marrywithyou** [comment]
用户使用批量编辑时，若多个操作涉及的资源不一致，也增加【无限制】功能。需要改动的页面如下：
1、「平台管理员」新建管理空间选择授权边界时
![image](https://github.com/TencentBlueKing/bk-iam-saas/assets/42159347/ba893d1f-15a5-4c64-abf7-6d493e9c4f57)
2、申请自定义权限时：
![image](https://github.com/TencentBlueKing/bk-iam-saas/assets/42159347/97b6a9d2-e74d-4959-9a5a-fa2613126a3b)

**Comment by lhzzforever** [comment]
https://user-images.githubusercontent.com/42159347/245975991-ba893d1f-15a5-4c64-abf7-6d493e9c4f57.png
这里需要确认下，是所有表格都要有这个无限制功能吗，这块是全局组件，几乎每个资源实例表格都会有这个侧边栏

**Comment by zhu327** [comment]
aggregate_resource_types: [] 传空表示 *任意*

**Comment by Marrywithyou** [comment]
> 不是所有表格都有，只有如下情况需要： 1、申请自定义权限的页面 2、系统管理员和平台管理员新建用户组的页面
1、申请自定义权限的页面
2、系统管理员和平台管理员新建+编辑用户组的页面
