### ISSUE TITLE
分级管理员创建用户组时，人员选择搜索优化

### ISSUE THREAD

**Issue by pagezz-canway** [TencentBlueKing/bk-iam-saas#1838]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):
需求提交

**bk-iam-saas SaaS版本/bk-iam后台版本(The versions used):**
最新版本

**发生了什么(What happened):**
当超管给分级管理员设置的【最大可授权人员范围】非全员时，不能搜索---希望可以搜索
<img width="701" alt="image" src="https://user-images.githubusercontent.com/8849151/223999970-f44cb954-ec36-4b6d-89d3-51da8be1a5ea.png">

**期望是什么(What you expected to happen):**
分级管理员创建用户组时，人员选择搜索优化

**如何复现(How to reproduce it):**

**相关的日志详情(SaaS 及后台日志说明 https://bk.tencent.com/docs/document/6.0/160/8398)和截图等(Log & Screenshot):**

**备注(Anything else we need to know):**

**Comment by Xmandon** [comment]
done 
V1.10.0
