### ISSUE TITLE
推荐自定义权限的时候需要把依赖操作一并推荐

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#1860]
<img width="950" alt="image" src="https://user-images.githubusercontent.com/19284021/226558694-6521d1f6-4446-4041-838b-973d75179f36.png">

<img width="2559" alt="image" src="https://user-images.githubusercontent.com/19284021/226558875-2983bd60-58e5-465e-9974-4285f75f9060.png">

**Comment by zhu327** [comment]
接入系统自行把对应的依赖操作带过来
