### ISSUE TITLE
[SaaS] 对外提供的查询类OpenAPI考虑添加缓存

### ISSUE THREAD

**Issue by nannan00** [TencentBlueKing/bk-iam-saas#190]
目前对外提供的查询类OpenAPI 都没有任何业务数据的缓存，性能比较一般，可以考虑缓存，同时对于OpenAPI的白名单查询，认证鉴权也可以进行缓存

**Comment by wklken** [comment]
优先级提升

1. 白名单需要加缓存, 提升性能
2. 对于查询类, 特别是目前bk_ci使用的接口, 确认是否能加缓存(如果saas侧不能, 后台的 API 保证一致性的情况下使用缓存)

**Comment by zhu327** [comment]
2022下半年规划

**Comment by zhu327** [comment]
https://github.com/TencentBlueKing/bk-iam-saas/pull/1694

**Comment by zhu327** [comment]
处理了鉴权相关的请求缓存
