### ISSUE TITLE
【权限中心-已评审】用户组设置“不可被申请”属性

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#1916]
需求描述： 管理员在创建用户组时，可以设置某些用户组不能被用户主动申请（也不会出现在“无权限推荐”列表），只能管理员主动授权，

1. 新建用户组时，可以设置该属性
<img width="1421" alt="image" src="https://user-images.githubusercontent.com/19284021/232319744-4acf088a-c5ad-4814-8cac-61a9c07a66f6.png">

2. 在用户组列表，可以快速设置该属性
<img width="1396" alt="image" src="https://user-images.githubusercontent.com/19284021/232319902-69059a70-c816-4cbf-b419-108398ae5384.png">

**Comment by zhu327** [comment]
1. 用户组Model增加对应的bool字段
2. 用户组列表增加对应字段的筛选方法, 默认为False, 由前端判断在什么场景下需要隐藏, 传入True

**Comment by EchoQT** [comment]
ok

**Comment by zhu327** [comment]
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/873883/234857296-0a6523fc-3186-4bde-89ac-e7bc29a30763.png">
<img width="870" alt="image" src="https://user-images.githubusercontent.com/873883/234857569-0f560589-8ecc-465c-bf20-0f4346a20cfa.png">

**Comment by Xmandon** [comment]
空间管理员可以：
1. 设置空间下用户组的“不可申请”属性和“不可见”属性

**Comment by Marrywithyou** [comment]
<img width="1598" alt="image" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/42159347/c3541a1c-6031-4167-84b9-b9966b30fcd6">
<img width="1595" alt="image" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/42159347/75212b92-c711-43a1-b790-65a61dc879b3">
<img width="1172" alt="image" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/42159347/69f5199b-d592-49ae-9063-0f83f0b96e08">

**Comment by lhzzforever** [comment]
需要提供一个用户组设置和用户组列表更换是否变更不可申请状态的接口

**Comment by zhu327** [comment]
<img width="763" alt="image" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/873883/325c2d72-d2e9-44ac-a809-d372b65571c6">
在申请用户组列表增加 apply_disable 筛选参数, apply_disable=false 筛选出可以申请的用户组

**Comment by zhu327** [comment]
<img width="865" alt="image" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/873883/b02cd7e0-762e-402c-aad8-9b4324d9ca1f">
<img width="812" alt="image" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/873883/75ac4bf9-e892-42e1-adaa-80b80da055d9">
<img width="1511" alt="image" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/873883/bccdc09b-8218-4f14-9ff2-754f0ac8c994">

**Comment by zhu327** [comment]
<img width="977" alt="image" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/873883/0fe6ec26-0374-451c-9082-fae18782f696">
<img width="949" alt="image" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/873883/b0750f14-47fb-45e9-a67c-db048a0cf3be">

**Comment by lhzzforever** [comment]
Done
