### ISSUE TITLE
自定义续期带上资源实例展示

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#1937]
<img width="1299" alt="企业微信截图_16823936041862" src="https://user-images.githubusercontent.com/19284021/234171925-53bcb028-5a04-47a1-81ac-cebdec73f609.png">

**Comment by Marrywithyou** [comment]
1
![image](https://github.com/TencentBlueKing/bk-iam-saas/assets/42159347/9cdb414d-818e-4add-9e97-237e6bb252a6)

**Comment by Marrywithyou** [comment]
@huangpeng0428

**Comment by zhu327** [comment]
<img width="1208" alt="image" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/873883/3c8f6e5a-4daf-4fb8-9260-96142b35b590">
接口上增加了policy字段, 字段数据跟用户的查询的policy列表数据结构一致

**Comment by lhzzforever** [comment]
Done

**Comment by Marrywithyou** [comment]
在权限续期这里，没有看到新增的字段。前端同学看一下
<img width="1446" alt="image" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/42159347/7c18f599-135f-4f1c-8eb5-259c7a1f2e2a">
