### ISSUE TITLE
[SaaS] 协作开发: 长时任务展示

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-iam-saas#199]

**Comment by zhu327** [comment]
作为管理后台功能实现:

1. 长时任务列表, 任务类型, 状态, 任务相关参数, 需要根据任务类型来获取
2. 任务详情, 进度, 子任务数量, 子任务的状态, 报错信息

**Comment by Canway-shiisa** [comment]
【排期】
开发方案：20220314
开发：20220315-20220317

**Comment by Canway-shiisa** [comment]
> 作为管理后台功能实现:
> 
> 1. 长时任务列表, 任务类型, 状态, 任务相关参数, 需要根据任务类型来获取
> 2. 任务详情, 进度, 子任务数量, 子任务的状态, 报错信息
> 3. 长时任务失败重试, 只有失败的长时任务才能重试
> 
> https://github.com/TencentBlueKing/bk-iam-saas/blob/master/saas/backend/long_task/models.py
> 
> 现有的长时任务:
> 
> 1. 用户组授权, 需要展示用户组的信息, 子任务需要有授权的模板信息
> 2. 模板更新, 需要展示模板的信息, 子任务需要有用户组的信息
> 
> 以上通过解析任务详情的参数, 子任务的参数可以获取

管理后台功能实现部分疑问：
1. 任务相关参数：任务类型是group_authorization的时候，任务相关参数放置在args这个字段；任务类型是template_update的时候，则是params这个字段？还是说都指的是args字段（看现有的数据 觉得怪怪的 所以确认一下

   ![img](file:///C:/Users/canway/Documents/WXWork/1688850451137178/Cache/Image/2022-03/企业微信截图_1648522144511.png)

2. 子任务参数集是什么概念来着 不太理解，是用来干什么的呢？
3. 任务进度是指？似乎没有在数据字段里面找到有这个标识进度的字段哩，还有就是 任务详情接口 要展示的进度指的是长时任务的进度呢 还是子任务的进度呢？

现有长时任务 的相关疑问：
这一块不太明白是要做啥来着

**Comment by zhu327** [comment]
1. 当前有2个操作需要用到长时任务, 用户组授权, 权限模板更新策略, 具体的参数详情, 需要读api的代码, 多读代码, 把逻辑搞懂, 参数就能明白了
2. 从以上代码的入口入手, 读懂TaskFactory生成长时任务的逻辑, 搞明白子任务是怎么调度的
3. 把上面任务的流程搞明白了, 任务进度自然就明白了

---

做这些需求的目的其实不仅仅是要你完成需求, 如果仅仅是完成需求的话, 我们自己解决起来会省很多事, 主要的目的还是希望你自己能承担一些功能开发, 提升开发的能力

不要怕花时间, 多读读代码, 不要急于把东西做出来, 要做好, 把逻辑弄明白

**Comment by Canway-shiisa** [comment]
##### 思路

- 在mgmt下增加 一个view，以long_task命名；
- 定义LongTaskViewSet，基于该view定义 get 和 retrieve，实现长时任务列表和任务详情；定义post方法实现任务重试



##### 长时任务列表

###### 接口地址

/api/v1/mgmt/long_task/?type=group_authorization



###### 请求参数

| key  | 说明        | 类型   | 请求示例            |
| ---- | ----------- | ------ | ------------------- |
| type | 任务类型    | string | group_authorization |





###### 请求方法

GET

###### 响应

```json
{
    "data": {
        "count":2,
        "results":[
        {
            "type":"group_authorization",
            "status":"running",
            "agrs": [
                {
                    "type": "group", 
                    "id": "33"
                },
                "08bd3eee57074ce0a02cd3174685198d"
            ]
        },
        {
            "type":"group_authorization",
            "status":"running",
            "agrs": [
                {
                    "type": "group", 
                    "id": "23"
                },
                "e49150a66daa4494b9d961c00c91935a"
            ]
        },
    ]
    },
    "code": 0,
    "message": "OK"
}
```



##### 长时任务详情

###### 接口地址

/api/v1/mgmt/long_task/\<int:id\>/

###### 请求方法

GET

###### 入参

长时任务id

###### 响应

```json
{
    "data": {
        "count":2,
        "results":[
        {
            "exception":"group_authorization",
            "status":"running"
        },
        {
            "exception":"group_authorization",
            "status":"running"
        },
    ]
    },
    "code": 0,
    "message": "OK"
}
```



用户组授权要展示用户组信息，子任务需要有授权的模板信息？这个执行成功的子任务不都被delete掉了吗



##### 长时任务失败重试

###### 思路

根据task_id判断长时任务状态，只有失败状态的任务才执行重试



###### 接口地址

/api/v1/mgmt/long_task/retry/

###### 请求方法

POST

###### 入参

```json
{
    "task_id": 2
}
```

###### 响应

```json
{
    "data": {},
    "result": true,
    "code": 0,
    "message": "OK"
}
```

**Comment by zhu327** [comment]
/api/v1/mgmt/long_task/retry/

api的定义保持一致, task_id放到url中

**Comment by zhu327** [comment]
- 长时任务列表中需要有模板名称id/用户组名称id 展示

**Comment by Canway-shiisa** [comment]
方案修改：
1.长时任务重试 接口地址
###### 接口地址

/api/v1/mgmt/long_task/<int:id\>

###### 请求方法

POST

###### 入参

长时任务id

###### 响应

```json
{
    "data": {},
    "result": true,
    "code": 0,
    "message": "OK"
}
```
2.长时任务列表参数【增加用户组名称 或 模板名称 的返回】
```json
{
    "data": {
        "count":2,
        "results":[
        {
            "task_id":1,
            "type":"group_authorization",
            "status":"running",
            "task_params":[ 
                {
                    "id": "33",
                    "name":"用户组B"
                }
            ]
        },
        {
            "task_id":2,
            "type":"template_update",
            "status":"running",
            "task_params": [
            	{
                    "id": "23",
                    "name":"模板A"
                }
            ]
        },
    ]
    },
    "code": 0,
    "message": "OK"
}
```

**Comment by Canway-shiisa** [comment]
长时任务列表中返回的object中 用户组/名称 是拿到长时任务相关参数中的id后进行查询的 如果出现用户组/模板被删除的情况 有如何展示呢？展示为已删除？还是？
