### ISSUE TITLE
[SaaS] 协作开发: 组织架构同步记录展示

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-iam-saas#200]
参考 用户管理的同步记录展示页面

**Comment by wklken** [comment]
如果同步失败, 需要将报错信息脱敏后, 在页面上展示;

让管理员可以直接看到报错信息

-----

进一步, 可以考虑每种错误分别是什么原因导致的

**Comment by Xmandon** [comment]
@nannan00  review
