### ISSUE TITLE
bug：新增/修改蓝盾的用户组权限时，偶现拉取的系统超出范围

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-iam-saas#2028]
新增用户组/修改用户组权限时，系统列表预期只有蓝盾自己，但偶现拉出了所有系统的问题，如下图所示：
<img width="600" alt="image" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/54432927/7dac450c-bfcc-4867-9315-8f9029df89d1">
- 一般是首次操作时出现
- 出现问题时刷新页面，会恢复正常

**Comment by lhzzforever** [comment]
请确认下获取系统列表接口是否有hidden参数
