### ISSUE TITLE
一级管理空间管理员默认具备二级管理空间的相关操作

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#2031]
<img width="2559" alt="image" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/19284021/b97146a1-cb48-45cf-909c-396ee684ee03">

<img width="2546" alt="image" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/19284021/9aba4d3a-bbdd-420c-a957-c4bda00f34fd">

**Comment by zhu327** [comment]
<img width="1390" alt="image" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/873883/2629782f-0faa-40f5-bb48-5f16271d2b74">
进入空间后的页面是这个, 意味者用户当前的角色被切换了, 角色切换是需要用户必须是角色的成员的

**Comment by zhu327** [comment]
考虑下一级管理员的下拉列表中要展示所有的二级管理员吗?
