### ISSUE TITLE
feat：支持和第三方系统进行权限同步

### ISSUE THREAD

**Issue by pagezz-canway** [TencentBlueKing/bk-iam-saas#2037]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):
需求提交

**bk-iam-saas SaaS版本/bk-iam后台版本(The versions used):**
最新版本

**期望是什么(What you expected to happen):**

## 客户原始需求描述 【必填】
希望能够同步Jira、Metersphere等第三方工具的权限，并在蓝鲸统一管理
蓝鲸只做权限同步，不做鉴权，鉴权侵入太深了；三方工具不提供代码做鉴权很难，但是一般会有权限配置接口。
这样可以让第三方已有权限设计的系统，快速、无侵入接入蓝鲸权限中心。

## 核心场景描述【必填】
现状：客户侧有Jira、Metersphere等第三方工具
诉求：希望在蓝鲸权限中心统一管理这些工具的权限
思路：在蓝鲸重建第三方工具的权限体系，双向同步权限改动，不做鉴权

业务场景及流程（以Jira为例）：
1. 在蓝鲸权限中心重建Jira权限体系
2. 保证Jira用户体系和蓝鲸一致（是否首先需要开发基于蓝鲸的统一登录？）
3. 在蓝鲸权限中心修改Jira某个用户的某些权限后，调用权限同步/配置接口，将权限改动同步给Jira
4. 涉及到鉴权时，仍由Jira内部自行完成
5. 如果在Jira修改了权限，同样可以反向同步给蓝鲸权限中心（可选，也可管理手段禁止，不做）

**相关的日志详情(SaaS 及后台日志说明 https://bk.tencent.com/docs/document/6.0/160/8398)和截图等(Log & Screenshot):**

**备注(Anything else we need to know):**

**Comment by wklken** [comment]
Jira只是无数第三方系统的一种, 当前每个系统的权限模型都是不同的
- 无法做通用
- 但是也不应该定制

可以考虑自己做一个`权限中心子系统`, 对接所有第三方权限同步/管理, 然后把这个页面`嵌入`到权限中心, 这个页面本身只做`管理员`角色的鉴权

**Comment by zhu327** [comment]
建议开发对应权限转换的中间系统, 统一走权限中心的admin接口同步数据, admin接口需要走协作开发
