### ISSUE TITLE
feat：“我的权限”页面希望支持过滤

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-iam-saas#2046]
在蓝盾场景下，用户名下可能有多个项目、很多流水线等资源，对应的用户组也成百上千个，当在「我的权限」下确认指定资源或者操作的权限时，很不方便，希望支持根据如下条件组合过滤：
- 资源实例
- 操作
- 用户组名

**Comment by Marrywithyou** [comment]
![image](https://github.com/TencentBlueKing/bk-iam-saas/assets/42159347/c903a2b0-d4c2-4f3d-a244-b02b687a0dcb)
![image](https://github.com/TencentBlueKing/bk-iam-saas/assets/42159347/5aa108df-5724-41aa-90c6-17e8bb7843b8)

**Comment by lhzzforever** [comment]
待后台支持联调

**Comment by zhu327** [comment]
https://github.com/TencentBlueKing/bk-iam-saas/issues/1155

这里需要全量查用户加入的所有的用户组, 然后与search engine查询的有权限的用户组取交集, 不能全量拉用户加入的所有用户组的原因可以看上面这个issue

**Comment by Marrywithyou** [comment]
1、我的权限页面，增加【全局】的筛选功能
2、整体交互参照申请用户组权限，区别是：筛选后是对下面三个tab都生效（目前搜索框只对【用户组权限】和【所属组织用户组权限】生效，使用搜索框【自定义权限】展示为空即可）
![image](https://github.com/TencentBlueKing/bk-iam-saas/assets/42159347/ee97ca1e-f816-4dbe-a554-54e3f55325a8)
3、上方查询之后，下面这个几个tab右侧需要展示本次筛选结果的数量
![image](https://github.com/TencentBlueKing/bk-iam-saas/assets/42159347/d6db3e14-cb59-4cbe-b129-d26e14e991b0)

**Comment by lhzzforever** [comment]
目前所有接口都是分页的，如果通过分页接口数据对比取全量数据，会造成交集数据遗漏风险

**Comment by zhu327** [comment]
增加了接口:

```
/api/v1/users/groups/search/
/api/v1/users/departments/-/groups/search/
/api/v1/users/policies/search/
```

**Comment by lhzzforever** [comment]
Done
