### ISSUE TITLE
cookies 中语言设置错误时，页面空白

### ISSUE THREAD

**Issue by alex-smile** [TencentBlueKing/bk-iam-saas#2047]
**`BUG反馈`

**发生了什么(What happened):**

 cookies 中语言 blueking_language 字段设置为 zhCN 时，iam 页面显示空白，console 有异常日志

<img width="1581" alt="image" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/17827133/f8c2e94a-547d-4491-9a22-50f63fb7f9f8">

**期望是什么(What you expected to happen):**

语言值不符合预期，使用默认语言

**如何复现(How to reproduce it):**

cookies 中设置：blueking_language=zhCN

**相关的日志详情(SaaS 及后台日志说明 https://bk.tencent.com/docs/document/6.0/160/8398)和截图等(Log & Screenshot):**

**备注(Anything else we need to know):**

**Comment by lhzzforever** [comment]
Done
