### ISSUE TITLE
feat：平台自托管场景下，用户组权限展示优化

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-iam-saas#2070]
当涉及多平台的权限时（比如蓝盾里可以给对应的监控空间赋权场景）：
1、添加组权限页面，希望首位默认展示主平台
<img width="303" alt="image" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/54432927/a2b54982-7b78-46ab-91b3-bfae56cd2c89">

2、查看组权限页面，希望首位默认为主平台，且增加平台名称区分是哪个平台的权限
<img width="459" alt="image" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/54432927/ea8a1b80-613d-4088-964a-c1c4ceb4e9da">

**Comment by lhzzforever** [comment]
前端这边加个系统名称展示，数据排序需要后台支持

**Comment by Xmandon** [comment]
按字母序

**Comment by lhzzforever** [comment]
Done

**Comment by Marrywithyou** [comment]
优先展示蓝盾，其余的系统再按照字母排序

**Comment by lhzzforever** [comment]
Done
