### ISSUE TITLE
【前端】编辑用户组，出现属性授权关联失效

### ISSUE THREAD

**Issue by Canway-shiisa** [TencentBlueKing/bk-iam-saas#2073]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):
疑似前端缺陷

**bk-iam-saas SaaS版本/bk-iam后台版本(The versions used):**
最新版本仍然存在该问题

**异常描述:**
自研saas对接权限中心实现了属性授权，新建用户组时，进行属性关联可以正常生效，但是编辑已有用户组的权限时，属性关联失效

1. 创建用户组可以实现关联属性授权（凭据编辑  依赖 凭据访问）

设置凭据编辑的属性条件：
![image](https://github.com/TencentBlueKing/bk-iam-saas/assets/90179140/917dbdb7-df23-4b4c-983c-0b8a47ecb337)

凭据访问自动关联上凭据编辑设置的属性条件：
![image](https://github.com/TencentBlueKing/bk-iam-saas/assets/90179140/7824613c-0a0a-41dd-9693-9e55946a4854)

2. 编辑该用户组，新增 凭据编辑操作 下的属性条件
![image](https://github.com/TencentBlueKing/bk-iam-saas/assets/90179140/59efb045-030b-4a96-bc5f-3169a3f7ebff)

![image](https://github.com/TencentBlueKing/bk-iam-saas/assets/90179140/8e26c9d5-5df3-4ad9-8c93-724e8014a370)

关联操作 <凭据访问> 没有新增对应属性
![image](https://github.com/TencentBlueKing/bk-iam-saas/assets/90179140/f53d4deb-cd97-4a3f-9449-3f4127f1d8ef)

**正常的预期状态:**
无论是新建用户组设置权限的时候还是编辑已存在的用户组权限，都应该进行正常的属性授权关联

**Comment by lhzzforever** [comment]
Done

**Comment by Marrywithyou** [comment]
编辑属性时，保存失败
<img width="1729" alt="image" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/42159347/0f380543-63e4-4d66-b9e4-c169c67dd407">
