### ISSUE TITLE
【前端】系统管理员成员输入框异常

### ISSUE THREAD

**Issue by Canway-shiisa** [TencentBlueKing/bk-iam-saas#2075]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):
疑似前端组件缺陷

**bk-iam-saas SaaS版本/bk-iam后台版本(The versions used):**
最新版本仍然存在该问题

**异常描述:**
添加系统管理员时不输入用户，然后点击输入框直接关闭，输入框无法再次打开，需要刷新页面才可以

![插入系统管理员空白](https://github.com/TencentBlueKing/bk-iam-saas/assets/90179140/33b490ea-99fe-4f98-af0c-892773b0d171)

**预期效果:**
即使点击完输入框后不输入，再次点击仍然应该可以进行正常编辑

**Comment by lhzzforever** [comment]
Done
