### ISSUE TITLE
无权限跳转可以指定 tab

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#2082]
<img width="884" alt="image" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/19284021/03eb49d4-9df5-4d4c-b16b-789d5d29d26e">
<img width="1760" alt="image" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/19284021/899964a3-b53f-44f9-ba66-eb62d86413d9">

**Comment by lhzzforever** [comment]
需要在url添加tab_key字段，如： http://paas6.bktencent.com/apply-custom-perm?system_id=bk_job&cache_id=0f887242a681468597b2a4a95e4daf77&tab_key=independent， tab_key为userGroup跳转到用户组推荐， tab_key为independent跳转到细粒度权限
