### ISSUE TITLE
bcs项目用户组初始化需求优化

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#2083]
BCS-{容器项目名}-查看组，描述为：仅包含{容器项目名}项目的容器、监控、日志系统的只读权限
BCS-{容器项目名}-运维组: ，描述为：包含{容器项目名}项目的容器、监控、日志系统的运维权限

**Comment by zhu327** [comment]
已处理, 上云等发版本后处理
