### ISSUE TITLE
单独部署 bk-iam-saas 服务 报错，依赖的 /api/c/compapi/v2/usermanage/retrieve_user/ 接口不存在

### ISSUE THREAD

**Issue by kingofzihua** [TencentBlueKing/bk-iam-saas#2089]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):

BUG REPORT

**bk-iam-saas SaaS版本/bk-iam后台版本(The versions used):**

 bkiam-saas:v1.8.24

**发生了什么(What happened):**

部署项目的时候 报错

<img width="2468" alt="image" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/21213820/d7561ece-4650-4953-9e48-b798e28359c0">

**期望是什么(What you expected to happen):**

**如何复现(How to reproduce it):**

**相关的日志详情(SaaS 及后台日志说明 https://bk.tencent.com/docs/document/6.0/160/8398)和截图等(Log & Screenshot):**

**备注(Anything else we need to know):**

**Comment by kingofzihua** [comment]
没找到 usermanage/retrieve_user/ 接口在哪个项目中，只在 API Gateway 中找到了这个

<img width="1264" alt="image" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/21213820/0a81c456-0c52-4282-9061-f9acc14076b3">

也找到了个 issues ，不过没太搞懂怎么处理的请求，怎么转换的

<img width="836" alt="image" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/21213820/f36a24c9-15c2-4acd-9d7b-b750cc9a35f2">

**Comment by zhu327** [comment]
依赖用户管理, ESB组件, 确认ESB用户管理是否正常

**Comment by kingofzihua** [comment]
> 依赖用户管理, ESB组件, 确认ESB用户管理是否正常

esb 组件如何部署？
