### ISSUE TITLE
[SaaS] 数据定时清理

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-iam-saas#209]
* 依赖于通用长时任务
* 需要梳理, 各种过期/无效数据的清理
* 例如:
  * 已过期, 超过一年的数据
  * 已经没有被关联的权限模板
  * 无效用户/无效系统等等
  * SaaS侧相关表的清理

---

需要从头清理;

另外之前有一批issue有相关的清理需求, 需要一并查看确认

-----

审计信息再考虑, 本身理论上是不应该删除的, 但是可以清理`被删除的系统/action`等的审计信息

---

所有规则需要落地wiki, 评审后上线

---

- 梳理用户管理同步过程中可能需要清理的数据
   - [x] 部门
   - [x] 用户
   - [x] 用户与部门的关系
   - [ ] 用户组与部门/用户的关系
   - [ ] 角色成员
   - [ ] 角色的授权范围

**Comment by wklken** [comment]
> 目标: 安全地清理, 尽量能保持权限中心核心表数据行数, 减少db查询压力

- 未被引用expression
- 过期的policy
- 过期的用户组成员
- 其他任何可以被清理的数据

------

考虑下关联的内容: 

- 支持删除用户组, 其所有成员关系/权限等等数据
- 支持删除系统
- 支持删除分级管理员/所有组/所有权限等

------

**Comment by zhu327** [comment]
除组织架构未删除外, 其它项都已完成处理
