### ISSUE TITLE
蓝鲸权限续期优化

### ISSUE THREAD

**Issue by Marrywithyou** [TencentBlueKing/bk-iam-saas#2106]
1、蓝鲸权限续期通知，目前只提示了组，没有到具体的人。并且点过期提示没有权限
2、目前作为管理员还需要自己给自己续期权限
<img width="765" alt="image" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/42159347/04e9cac1-cd27-4933-bb53-ff9d29aac824">

**Comment by zhu327** [comment]
统一到通知设置相关需求跟进
