### ISSUE TITLE
点击用户或部门后进行同步按钮点击，出现第三方接口异常提示

### ISSUE THREAD

**Issue by Canway-shiisa** [TencentBlueKing/bk-iam-saas#2136]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):
BUG

**bk-iam-saas SaaS版本/bk-iam后台版本(The versions used):**
最新版本仍旧存在该问题

**异常描述:**
用户同步页面-》点击任意用户或部门-》点击同步按钮-》出现第三方接口异常（最终同步结果是正常的）
![image](https://github.com/TencentBlueKing/bk-iam-saas/assets/90179140/abbbab6c-370c-475b-b6f1-d6fe4e26ad03)
![image](https://github.com/TencentBlueKing/bk-iam-saas/assets/90179140/8d54aceb-bf53-4bbf-a15b-f4aa3d69f5a3)

**预期:**
不管是进入用户页面后直接点击同步按钮，还是先进行用户或部门的点击操作后点击同步按钮，都不应该出现其他接口异常（这里可能前端调用了其他接口导致）

**Comment by lhzzforever** [comment]
Done

**Comment by Canway-shiisa** [comment]
在权限中心下列版本中修复：

saas 1.10.12

后台 1.12.7
