### ISSUE TITLE
【前端】人员选择器滑动优化

### ISSUE THREAD

**Issue by Marrywithyou** [TencentBlueKing/bk-iam-saas#2150]
前端这边做了一个懒加载，为了处理数据量大的问题，滑动的时候只会展示可视化区域的内容~ 这里需要优化
<img width="569" alt="image" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/42159347/d1956133-1068-4ee9-8462-21cbedd6ec36">

**Comment by lhzzforever** [comment]
Done

**Comment by Marrywithyou** [comment]
还是有一点
