### ISSUE TITLE
bugfix：组权限列表资源实例个数错误问题fix

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-iam-saas#2157]
<img width="800" alt="image" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/54432927/d1b7965f-fa36-4702-9d1b-82e34a7427d4">

<img width="600" alt="image" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/54432927/f20b203b-9883-4579-92f7-461b78bbbb5c">

实际只有一个项目，但显示 2 个

**Comment by Marrywithyou** [comment]
经产研排查，应该是旧数据导致的问题（存在2条一模一样的数据，id一致）
<img width="743" alt="image" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/42159347/056fb6df-bf11-4187-8f53-7468baa56d2b">

**Comment by fayewong-v5** [comment]
早期迁移数据时，同时添加了流水线和流水线组导致的，已经fix
