### ISSUE TITLE
双侧抽屉，收起优化

### ISSUE THREAD

**Issue by Marrywithyou** [TencentBlueKing/bk-iam-saas#2158]
<img width="1067" alt="image" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/42159347/56ab747a-bb8b-453e-89db-f607c8626331">

**Comment by lhzzforever** [comment]
这个不是抖动，这是宽度缩减了，按照最新蓝鲸嵌套侧边栏规范，前一个侧边栏要比当前打开的侧边栏像素多200px，关闭的时候要还原之前的宽度，所以视觉上是抖动，实际是关闭嵌套侧边栏后，之前的宽度被还原了

**Comment by Marrywithyou** [comment]
ok
