### ISSUE TITLE
bugfix：项目下的唯一管理员可以在「我的权限」下退出问题fix

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-iam-saas#2163]
项目下应该至少拥有一名管理员，已经支持了「管理员」组下不能退出，但目前可以在「我的权限」下退出
<img width="600" alt="image" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/54432927/3c1e8910-d8be-49ae-b5b7-aa78fe54c908">

**Comment by lhzzforever** [comment]
Done

**Comment by Marrywithyou** [comment]
已修复
