### ISSUE TITLE
feat：续期界面信息太少，无法评估哪些组真正需要提交续期，希望有项目、资源相关信息

### ISSUE THREAD

**Issue by fayewong-v5** [TencentBlueKing/bk-iam-saas#2174]
续期界面信息太少，无法评估哪些组真正需要提交续期，希望有项目、资源相关信息
<img width="800" alt="image" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/54432927/1859248a-b603-4e19-8b1f-60aa92cb9512">

**Comment by Xmandon** [comment]
done
