### ISSUE TITLE
itsm审批单据标题过长处理方案

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#2197]
用户申请多个用户组时，当iam传给itsm的单据标题超过128时，itsm限长会报错，iam这边主动做截断处理，
处理规则：当标题超过64时，用6个省略号代替 + 总数代替，比如：申请加入用户组：英雄联盟业务运维组、dnf业务运维组......等 10 个。

**Comment by lhzzforever** [comment]
![image](https://github.com/TencentBlueKing/bk-iam-saas/assets/46641918/81447474-607b-4131-a12c-5c58930d7128)
现有的接口传参是一个数组，每一个用户组名称对应的是一条数据，无法分割开来
