### ISSUE TITLE
【蓝盾】管理员续期邮件点击跳转链接，网页内容显示空白

### ISSUE THREAD

**Issue by Marrywithyou** [TencentBlueKing/bk-iam-saas#2228]
<img width="1471" alt="image" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/42159347/2687556d-720b-443b-8785-57147f8d6d7b">

**Comment by Marrywithyou** [comment]
目前已初步定位，在续期场景中 iam过滤掉了蓝盾这边的数据

**Comment by lhzzforever** [comment]
Done
