### ISSUE TITLE
【产品】【前端】分级管理员授权有效期支持开放<永久>

### ISSUE THREAD

**Issue by Canway-shiisa** [TencentBlueKing/bk-iam-saas#2263]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):
需求提交

**bk-iam-saas SaaS版本/bk-iam后台版本(The versions used):**
最新版存在该问题

**问题描述:**
超级管理员角色下进行用户组授权，权限有效期可以勾选`永久`：
![image](https://github.com/TencentBlueKing/bk-iam-saas/assets/90179140/514a5cd5-8d00-4a0b-94cc-476162e925d5)

分级管理员角色下进行用户组授权，权限有效期无法勾选`永久`：
<img width="1270" alt="企业微信截图_16938307274476" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/90179140/d1a6b649-5169-47bf-9cca-8768926de0e6">

**期望是什么(What you expected to happen):**
分级管理员角色下进行用户组授权，也支持勾选`永久`有效期

**其他:**
目前后台接口是支持永久的，需要产品评估是否放开后由前端页面进行调整

**Comment by bohanchai** [comment]
<img width="1789" alt="1" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/354dc9a8-0030-49bf-a6cf-d6b4eeb09e62">
<img width="1789" alt="2" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/6c97ec32-67e0-4a6b-a59a-fb51ed52bedb">
<img width="1789" alt="3" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/03872b40-f083-4f7b-982c-76ace6bf85ff">
<img width="1789" alt="4" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/47af2f26-7fa1-4770-80d2-0eb9e7725cc7">
<img width="1789" alt="5" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/425d2e7a-36a4-497e-9710-d08fec072a4e">
<img width="1789" alt="6" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/00916e08-081e-471c-9e38-bdbde9ace36d">
<img width="1789" alt="7" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/41a8b856-c4ba-437b-b992-1d5691e100a4">
<img width="1789" alt="8" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/68ca8747-c766-4b34-bd2e-b151bffeff2d">
<img width="1789" alt="9" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/bb334d32-613c-40cc-9d3d-3ff9e7828b5b">

**Comment by lhzzforever** [comment]
1. 平台管理需要超级管理员身份才会有这个导航栏，如果他不是超管怎么处理
2. 怎么有这么多种排版样式，以哪种为基准

**Comment by Canway-shiisa** [comment]
已实现

**Comment by bohanchai** [comment]
产品评估后，续期不做永久选项
