### ISSUE TITLE
【优化】增加底部版本声明，并支持自定义修改

### ISSUE THREAD

**Issue by Canway-shiisa** [TencentBlueKing/bk-iam-saas#2285]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):
需求

**bk-iam-saas SaaS版本/bk-iam后台版本(The versions used):**
当前最新版本仍旧存在该问题

**目前状态:**
权限中心底部没有类似其他saas会展示版本信息等声明：
- 权限中心页面：
![image](https://github.com/TencentBlueKing/bk-iam-saas/assets/90179140/0fee2886-42ba-46c7-9172-fbb5123bfe41)

- 其他saas参考：
![image](https://github.com/TencentBlueKing/bk-iam-saas/assets/90179140/877ea629-2890-4bd5-941f-fa4618972d34)

**期望效果:**
底部增加版本声明展示，并支持用户自定义修改

**Comment by lhzzforever** [comment]
Done
