### ISSUE TITLE
【免审批】管理空间下，支持用户的视角，查看用户在哪些用户组里

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#2292]
需求背景说明：管理空间下，管理员需要有一个用户视角的管理页面，可以编辑用户加入的用户组。

关联需求：https://github.com/TencentBlueKing/bk-iam-saas/issues/1708

**Comment by bohanchai** [comment]
<img width="1792" alt="1" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/4638bc5c-1df2-466b-8c2e-c04560305bcf">
<img width="1792" alt="2" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/7230e363-3832-4ab7-a78c-e82e7ed5e0bd">
<img width="1792" alt="3" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/51f26fe0-f101-4252-b4ce-c66d2317206f">
<img width="1792" alt="4" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/af0699dd-67f7-4084-86c6-b444420ab4f3">
<img width="1792" alt="5" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/4e7fea23-d59d-42f8-8784-786022fec280">
<img width="1792" alt="6" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/23c0fe34-0dee-4d50-955b-2f76b12fa778">
<img width="1792" alt="7" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/1764a892-9c29-4bc3-a285-d4e1ecb35f8b">
<img width="1792" alt="8" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/ddde0b07-80af-4ecf-9975-7f483f45babc">

**Comment by EchoQT** [comment]
如果该用户在多个管理空间下都有权限，此时该空间管理员可以修改用户在其他空间里的权限吗？

**Comment by Xmandon** [comment]
> 如果该用户在多个管理空间下都有权限，此时该空间管理员可以修改用户在其他空间里的权限吗？

不可以，管理空间只能管理自己空间下的人员。

**Comment by EchoQT** [comment]
后续注意，不要只贴图，要有基本的交互逻辑说明。

1、覆盖用户组的叫法太技术了，可以改为设定用户组，相对于追加有一定的区分度，同时在弹出框中可以对设定功能有简单的说明。
2、当前这个单个用户的修改方式太随意了，连个确认按钮都没有，也可以考虑跟批量操作模式复用同一个弹框。
<img width="427" alt="image" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/108731654/854e8fbe-cdb6-44e3-943e-e5e8b530f5bf">

**Comment by bohanchai** [comment]
在管理空间下增加用户的管理页面，管理用户及其加入的用户组
<img width="1792" alt="1" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/61a01b91-8499-4752-88be-58c1a692e356">
<img width="1792" alt="2" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/e7ce75e4-4a84-4637-97c3-20a4c2730024">
<img width="1792" alt="3" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/6c8ce837-27ab-47b8-84aa-6198395275dd">
批量处理用户加入的用户组，包括编辑、追加、清空
<img width="1792" alt="4" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/c2ba9294-f9ac-486d-bad4-64d3c7bbdd30">
<img width="1792" alt="5" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/cd391c60-7dac-4b64-ad31-662953452f7d">
批量编辑用户组：选择用户组覆盖原有用户组
<img width="1792" alt="6" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/72e389e0-69c1-4c71-942c-7e737f87bae3">
<img width="1792" alt="7" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/9b9b2313-de61-4926-95d1-5e835e336a75">
批量加入用户组：
<img width="1792" alt="8" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/dea69f2c-c9a3-413b-b100-c79dec83343c">
<img width="1792" alt="9" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/8da42f44-e933-482c-8cd1-9df4b9d2f2a7">
批量清空用户组：
<img width="1792" alt="10" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/83099a8a-c3f3-48dc-90a4-6ab4e4e41ae5">

**Comment by EchoQT** [comment]
覆盖直接改成重置吧，单我过了

**Comment by bohanchai** [comment]
1. 在管理空间下增加用户的管理页面，管理用户及其加入的用户组
<img width="1792" alt="1" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/f6c2dbb9-1713-4ec2-ba48-12cde2dbb576">
<img width="1792" alt="2" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/8e5359c2-cf77-4bfd-b79d-f15921ad21e6">
<img width="1792" alt="3" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/5a8b39f2-fa5f-49f6-b3a0-c021b90dc223">
2. 批量处理用户加入的用户组，包括重置、追加、清空
<img width="1792" alt="4" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/ac9c2ab6-9fbd-4be0-908b-3100514be784">
<img width="1792" alt="5" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/64766db9-12ad-44c6-8131-cefd05f9222c">
<img width="1792" alt="6" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/669378d4-d557-448d-bbdc-a4eeac233479">
<img width="1792" alt="7" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/5e43405f-b794-4052-bd2b-4c689a6b0ecd">
<img width="1792" alt="8" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/553bdb29-ac6c-49a7-a6f4-8ac2eb239fc6">
<img width="1792" alt="9" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/b04719a8-6fbe-4794-b942-8414328d99f9">
<img width="1792" alt="10" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/d4544b72-4e9a-419d-b1c6-d8cfc60d09df">

**Comment by fayewong-v5** [comment]
能否支持根据资源实例+操作来查询用户？ 便于管理员来评估对资源实例的权限管理是否合理

**Comment by bohanchai** [comment]
1.  在管理空间下增加用户的管理页面，管理用户及其加入的用户组（选择优化后样式，人员模板可以下拉后分为用户与组织加入方式）
<img width="1792" alt="1" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/d3441c60-caf0-41bb-be63-4c7158c4e38b">
<img width="1792" alt="2" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/0799304f-f7da-47c5-a364-0b604b647adf">

2. 对单个用户退出、添加用户组
<img width="1792" alt="3" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/80c40309-3ac9-43c5-b610-6c749835cc37">
<img width="1792" alt="4" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/a10efcf4-2b57-41f4-ad6d-4baa2178a43a">

3. 对单个用户的多个用户组进行批量操作：批量添加成员、批量退出、批量续期
<img width="1792" alt="5" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/77cf706d-e64b-42ec-9dbb-3c969b5815b6">
<img width="1792" alt="6" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/fb39c1cf-b70e-452a-93ce-3cc325ef0ed2">
<img width="1792" alt="7" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/4aef1966-6ee7-418c-b82d-8f2a467a5c73">
<img width="1792" alt="8" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/9ddd4c65-279a-41c0-86b9-9be52f2b1f7e">

4. 对多个用户的批量操作：chong zhi重置、追加、清空用户组
<img width="1792" alt="9" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/6c3e70f0-cb38-4d30-94d4-87da7b446eee">
<img width="1792" alt="10" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/6a603434-d96c-49df-b1ba-83b475010295">
<img width="1792" alt="11" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/57b23839-222d-46c6-abe4-1c0853718368">
<img width="1792" alt="12" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/e5fdf39d-2d2b-4326-bcea-0adec28b83ab">

5. 增加资源管理模块，可以通过操作与资源实例的方式搜索用户组与用户
<img width="1792" alt="13" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/309c8888-1972-4309-ac5d-fa4fdc61909b">
<img width="1792" alt="14" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/90c5616c-a2ce-4594-be5d-6767d499ba75">

**Comment by zhu327** [comment]
接口已ready
