### ISSUE TITLE
删除完所有自定义权限后，页面样式出现一个方框

### ISSUE THREAD

**Issue by reggieisrunning** [TencentBlueKing/bk-iam-saas#2299]
删除完所有自定义权限后，页面样式出现一个方框
![image](https://github.com/TencentBlueKing/bk-iam-saas/assets/82890468/a2df0145-be05-4107-87ec-3e13cd053cb6)
version：V1.10.12

**Comment by reggieisrunning** [comment]
@Xmandon

**Comment by lhzzforever** [comment]
Done
