### ISSUE TITLE
[方案] 实例有效期 方案4: 作为独立的资源类型

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-iam-saas#230]
## 背景

目前有效期是跟操作绑定的, 例如, 用户有编辑脚本权限有效期到 `2021-12-12 00:00:00`, 那么, 这个操作的所有脚本有效期是一致的, 如果续期, 会全部续;

这种实现方式, 可以应对常见的系统需求; 

但是, 某些情况下, 接入系统安全级别较高(例如登录某台主机), 或者接入系统本身有对应的实例有效期需求(例如执行某条流水线的有效期)

此时, 我们的模型满足不了需求

## 方案

大部分接入系统不需要, 当前的模型满足需求, 那么, 对于需要实例有效期的接入系统, 需要做一些额外的配置

我们暂时没有抽离出一个特定的概念, 假设有效期现在是一个独立的资源类型, 那么, `可以通过操作关联资源+有效期`来实现

编辑脚本权限
- 原先: `edit_script => script`
- 现在: `edit_script => script, ts`

执行鉴权的时候
- 原先: `script{id=1}`
- 现在: `script{id=1} ts{value=1633659529}`

返回的策略:

```
(
    script.id in [1, 2, 3] 
    AND
    ts.value lte 1633659568
)
OR
(
    script.id in [4, 5, 6] 
    AND
    ts.value lte 1633659595
)
```

这个方案的影响:
- 鉴权
    - 分布式鉴权: 无影响, 按操作需要的资源类型chain传递参数即可
    - 集中式鉴权: 无影响
- SDK
   - 无影响
- 查询有权限的资源列表:
   - `有影响`, 多了一个无用的条件
- 配置权限: 这个资源的实例视图, 需要关联官方的实例视图: `时间日期选择框`, 并且, 操作符可以有`lte/lt/gte/gt/between`
   - 问题: `between`是否是强需求? 一定要实现?????

## 其他问题:

- 对于saas的目前的变更冲击有多大? 
- 是否符合bf的需求?
- 是否符合蓝盾的需求? 

## TODO

- 后台需要支持 `lt/lte/gt/gte` 操作符

**Comment by wklken** [comment]
## 讨论

实例有效期不单独通知权限过期? 或者, 如果做通知, 成本有多大?

**Comment by wklken** [comment]
## 讨论

实例有效期和操作有效期什么关系? 实例有效期必须`<=`操作有效期? 或者, 是独立的?

**Comment by zhu327** [comment]
### 问题

1. 产品上怎样选择过期时间类型的实例时间? 更像是一个用户填入的日期值, 而不是当前使用的实例选择的方式, 与实例视图无关?
2. 回收时需要做特殊处理, 走对应的策略, 过期通知也同样处理
3. 为什么不使用属性而是资源类型, 属性可以更细粒度的管理每个资源实例的过期时间? 但是如果使用属性回收与通知会更复杂一些, 也没有新增资源类型容易标识出操作的特殊性
4. engine的搜索只能走eval engine了?

**Comment by zhu327** [comment]
### 工作量

1. SaaS授权部分, 需要支持特殊的过期时间的值的选择, 总体上改动不大
2. 回收逻辑走策略分支, 需要处理, 大部分复用现有逻辑, 改动不大
3. 无权限跳转需要接入系统传多个资源类型, engine现有的逻辑不变, 不需要处理

预期 5人天, 不包括前端的改动

**Comment by wklken** [comment]
> ### 问题
> 1. 产品上怎样选择过期时间类型的实例时间? 更像是一个用户填入的日期值, 而不是当前使用的实例选择的方式, 与实例视图无关?
> 2. 回收时需要做特殊处理, 走对应的策略, 过期通知也同样处理
> 3. 为什么不使用属性而是资源类型, 属性可以更细粒度的管理每个资源实例的过期时间? 但是如果使用属性回收与通知会更复杂一些, 也没有新增资源类型容易标识出操作的特殊性
> 4. engine的搜索只能走eval engine了?

操作关联多个资源类型: 主机+脚本, 此时使用属性, 不能明确关联到谁合适,有歧义

**Comment by wklken** [comment]
## 查询有权限的资源列表 的实现

默认查询得到的策略是

```
(
    script.id in [1, 2, 3] 
    AND
    ts.value lte 1633659568
)
OR
(
    script.id in [4, 5, 6] 
    AND
    ts.value lte 1633659595
)
```

此时, 应该是使用服务端提供的两阶段计算的拉取方式, 传入 `ts.value = 1633600187`, 那么会将`ts`部分先计算掉, 得到的表达式跟加入这个ts这个资源类型之前得到的表达式一致

并且需要明确, 这种处理方式不能cache, 因为`ts.value`直接影响结果

**Comment by nannan00** [comment]
> ## 站在接入系统角度
> 多一种叫做ts的资源类型, 虽然不是不能这么做, 但是处理起来有点别扭
> 
> * 这个类型可以是权限中心默认的, 不需要接入系统注册(这个资源类型, 怎么搞成默认的??????)
> * 鉴权等, 每次都得关注并传递, 且`ts.value`每次赋值都必须是`当前的时间戳`
> * 时间戳有问题, 可能导致权限差异
> * 获取有权限的资源列表, 每次都得先先传`ts.value`过去先进行两阶段计算

对于接入系统，拿到的策略是已经在权限中心服务端去除了ts的表达式，那么如果接入系统判断到某个实例没权限，实际上是已过期了的，但是被权限中心计算ts时去除了，这时候如果去做实例授权，应该如何处理呢？在原先基础上续期？这个复杂度在SaaS上实现好像有点高

**Comment by nannan00** [comment]
> ### 问题
> 1. 产品上怎样选择过期时间类型的实例时间? 更像是一个用户填入的日期值, 而不是当前使用的实例选择的方式, 与实例视图无关?
> 2. 回收时需要做特殊处理, 走对应的策略, 过期通知也同样处理
> 3. 为什么不使用属性而是资源类型, 属性可以更细粒度的管理每个资源实例的过期时间? 但是如果使用属性回收与通知会更复杂一些, 也没有新增资源类型容易标识出操作的特殊性
> 4. engine的搜索只能走eval engine了?

还有产品上分级管理员是否支持也配置具有ts的实例权限呢？如果支持，那么在用户组授权时如何判断是否越过ts授权等，之前只是判断资源实例是否满足，现在如果添加上ts，复杂度可能会比较高，而非之前纯粹的结构化数据判断

**Comment by nannan00** [comment]
> ### 工作量
> 1. SaaS授权部分, 需要支持特殊的过期时间的值的选择, 总体上改动不大
> 2. 回收逻辑走策略分支, 需要处理, 大部分复用现有逻辑, 改动不大
> 3. 无权限跳转需要接入系统传多个资源类型, engine现有的逻辑不变, 不需要处理
> 
> 预计 5人天, 不包括前端的改动

还需要考虑：
1. Action的Related Resource这时候是与Policy不一致的，这个可能会涉及到很多地方的改动，包括校验Policy等等
2. 同步权限模板时，新的资源类型等有效期如何处理？
3. API授权和回收权限时，如何与老权限进行对比？有效期是否参与对比计算

**Comment by wklken** [comment]
## 主体逻辑描述

#### 1. 用户注册权限模型

```
action.related_resource_types = [username, host]   (可以是一个, 也可以是多个)
action.enable_timestamp = true            (默认 false)
action.timestamp_type = [lte, gte, between]   (默认lte)
```

#### 2. 前端渲染

如果发现 `enable_timestamp = true`, 会根据 `timestamp_type` 多渲染一个时间选择框, 可以选取 1-2 个时间戳(between选取两个)

#### 3. 策略提交到SaaS

前端提交代码, 除了原先的结构, 会多一个`_bk_iam_ts_`字段的结构;  新的接口跟原先的解耦, 不会涉及`资源类型`校验等逻辑的校验;

#### 4. SaaS保存策略

如果`_bk_iam_ts_`不存在, 会保持原先的策略表达式逻辑;  `username = tom AND host = 123`

如果`_bk_iam_ts_`存在, 会保存多一个AND`username = tome AND host = 123 AND _bk_iam_ts_ lte 1636097031`

#### 5. 鉴权

调用方无需感知到 `_bk_iam_ts_`的存在, 还是按原先的调用方式鉴权

服务端, 发现`action.enable_timestamp = true`, 会往`evalContext`中注入 `_bk_iam_ts_ = nowTimestamp()`, 然后正常执行

`policy/query`逻辑, 也会执行类似两阶段计算的逻辑, 先将`_bk_iam_ts_`执行完

问题: `_bk_iam_ts_`是否在服务端执行, 或者在sdk执行, 理论上应该是可控的

#### 6. 策略查询

发布订阅, 或者接入系统主动查询策略, 此时必须要理解`_bk_iam_ts_`, 不能走两阶段计算等, 查到什么返回什么;

接入系统如果开启了`_bk_iam_ts_`, 那么必须理解和消化;

**Comment by wklken** [comment]
move to #350 讨论
close
