### ISSUE TITLE
“用户”菜单的搜索补充

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#2300]
<img width="2550" alt="image" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/19284021/0bd6f133-c796-42a0-8246-688eee635bce">

**Comment by lhzzforever** [comment]
Done

**Comment by bohanchai** [comment]
![image](https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/e3b9b2cc-b75e-4653-b41c-0fe3d9a3bf22)
组织也添加搜索
