### ISSUE TITLE
【前端】克隆用户组编辑存在异常

### ISSUE THREAD

**Issue by Canway-shiisa** [TencentBlueKing/bk-iam-saas#2339]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):
bug反馈

**bk-iam-saas SaaS版本/bk-iam后台版本(The versions used):**
最新版本仍旧存在该问题

**问题描述:**
1. 克隆生成的用户组，直接进行权限编辑，无法使用批量编辑按钮；如果退出克隆后进入的用户组权限编辑页面，重新进入，添加相同的权限则可以正常使用
2. 克隆生成的用户组，可以重复添加相同的一批权限

**相关截图:**

![image](https://github.com/TencentBlueKing/bk-iam-saas/assets/90179140/f12a3109-b8ad-4186-a172-e5560a6da775)

**预期效果:**
1. 克隆生成的用户组也需要支持用户组授权时的批量编辑按钮
2. 克隆添加权限的时候要进行重复校验

**Comment by lhzzforever** [comment]
Done

**Comment by Canway-shiisa** [comment]
自定义授权这块验证没有问题，另一个场景：当原始的用户组选择的授权方式是通过权限模板，还是存在问题，这块需要定位后处理下

**Comment by Canway-shiisa** [comment]
自定义授权这块验证没有问题，另一个场景：当原始的用户组选择的授权方式是通过权限模板，还是存在问题，这块需要定位后处理下
