### ISSUE TITLE
自定义权限选择操作收藏后失效

### ISSUE THREAD

**Issue by bohanchai** [TencentBlueKing/bk-iam-saas#2349]
<img width="1645" alt="企业微信截图_f441cc99-6a4f-4c8a-bc26-3f5103cb5f33" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/498d30b9-c0df-48e7-8846-6b92bc54bb26">

**Comment by bohanchai** [comment]
#1068

**Comment by zhu327** [comment]
并未实现, 由其它需求跟进
