### ISSUE TITLE
超级管理类接口-查询 Subject 加入的用户组列表返回用户归属的用户组不包含继承组织架构的用户组

### ISSUE THREAD

**Issue by Canway-shiisa** [TencentBlueKing/bk-iam-saas#2355]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):
需求反馈

**需求背景描述:**
saas旧版本（1.7.x）中，该接口查询指定用户归属的用户组会返回用户个人加入的用户组及用户继承组织架构的用户组
saas新版本（1.9.x）后，该接口查询指定用户归属的用户组只返回用户个人加入的用户组
=》
1. 新版本没有兼容旧版本导致用户定开逻辑会出现异常
2. 该接口的返回不太符合大部分场景需求，客户使用该接口就是为了查询指定用户所在的所有用户组，目前的返回对客户来说是不完整的

**预期效果:**
该接口在查询指定用户归属的用户组时，需要返回该用户加入的用户组及其继承组织架构后拥有的用户组

**相关接口文档:**
https://bk.tencent.com/docs/markdown/ZH/IAM/IntegrateGuide/Reference/API/11-Admin/03-ListGroupOfSubjectJoined.md

**Comment by zhu327** [comment]
可以通过 用户管理 的组件api:

/api/c/compapi/v2/usermanage/retrieve_user/

获取到用户加入的部门id, 然后调用接口获取到对应部门的用户组

**Comment by wklken** [comment]
在这个 commit 中引入的: https://github.com/TencentBlueKing/bk-iam-saas/commit/a034c987fb4b0c3beeb5d12ea4529b311ddd09e5

涉及版本: >=1.9.0

原因: 接口规范化, 单一职责以应对内部系统高并发调用(需要确保性能, 而递归查询经压测验证无法满足需求)

结论: 是一个breaking changes, 需要告知用户升级的风险, 无法兼容

-------


1. 在运维文档/release log 中, 1.9.x/1.10.x 标注 breaking changes  @zhu327 
2. 告知升级后对应接口的风险, 以及如何处理(使用用户管理接口查部门, 自行递归查部门的groups) @Xmandon @zhu327

**Comment by wklken** [comment]
> 在这个 commit 中引入的: [a034c98](https://github.com/TencentBlueKing/bk-iam-saas/commit/a034c987fb4b0c3beeb5d12ea4529b311ddd09e5)
> 
> 涉及版本: >=1.9.0
> 
> 原因: 接口规范化, 单一职责以应对内部系统高并发调用(需要确保性能, 而递归查询经压测验证无法满足需求)
> 
> 结论: 是一个breaking changes, 需要告知用户升级的风险, 无法兼容
> 
> 1. 在运维文档/release log 中, 1.9.x/1.10.x 标注 breaking changes  @zhu327
> 2. 告知升级后对应接口的风险, 以及如何处理(使用用户管理接口查部门, 自行递归查部门的groups) @Xmandon @zhu327

**Comment by zhu327** [comment]
https://github.com/TencentBlueKing/bk-iam-saas/releases/tag/v1.9.2

**Comment by zhu327** [comment]
break change 无法兼容
