### ISSUE TITLE
实例审批人实现不拆单逻辑

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#2360]
需求背景： 某企业财务系统，申请权限审批极敏感，比如用户申请了10个业务的实例数据，分别对应10个老板审批，并且需要这10个老板都同意了对应的单据才能通过。

实现方案参考：我们当前实现了实例审批人，但是我们目前的逻辑是按照实例审批人自动拆单，现在需要另外一套不需要拆单的逻辑，该不该拆单，由接入系统告知。

**Comment by zhu327** [comment]
1. 需要新增一种审批节点类型, 类似于实例审批人, 但是所有的审批人需要合并审批
2. 接入系统收到实例审批人查询请求时需要只返回一个实例审批人, 如果有多个是不是有问题, 因为审批是and的关系, 但是对于单个实例多个实例审批人之间是or的关系

**Comment by Xmandon** [comment]
> 2\. 接入系统收到实例审批人查询请求时需要只返回一个实例审批人, 如果有多个是不是有问题, 因为审批是and的关系, 但是对于单个实例多个实例审批人之间是or的关系

2. 这个结论：多个实例审批人，随机挑取一个发送审批单。

**Comment by zhu327** [comment]
ready, 需要ITSM内置一个类型是instance_approver_merge, processor_source为iam的审批节点类型, 其中的审批人为会签 @Xmandon
