### ISSUE TITLE
[SaaS] 重构Cache模块

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-iam-saas#237]
1. cachetools https://cachetools.readthedocs.io/en/stable/
1. dogpile.cache https://dogpilecache.sqlalchemy.org/en/latest/api.html#module-dogpile.cache.region
1. django cache https://docs.djangoproject.com/en/3.1/topics/cache/#cache-key-transformation

---

需要保证key不冲突

pickle https://docs.python.org/zh-cn/3/library/pickle.html

-----

dogpile.cache 自定义function_key_generator，支持Class
```python
# Note: 使用region.cache_on_arguments() 对类的相关方法应用时，会忽略self和cls参数，进而是在类的所有对象上缓存的，并不是针对某个对象
# 如果需要针对对象缓存，则需要自定义 function_key_generator参数传入cache_on_arguments()里
def generate_function_key_generator(attributes: List[str]):
    """
    生成"key生成方法"的方法，主要用于类的实例方法、类方法、静态方法上
    attributes: 实例方法、类方法、静态方法里使用到的需要区分的实例属性和类属性列表
    比如某个
    """

    def function_key_generator(namespace, fn, to_str=compat.string_type):
        if namespace is None:
            namespace = "%s:%s" % (fn.__module__, fn.__name__)
        else:
            namespace = "%s:%s|%s" % (fn.__module__, fn.__name__, namespace)
        args = compat.inspect_getargspec(fn)
        has_self = args[0] and args[0][0] in ("self", "cls")

        def generate_key(*args, **kw):
            if kw:
                raise ValueError("dogpile.cache's default key creation " "function does not accept keyword arguments.")

            key = namespace
            if has_self:
                key = key + "|" + args[0].__class__.__name__
                attr_value = [getattr(args[0], i) for i in attributes if hasattr(args[0], i)]
                if attr_value:
                    key = key + "|" + " ".join(map(to_str, attr_value))
                args = args[1:]
            key = key + "|" + " ".join(map(to_str, args))
            print(key)
            return key

        return generate_key

    return function_key_generator

```

```python
@region.cache_on_arguments(expiration_time=60, function_key_generator=generate_function_key_generator(["xxxx", "yyyy"]))

```

**Comment by nannan00** [comment]
目前SaaS里使用 Django cache 和 dogpile ，混用，需要统一调研是否有其他缓存库

已知需要解决的问题：
1. 至少需要同时支持内存缓存 和 Redis缓存
2. dogpile 内存缓存必须使用`dogpile.cache.memory_pickle`，否则对于引用对象会出现被`动态`修改的情况
3. dogpile 内存使用 pickle后会导致程序成为CPU密集型程序，进而Gunicron使用gevent会比sync模式还差，只能提升worker数量或者换更好的CPU机器来解决

**Comment by nannan00** [comment]
SaaS cache场景

* Django Cache [Redis]
  - 无权限跳转 ApplicationPolicyListCache 
  - Redis分布式锁

* Dogpile Cache [Redis]
  - 接入系统的资源实例名称 Resource ID/Name 

* Dogpile Cache [Memory Pickle]
  - View层
    - backend.api.authentication._get_jwt_public_key
    - backend.api.authorization.mixins._list_system_allow_list
    - backend.apps.organization.views.get_search_data
    - backend.apps.group.filters._list_pre_application_group_ids

  - Biz层
    - backend.organization.biz._get_category_dict
    - backend.biz.application.get_super_manager_members
    - backend.biz.application.get_system_manager_members
    - backend.biz.application.get_grade_manager_members_by_group_id
    - backend.biz.application._gen_application_system
    - backend.trans.policy._get_action_list

  - Service层
    - backend.service.system.list_client
    - backend.service.resource.get_provider_config
    - backend.service.resource._list_resource_type_provider_config
    - backend.service.action.list
    - backend.plugins.approval_process.itsm.list
    - backend.plugins.approval_process.list_with_nodes

  - Component
    - backend.component.iam.list_resource_type
    - backend.component.iam.list_action
    - backend.component.iam.list_instance_selection
    - backend.component.resource_provider._search_instance
