### ISSUE TITLE
用户菜单搜索补充

### ISSUE THREAD

**Issue by bohanchai** [TencentBlueKing/bk-iam-saas#2379]
![image](https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/d3631314-392a-43f1-a303-4abf20e9e369)
与用户增加搜索一样，组织也添加搜索
![image](https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/9e161dc5-da9d-46a8-a0f7-988177085469)

**Comment by bohanchai** [comment]
#2300

**Comment by lhzzforever** [comment]
Done
