### ISSUE TITLE
容器化版本，https页面中请求http资源异常问题

### ISSUE THREAD

**Issue by Canway-shiisa** [TencentBlueKing/bk-iam-saas#2389]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):
BUG反馈

**bk-iam-saas SaaS版本/bk-iam后台版本(The versions used):**
最新版本仍旧存在该问题

**异常描述:**
权限中心页面，在获取超级管理员成员时，前端组件调用的fs_list_users接口拉取数据失败

**相关截图:**
![image](https://github.com/TencentBlueKing/bk-iam-saas/assets/90179140/10ad64cc-486e-4ffa-910a-95336b2f8a48)

![image](https://github.com/TencentBlueKing/bk-iam-saas/assets/90179140/53080c49-2a28-4006-9c47-708efe7bb6c7)

直接https形式调用用户管理接口，返回正常：
![image](https://github.com/TencentBlueKing/bk-iam-saas/assets/90179140/ee33a7e6-e4bb-43ce-b65f-9ba90f477e9f)

**临时处理:**
由于BK_COMPONENT_API_URL 变量前后台共用，无法直接修改=》
1、前端定义一个新的变量 BK_FRONTEND_COMPONENT_API_URL +  bkFrontendComponentApiUrl 
BK_FRONTEND_COMPONENT_API_URL , 然后 引用bkiam-saas helm包 value.yaml  的 .Values.bkFrontendComponentApiUrl （变量新增）。

templates/_helpers.tpl
```
- name: BK_COMPONENT_API_URL
  value: {{ .Values.bkComponentApiUrl }}
- name: BK_FRONTEND_COMPONENT_API_URL
  value: {{ .Values.bkFrontendComponentApiUrl }}
```

2、替换BK_COMPONENT_API_URL 为BK_FRONTEND_COMPONENT_API_URL
sed -i.bak "s|{{ BK_COMPONENT_API_URL }}|{{ BK_FRONTEND_COMPONENT_API_URL }}|g" resources/templates/index.html
在如下文件新增 BK_FRONTEND_COMPONENT_API_URL 变量
config/ce.py
config/v2.py

**Comment by zhu327** [comment]
增加环境变量用于配置内部使用的组件curl
https://github.com/TencentBlueKing/bk-iam-saas/pull/2431/files#diff-674b86c100784413d7ecef61d3c75c812be0ba7f1d50c7f9a7a6e79c73789692L368

在helm chart上通过extraEnvVars配置, 版本需要晚点再出

**Comment by zhu327** [comment]
v1.10.19版本解决, 按以上备注通过helm注入环境变量实现
