### ISSUE TITLE
【性能问题】批量资源拓扑授权/api/c/compapi/v2/iam/authorization/batch_path/ 在并发场景下调用异常

### ISSUE THREAD

**Issue by Canway-shiisa** [TencentBlueKing/bk-iam-saas#2390]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):
BUG反馈

**bk-iam-saas SaaS版本/bk-iam后台版本(The versions used):**
v1.10.11

**异常描述:**
自研的saas存在批量创建资源的场景，底层并发调用了权限中心的 batch_path接口，调用的情况大概是每次循环发送300个请求（实际使用可能并发数量会更高），出现下列报错：
![image](https://github.com/TencentBlueKing/bk-iam-saas/assets/90179140/d909567b-5812-42d9-a315-f235ed431b40)

**期望效果:**
性能进行优化 支持多并发场景

**Comment by zhu327** [comment]
1306201 不是权限中心的code, 可以问下esb
