### ISSUE TITLE
我的权限增加人员模板权限

### ISSUE THREAD

**Issue by bohanchai** [TencentBlueKing/bk-iam-saas#2427]
我的权限无法显示通过人员模板加入的用户组

**Comment by bohanchai** [comment]
<img width="1791" alt="1" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/0e027d88-5b7e-41ff-9f65-42e4689e0230">
<img width="1791" alt="2" src="https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/97c873e3-578d-4ead-9a03-ffcded6baeed">

**Comment by lhzzforever** [comment]
Done
