### ISSUE TITLE
对接方删除资源实例无法实时同步到权限中心，导致分级管理员授权范围异常

### ISSUE THREAD

**Issue by Canway-shiisa** [TencentBlueKing/bk-iam-saas#2436]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):
BUG反馈

**bk-iam-saas SaaS版本/bk-iam后台版本(The versions used):**
最新版仍旧存在该问题

**问题描述:**
对接方删除某一些资源实例，权限中心无法实时进行更新，导致分级管理员的相关授权还是会拉取到已删除的资源实例，导致授权后保存会报相关异常（name-id校验不通过）

**期望是什么(What you expected to happen):**
权限中心能实时同步到对接方的资源实例，更新分管授权范围及删除相关的策略

**Comment by zhu327** [comment]
新版无该问题
