### ISSUE TITLE
[方案] RBAC

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-iam-saas#245]
## RBAC role as subject_type

- subject: `type=role, id=uniq_role_id`
- 拿这个 Subject 配置权限
- 此时, 一旦建立, `user - role`映射关系, 理论上鉴权的时候, 跟group机制一样, 可以继承subject(type=role)的权限
- 此时, role是system维度的
- 存哪里? 权限中心存, 会有限制(比如一个系统只能有 1000个角色, 一个人只能属于 10 个角色等等), 接入系统存, 自行处理(没有限制)
- 目前用户组带来的继承爆炸, 原因还是: 用户组关系存在了权限中心

------

存接入系统, 鉴权自行传角色

```
subject: {
    type : "user"
    id : "tom1"
    attribute : [
        role: [projeect1_admin, project1_owner]
    ]
}
```

------

- 一个人 - 一个系统 - 角色数量也不能过多; 例如 1000 个, 搞成 100 个呢? 
- 例如, 蓝盾一个人有 2000 个项目的管理员角色, 鉴权的时候, 理论上, 不能传 2000 个过来

------

## 需要再细化下限制

- 权限中心可以存, 有限制
- 接入系统可以自己存, 也有限制 (角色的权限在权限中心)

权限中心帮助存, 但是需要有个附加的字段(key/value), 鉴权的时候必须要传(用于第一时间缩小范围)

- key=project
- value=projectID
- 鉴权: `subject.type = user, subject.id = tom, subject.role_scope=project, subject.role_scope_id=projectID`

问题: 过于定制了?

**Comment by Xmandon** [comment]
关联issue https://github.com/TencentBlueKing/bk-iam-saas/issues/17

**Comment by wklken** [comment]
是否能整合django本身的 rbac

**Comment by zhu327** [comment]
- 立足于ABAC的基础上来实现RBAC, 不能一传统的RBAC的模式来套现在的模型, 所以需要有一个突破性的方案
- 如果role - subject的关系保存在权限中心这边, 实际效果跟group现在看起来也没什么区别, 方案开始就应该打破这个形式

**Comment by zhu327** [comment]
openApi也需要完整的支持RBAC, 支持二次开发接入

**Comment by zhu327** [comment]
[toc]

### 1. 现有问题

1. 蓝盾/BCS都需要以资源的维度来创建角色包含一系列的操作权限，这些资源本身都有上下级的层级关系，不同的层级的资源需要创建不同的角色

   - 蓝盾：项目 - 流水线/项目 - 流水线组 - 流水线
   - BCS：项目 - 集群 - 命名空间

   这就会导致权限中心现有的ABAC模型中通过操作来索引策略的方式不能精确的命中操作的索引，进而使得查询得到的策略过多，策略表达式计算量过大，导致鉴权性能下降

2. RBAC在模型上更加注重管理员对于角色的管控，需要理清权限中心要实现的RBAC到底是由接入系统自行来分配角色（比如蓝盾）还是由管理员在权限中心来创建角色，不同的角色创建方式，面向的用户不同，会影响到RBAC的实现设计，产品选项：

   - RBAC只提供API，role由接入系统自行管理，在权限中心上只能看不能管理
   - RBAC只在权限中心内管理，接入系统不能管理role的信息
   - RBAC可以同时在权限中心或者接入系统上做管理 （**最复杂**）

### 2. 方案

#### 2.1 ABAC的扩展实现RBAC

##### 2.1.1 ABAC示例

策略示例：

```json
{
  "subject": {
    "attrs": {
      "role": "1"
    }
  },
  "actions": ["execute"],
  "resources": {
    "type": "pipeline",
    "attrs": {
      "role": 1
    }
  }
}
```

在示例中，只要subject有角色1的标签，并且资源实例也有角色1的标签，则subject拥有execute的权限

从ABAC的角度来看，subject/action/resource都可以配置不同的属性，再基于策略中属性的匹配表达式判断用户数据是否满足策略，基于subject/action/resource都可以配属性的特点，下面分析基于属性的来实现RBAC的可行性

##### 2.1.2 属性

###### 用户的属性

如果把角色/Role作为一种属性/tag附加用户上，那么每一种Role对于用来说都只是一个标记，新建用户 - 属性关系表：

```json
{
  "subject_type": "user",
  "subject_id": "id",
  "attr_type": "role",
  "attr_id": "role_id"
}
```

在角色中增加用户时，需要在以上关系表中增加一条数据，此关系可以保存在权限中心，也可以保存在接入系统

如果保存在接入系统中，在权限中心这边就不能管理角色的用户成员，因为权限中心的成员变更没法直接通知到接入系统，导致鉴权时带入错误的role属性（可以考虑通过回调来实现，引入了对接入系统的依赖）

`实现分析`

1. 关系表保存在接入系统中
	- 鉴权时需要接入系统指定用户的角色身份，用户的角色身份可能有很多（蓝盾场景中，用户同时在项目，流水线的多个角色中），需要提前查询用户的角色身份，增加接入系统鉴权的逻辑负担
2. 关系表保存在权限中心
   - 与现有逻辑中group的鉴权方式相同，需要遍历用户所有的role关系，查询所有role的action的表达式再计算，解决不了问题1

完全把role - user的关系放到接入系统管理，对于接入系统来说（比如蓝盾）其实权限中心就没有太大的作用了，还不如接入系统自行实现RBAC简单

结论：**用户的属性不作为备选**

###### 资源的属性

如果角色完全由接入系统自行管理并且不能在权限中心对角色的策略资源信息作修改，则接入系统在鉴权时知道资源是由哪个角色管理的，此时鉴权的信息中接入系统可以给到role的信息

```json
{
	"system": "bk_devops",
	"subject": {
		"type": "user",
		"id": "admin"
	},
	"action": {
		"id": "execute"
	},
	"resources": [{
		"system": "bk_devops",
		"type": "pipeline",
		"id": "ping",
		"attribute": {
			"role_id": ["1"]  // 角色ID
		}
	}]
}
```

如果角色本身的授权的资源范围在权限中心是可以变更的，此时接入系统不能感知到变更，所以也就不能在鉴权时给到资源对应的role属性值

`实现分析`

```json
// 策略例子
{
    "action":{
        "id":"execute"
    },
    "condition": {  // 条件表达式
         "field": "pipeline.role_id",
         "op": "eq",
         "value": ["1"]
    }
}
```

- 如果角色管理的资源范围是一个大的范围，通过这种方式能减少策略的表达式大小，但是实际上蓝盾/BCS的需求角色的资源实例都只有一个，这里的表达式换成资源实例的id是没有区别的
- 授权对象为用户，没有实际作用，相当于把role的权限配置拆分到每个成员用户的头上
- 如果授权对象为role，此时可以通过资源role_id属性来筛选出适合的role策略，然后通过user - role关系表来判定用户是否属于role的成员，但是这样会改变现有的鉴权逻辑，以及对于鉴权逻辑侵入导致职责模糊

结论：**资源的属性不作为备选**

###### 操作的属性

现有的操作是一个字符串，如果在授权时能对操作增加一个属性的维度，则在查询策略时可以提前过滤掉不必要的计算

```json
{
  "action": {
    "id": "execute",
    "attribuete": {
      "role_id": "1",  // 角色属性
      "project": "blueking"  // 资源范围的属性
    }
  }
}
```

- 如果属性是role_id, 鉴权时需要在action_id中附加role_id
  - 意味着接入系统需要管理role - action之间的关系，并且关系不能在权限中心管理，**不适合**

- 如果属性是资源类型，意味着role必须绑定在资源类型上

`实现分析`

- 在鉴权逻辑中需要新增操作的筛选逻辑，增加查询的复杂度
- 如果授权在权限中心上实现，授权时需要选择操作的属性，难以理解

在操作上增加scope范围属性，在subject_pk to policies 的查询过程中可以筛选掉一部分策略，减少计算量，但是会增加查询筛选的复杂度，并且没有做到提前筛选subject_pk，具体的实现性能需要压测来评估

结论：**操作的属性暂时保留**

#### 2.2 独立RBAC

回归到现有的原始需求，蓝盾/BCS这类系统的RBAC需求都是在单一资源实例上创建角色，以现有的ABAC模型最大的问题是不能通过资源实例快速定位到有权限的策略，这里抛开ABAC设计一种对资源实例做索引的权限策略

##### 2.2.1 鉴权

每个资源实例在创建role时创建一条数据，最终策略的总数 = 资源实例数量 * 平均每个资源实例的role数量

```json
{
    "system_id": "bk_ci", // 索引字段
    "type": "project",  // 索引字段
    "id": "1",  // 索引字段
    "role": {  // role 字段在数据库中为json表达式
        "id": "",
        "members": ["admin", "tianyizhu"],
        "actions": ["edit", "delete", "create"]
    }
}
```

蓝盾在进行流水线鉴权时，需要传入上级资源实例：

```json
{
    "subject": {
        "type": "user",
        "id": "admin"
    },
    "action": {
        "id": "edit"
    },
    "resources": [
        {
            "type": "project",
            "id": "id"
        },
        {
            "type": "pipeline",
            "id": "id"
        }
    ]
}
```

鉴权时分别查询project/pipeline资源实例的策略，遍历计算role的表达式信息中是否包含鉴权的操作，以及成员中是否有被鉴权的用户

预期每个资源实例能创建的role数不超过50个，有多级资源类型5级的情况下，查询出来的策略数量为250，遍历计算最差性能是可控的

如果资源实例有多个分叉的上级，全部放到resource中鉴权也没问题

问题：

- 不关联资源类型的操作，比如创建项目怎么处理

##### 2.2.2 授权

页面上需要展示角色的相关信息，包括资源/操作/成员，需要在saas保存额外的role信息用于展示

可以提供api到接入系统创建角色，管理角色相关的成员，操作信息，提供api给接入系统查询资源实例的

权限中心saas也可以做角色相关信息的管理，独立功能，需要重新设计，基于资源实例的角色

问题：

- 接入系统是否会有不依据资源实例查询角色列表的需求，该如何实现

该方案打破了现有的产品/鉴权逻辑，对用户来说是另一套使用逻辑，对于接入系统来说，使用独立的角色管理api，鉴权api，也会提升新的接入系统的理解成本

**Comment by wklken** [comment]
另外, abac的示例

```json
{
  "subject": {
    "attrs": {
      "role": "1"
    }
  },
  "actions": ["execute"],
  "resources": {
    "type": "pipeline",
    "attrs": {
      "role": 1
    }
  }
}
```

应该是: 

```json
{
  "subject": {
    "attrs": {
      "role": "1"
    }
  },
  "actions": ["execute"],
  "resources": {
    "type": "pipeline",
    "id": "123"
  }
}
```

逻辑表达式: `subject.role = 1 AND action.id="execute" and resource.type=pipeline and resource.id="123"`

**Comment by zhu327** [comment]
RBAC能确定的点:

1. role一定是接入系统范围内, 不存在全局的role
2. RBAC把role绑定在资源实例
3. role信息要单独存放, role与资源建立关联关系, 1对多


---

新的方案的问题:

1. 项目上的流水线任意的执行权限, 需要项目/流水线多次鉴权
    - 项目上面绑定流水线的执行操作会有疑惑, 因为流水线执行的操作关联的资源类型是流水线
    - 考虑下如果有范围的鉴权还是在ABAC, RBAC这里还是绑定单一的资源绑定
2. 操作如果没有关联资源类型, 导致policy查询的role_id数量级不可控
3. 角色模板(角色名称, 操作列表), 抽象出一些固定的数据, 实例化模板是传入动态参数, 创建role对象

**Comment by zhu327** [comment]
通用RBAC表结构

#### 1. role表

- pk
- system_id

#### 2. role_subject表

- pk
- role_pk
- subject_pk

#### 3. action表

- pk
- id
- name
- type  // 是否关联资源类型

#### 4. action_resource_type

- pk
- action_system_id
- action_id
- resource_type_system_id
- resource_type_id

#### 5. policy

- pk
- role_pk
- action_ids
- resource_type_system_id
- resource_type_id
- resource_id

---

鉴权逻辑:

鉴权数据:

```json
{
	"system": "demo",
	"subject": {
		"type": "user",
		"id": "tom",
	},
	"action": {
		"id": "access_developer_center"
	},
	"resource": {
        "type": "resource",
        "id": "id"
    }
}
```

1. 使用system/resource_type/resource_id, 在policy表中查询role_pk与action_ids
2. 使用鉴权数据的action_id, 筛选出有对应操作权限的role_pk
3. 使用第二步中的role_pk与subject_pk在role_subject表中判断是否有数据, 如果有则pass, 没有则无权限

**Comment by wklken** [comment]
讨论点:

上面的 `policy.action_ids` 挪到 `role.action_ids`?
- role 的操作大部分是确定的, 没有差异
- role 一对多的情况下, 能节约存储
- 是否有其他问题? 

-----


不关联资源类型: 独立一张表存储, 命中即有权限; 处理逻辑, 关联资源实例, 走上面的, 不关联, 走这张表

```
role_subjet_pk
action_id

# 或者冗余存储
role_pk
subject_pk
action_id
```

**Comment by wklken** [comment]
需评估, 蓝盾的场景往里放, 每个表的数量级

**Comment by wklken** [comment]
场景描述:
1. 新建一个角色
2. 角色可以拥有 100 条流水线权限
3. 角色可以创建流水线权限
4. 角色可以加上另一条流水线
5. 角色可以加 创建项目权限
6. 可以给所有角色同时加上一个操作权限

**Comment by wklken** [comment]
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/2002216/160069078-b4daf552-4423-4884-9d37-e79e9dbd0b02.png">

**Comment by zhu327** [comment]
1. action_ids 放 role 表需要额外的一次查询
2. 放到 role_subject 话会有冗余, 并且不利于鉴权逻辑的筛选, 会有重复计算?

**Comment by zhu327** [comment]
数量级
流水线: 100万
每个流水线角色: 5个
每个流水线角色操作: 10个
项目: 5万
每个项目角色: 10个
每个项目角色操作: 10个

---

按以上数量级反推各表的数量级:

1. role表: 550万
2. role_subject表: 550万 * 10 = 5500万   # 每个角色成员10个
3. action表: 不多, 100以内
4. policy表: 550万  # 每个role一条

**Comment by zhu327** [comment]
![image](https://user-images.githubusercontent.com/873883/160339079-4bd9834c-f8e8-4a94-9313-2ef453c8d400.png)

**Comment by zhu327** [comment]
casbin

https://github.com/casbin/casbin/blob/master/examples/rbac_model.conf

```
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act
```

- policy 中的 sub 可以是 user, 也可以是group, group表示role
- matchers 中 g 的意思是使用内置的g函数匹配request中的sub与policy中的sub(user/group)是否匹配

---

蓝盾数据量:

- group: 500W
- user - group: 5000W
- policy: 500W * 5 = 2500W (每个group操作5个)

---

casbin中策略可理解subject - object - action大平的存在内存中

**Comment by wklken** [comment]
https://github.com/casbin/casbin/blob/master/examples/rbac_policy.csv

```
p, alice, data1, read
p, bob, data2, write
p, data2_admin, data2, read
p, data2_admin, data2, write
g, alice, data2_admin
```

**Comment by wklken** [comment]
问题: 一个role会有多少用户? 每个用户配置多少操作?

1. 如果关联实例的, 把action_ids冗余到策略表
2. 不关联实例的, action_ids冗余到subject_role表

**Comment by wklken** [comment]
明天我们讨论下 V0 的实现是否可以借鉴到上周讨论的纯 RBAC 的设计

V0 提前算 Hash 放 Redis , 直接通过key是否存在鉴权

**Comment by zhu327** [comment]
![image](https://user-images.githubusercontent.com/873883/160806235-a277c4c6-4334-457d-8a16-de3a816498b2.png)


会议纪要：

1. Role 作为一种Subject，若需要资源范围授权，则使用ABAC，若需要资源实例授权，则使用RBAC

2. SubjectRoleAction 表，单独处理 与资源实例无关的操作权限， 字段：subject_pk + role_pk +action_pk + system_id

3. SubjectRole 只存 role_pk + subject_pk + system_id

4. ResourcePolicy 增加 action_ids 字段作为初筛

5. 权限模型增加 RoleAction表 用于限制 授权时Role的可授权Action选择

6. ResourcePolicy 表将 ResourceTypeID和ResourceID 合并为一个字段 unique(ResourceTypeID:ResourceID)

----------------------

目前方案只支持节点范围，不支持路径范围，即不支持精确的前缀匹配

另外一种支持精确的前缀匹配思路 => ResourcePolicy.action_ids字段，可以是存储附带前缀信息 action1.resource_prefix

**Comment by wklken** [comment]
related #17

**Comment by wklken** [comment]
https://github.com/TencentBlueKing/bk-iam-saas/issues/17#issuecomment-1092389519

把用户组, 当成角色, 那么目前涉及的 独立的RBAC方案, 相当于是将用户组切分一个维度出来: 实例级别的用户组(支持配置ignore_path的实例视图)

此时, 用户组需要的形态变更: 全局继承(存在 100个限制), 变成几类:

全局(现有的, 依旧存在 100 个限制)
系统级别的(受限, 只能配置本系统权限, 可以再给 100个配额)
实例级别的(暂时不限制, 只能配置本系统并且关联某些实例)
实现上, 角色模型套用现在的 用户组; 但是底层可能分表存;

这样做对目前产品形态影响不大; 但是需要考虑这类组的各种限制

此时, 需要对应系统鉴权时传递资源实例, 才能命中这部分权限数据

-------------
此时, 产品形态还是只有`用户组`, 只是多维度的用户组

而底层实现, 这个维度的单独处理
<img width="1206" alt="image" src="https://user-images.githubusercontent.com/2002216/162355325-b0247f61-1958-46d6-b216-224846216626.png">

**Comment by wklken** [comment]
SubjectRole, 可以通过bitmap优化, 降低 2 个数量级

> 表大小 = RBAC系统数 * 总用户数 * 20% 

存储字段: RolePKs, SubjectPK, SystemID
其中RolePKs是一个bitmap, https://github.com/RoaringBitmap/roaring

------

这样的问题, 不好查询: 某个角色的用户列表

------

所以, 这个优化只能用在鉴权时? 用户缓存了自己的所有角色列表? (**重要: 避免大表高频率查询**)

**Comment by wklken** [comment]
## 问题: 表大小再上一个数量级

- Role/ResourcePolicy 千万级
- SubjectRole 亿级

此时是扛不住的, 快到达 1000W 的时候就需要考虑分表/分库

那么, 是否提前做一些处理?

1. 普通系统接入, 都有限制, 接入前评估 => 共享表/库
2. 大的系统接入, 例如cmdb/bk_ci/bcs等, => 独立的表/库?
3. 未来可以基于system_id/action_pk等等进一步分表

数据存储独立后, 怎么跟主体的 ABAC 一起工作?

**Comment by wklken** [comment]
## 表字段

指向很明确, 所以所有xxSystemID都改成 system_id

**Comment by wklken** [comment]
db proxy方案调研

**Comment by wklken** [comment]
## 问题: 如何表示更大范围的权限

资源类型链路: 项目 -> 流水线

目前可以实现: 某个项目下的所有流水线的编辑权限

但是, 如果需要实现: 所有项目的查看权限? 类似全业务管理员 (如果全部实例化, 代价太大)

是否有其他路子?

**Comment by wklken** [comment]
## 问题: k8s RBAC

https://jimmysong.io/kubernetes-handbook/concepts/rbac.html

role binding的时候指定了namespace, 此时是否适用?


```yaml
# 以下角色绑定允许用户 "dave" 读取 "development" 命名空间中的 secret。
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: read-secrets
  namespace: development # 这里表明仅授权读取 "development" 命名空间中的资源。
subjects:
- kind: User
  name: dave
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: secret-reader
```

而cluster role binding对所有命名空间生效

```yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: read-secrets-global
subjects:
- kind: Group
  name: manager
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
```

**Comment by wklken** [comment]
## 问题: RBAC

这套方案只实现了, 最基本的 RBAC 模型(RBAC0)

https://github.com/casbin/casbin/blob/master/examples/rbac_model.conf

无法支持:
1. 角色继承 (RBAC1)
2. RBAC2/RBAC3 理论上在配置权限时根据需求限制即可

## 问题: 一个人可以属于多少角色? 不限制会不会有问题

最早数平的需求, 从构建系统的层面, 应该先限制? 防御性

未来超过了有诉求再加白名单?

**Comment by wklken** [comment]
Reopen, 跟进项

**Comment by wklken** [comment]
- 不在权限中心展示bk_ci的内容/交互等
- bk_ci专属的组(标签等等)
- 开发者/管理者/使用者, 不需要感知, 以目前一致的接入体验/使用体验在使用权限中心

---------------------

问题: 现有的 abac 如何才能支持到? 整体体验一致

1. 组该怎么处理? 怎么做限制, 只能配置bk_ci的东西, 并且, 权限配置的体验一致
2. 组的规模会很大, 百万级
3. 怎么快速从资源, 反向检索到组, 然后查找 `用户-组`之间的关系?
