### ISSUE TITLE
新建用户组编辑添加操作后不显示

### ISSUE THREAD

**Issue by bohanchai** [TencentBlueKing/bk-iam-saas#2461]
![企业微信截图_605a45a2-1a36-4232-a24b-fef36e4bbd54](https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/ce515b68-7a08-43ef-81f9-4b2e31cf6af3)
![企业微信截图_28dced07-52eb-48f5-a6fd-b31130f4b835](https://github.com/TencentBlueKing/bk-iam-saas/assets/142869123/79dddc93-1772-4fbd-be3d-ce45446ee549)
复现过程：新建用户组——添加权限——选择模板和自定义后确认——再去编辑已选的权限，取消自定义权限——无法显示操作模板

**Comment by lhzzforever** [comment]
Done
