### ISSUE TITLE
【前端】资源权限管理点击重置后 搜索功能异常

### ISSUE THREAD

**Issue by Canway-shiisa** [TencentBlueKing/bk-iam-saas#2560]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):
BUG反馈

**bk-iam-saas SaaS版本/bk-iam后台版本(The versions used):**
最新版仍旧存在该问题

**异常描述:**
在权限中心-资源权限管理 首次点击进行搜索（可以正常返回数据）后，点击重置按钮（首次的搜索结果没有清空），重新选择搜索条件后进行搜索，仍旧显示上一次搜索的结果数据，无法正常返回正确数据

**异常相关截图:**
1. 异常复现截图
![资源权限管理异常](https://github.com/TencentBlueKing/bk-iam-saas/assets/90179140/b92fb9df-7add-48bc-8c2c-07d3dec87508)

2. 输入相同的搜索条件，不在重置后进行搜索的话可以返回正常结果：
![image](https://github.com/TencentBlueKing/bk-iam-saas/assets/90179140/06ff8567-086e-4481-acec-008e1d80322c)

**预期效果:**
资源权限管理，搜索后进行重置，应该清空掉搜索条件+原搜索结果；
重新输入搜索条件后要能够实现正常搜索

**备注(Anything else we need to know):**
初步排查结论：重置之后前端没有重新调用接口到后台拿数据

**Comment by lhzzforever** [comment]
Done
