### ISSUE TITLE
容器化版本无法正常切换中英文版本

### ISSUE THREAD

**Issue by Canway-shiisa** [TencentBlueKing/bk-iam-saas#2567]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):
BUG反馈

**bk-iam-saas SaaS版本/bk-iam后台版本(The versions used):**
所有容器化版本的权限中心都存在该问题

**问题描述:**
容器化版本中的权限中心无法正常切换中英文，其他saas可以

**问题截图:**
![切换中英文异常](https://github.com/TencentBlueKing/bk-iam-saas/assets/90179140/f90694e1-8a36-4ce6-b791-929a1d513a52)

**预期效果:**
不管是否为容器化版本，都需要可以正常切换中英文

**Comment by lhzzforever** [comment]
BJ_DOMAINh环境变量地址有问题

**Comment by Canway-shiisa** [comment]
需要提供配置文档
