### ISSUE TITLE
个人工作台-我的申请列表拉到底部会报错

### ISSUE THREAD

**Issue by Canway-shiisa** [TencentBlueKing/bk-iam-saas#2568]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):
BUG反馈

**bk-iam-saas SaaS版本/bk-iam后台版本(The versions used):**
最新版本仍旧存在该问题

**问题描述:**
在 我的申请 栏 滑动滚动条到底部，会出现系统异常的报错

**问题截图:**
![我的申请列表异常](https://github.com/TencentBlueKing/bk-iam-saas/assets/90179140/c177fe10-3952-40cd-9253-78518a08e901)

**备注:**
慢慢拉到底部，可以正常；当拉滚动条的速度比较快，就会出现多次调用接口的情况：
1. 
![image](https://github.com/TencentBlueKing/bk-iam-saas/assets/90179140/4926d739-27fc-43ec-8e13-5ebddf9a9d7f)
2. 
![image](https://github.com/TencentBlueKing/bk-iam-saas/assets/90179140/1c2192f5-597c-410d-b233-04e1280fb2a3)
3. 
![image](https://github.com/TencentBlueKing/bk-iam-saas/assets/90179140/bee6fa8d-66f8-4c6d-b0d7-44bc4116aa6b)
![image](https://github.com/TencentBlueKing/bk-iam-saas/assets/90179140/cbe06999-dd2f-4513-8777-a46da47ba868)

**Comment by lhzzforever** [comment]
无法复现

**Comment by Canway-shiisa** [comment]
Saas V1.10.24修复
