### ISSUE TITLE
[SaaS] 协作开发: 管理后台一期-白名单-管理类 API

### ISSUE THREAD

**Issue by zhu327** [TencentBlueKing/bk-iam-saas#260]
相关model

https://github.com/TencentBlueKing/bk-iam-saas/blob/master/saas/backend/api/management/models.py#L19

**Comment by zhu327** [comment]
- api 选择, 可以已有中文的对应关系, 可以返回接口文档的链接, 通过枚举来返回
- system_id 通过系统列表获取
- CURD

**Comment by Canway-shiisa** [comment]
排期：
1.20211222 完成开发接口文档，根据文档review结果进行调整，确定最后方案
2.20211224 提交第一版PR

**Comment by Canway-shiisa** [comment]
##### 系统接口

复用/api/v1/systems/ 



##### API接口

###### 请求地址

/api/v1/open/management/

###### 请求方法

GET

###### 返回示例

```json
{
  "data": [
      {	  "id":"grade_manage_create",
          "name":"新建分级管理员"
      },
      {
          "id":"group_list",
          "name":"获取用户组列表"
      }
  ],
  "result": true,
  "code": 0,
  "message": "OK"
}
```



###### 请求方法

POST

###### 请求示例

```json
{
  "system_id": "bk_paas",
  "api": "group_update"
}
```

###### 请求参数说明

| key       | 说明    | 类型   | 是否必填 | 请求示例     |
| --------- | ------- | ------ | -------- | ------------ |
| system_id | 系统ID  | string | 是       | bk_paas      |
| api       | API名称 | string | 是       | group_update |

###### 返回示例

```json
{
  "result": true,
  "code": 0,
  "message": "OK"
}
```



###### 请求方法

DELETE

###### 请求示例

```json
{
  "system_id": "bk_paas",
  "api": "group_update"
}
```

###### 请求参数说明

| key       | 说明    | 类型   | 是否必填 | 请求示例     |
| --------- | ------- | ------ | -------- | ------------ |
| system_id | 系统ID  | string | 是       | bk_paas      |
| api       | API名称 | string | 是       | group_update |

###### 返回示例

```json
{
  "result": true,
  "code": 0,
  "message": "OK"
}
```

**Comment by zhu327** [comment]
## 模块处理

1. 以上api都不是应该在/api/v1/open下
2. 在apps下新增管理后台模块
3. 在管理后台下心中白名单模块, 白名单相关的api都放到这个模块下

## api的定义

1. 提供一个获取所有枚举值的api, GET接口, 获取api相关的枚举
2. DELETE接口直接使用主键删除

**Comment by Canway-shiisa** [comment]
#### 白名单-管理类API-接口文档

##### 系统接口

复用/api/v1/systems/ 



##### API接口

###### 请求地址

/api/v1/mgmt/management_api/

###### 请求方法

GET

###### 返回示例

```json
{
  "data": [
      {
          "api":"grade_manage_create",
          "name":"新建分级管理员"
      },
      {
          "api":"group_list",
          "name":"获取用户组列表"
      }
  ],
  "result": true,
  "code": 0,
  "message": "OK"
}
```



###### 返回参数说明

| key  | 说明              | 类型   | 请求示例            |
| ---- | ----------------- | ------ | ------------------- |
| api  | API名称           | string | grade_manage_create |
| name | API中文名称       | string | 新建分级管理员      |



###### 请求地址

/api/v1/mgmt/management_api/

###### 请求方法

POST

###### 请求示例

```json
{
  "system_id": "bk_paas",
  "api": "group_update"
}
```

###### 请求参数说明

| key       | 说明    | 类型   | 是否必填 | 请求示例     |
| --------- | ------- | ------ | -------- | ------------ |
| system_id | 系统ID  | string | 是       | bk_paas      |
| api       | API名称 | string | 是       | group_update |

###### 返回示例

```json
{
    "data": null,
    "result": true,
    "code": 0,
    "message": "OK"
}
```



###### 请求地址

/api/v1/mgmt/management_api/\<int:id\>

请求方法

DELETE



###### 请求参数说明

| key  | 说明              | 类型 | 是否必填 | 请求示例 |
| ---- | ----------------- | ---- | -------- | -------- |
| id   | 管理类API的记录ID | int  | 是       | 1        |



###### 返回示例

```json
{
    "data": null,
    "result": true,
    "code": 0,
    "message": "OK"
}
```

**Comment by Canway-shiisa** [comment]
排期：
1.20220107 提交第二版PR

**Comment by Canway-shiisa** [comment]
#### 白名单-管理类API-接口文档

##### 系统接口

复用/api/v1/systems/ 



##### API接口

###### 请求地址

/api/v1/mgmt/api/?api_type=management_api

###### 请求方法

GET

###### 请求参数

| key      | 说明    | 类型   | 请求示例       |
| -------- | ------- | ------ | -------------- |
| api_type | API类型 | string | management_api |



###### 返回示例

```json
{
    "data": [
        {
            "api": "grade_manager_create",
            "name": "新建分级管理员"
        },
        {
            "api": "grade_manager_update",
            "name": "更新分级管理员"
        },
        {
            "api": "grade_manager_member_list",
            "name": "获取分级管理员成员列表"
        },
        {
            "api": "grade_manager_member_add",
            "name": "添加分级管理员成员"
        },
        {
            "api": "grade_manager_member_delete",
            "name": "删除分级管理员成员"
        },
        {
            "api": "group_list",
            "name": "获取用户组列表"
        },
        {
            "api": "group_batch_create",
            "name": "批量创建用户组"
        },
        {
            "api": "group_update",
            "name": "更新用户组"
        },
        {
            "api": "group_delete",
            "name": "删除用户组"
        },
        {
            "api": "group_member_list",
            "name": "获取用户组成员列表"
        },
        {
            "api": "group_member_add",
            "name": "添加用户组成员"
        },
        {
            "api": "group_member_delete",
            "name": "删除用户组成员"
        },
        {
            "api": "group_policy_grant",
            "name": "授权用户组"
        },
        {
            "api": "user_role_list",
            "name": "获取用户加入的分级管理员列表"
        },
        {
            "api": "user_role_group_list",
            "name": "获取某个分级管理员下用户加入的用户组列表"
        },
        {
            "api": "group_application_create",
            "name": "创建用户组申请单"
        }
    ],
    "result": true,
    "code": 0,
    "message": "OK"
}{
  "data": [
      {
          "api":"grade_manage_create",
          "name":"新建分级管理员"
      },
      {
          "api":"group_list",
          "name":"获取用户组列表"
      }
  ],
  "result": true,
  "code": 0,
  "message": "OK"
}
```



###### 返回参数说明

| key  | 说明              | 类型   | 请求示例            |
| ---- | ----------------- | ------ | ------------------- |
| api  | API名称           | string | grade_manage_create |
| name | API中文名称       | string | 新建分级管理员      |



##### API白名单接口

###### 请求地址

/api/v1/mgmt/management_api/white_list/

###### 请求方法

GET


###### 返回示例

```json
{
  "data": [
      {		
          "id":1,
          "api":"grade_manage_create",
          "system_id":"bk_paas"
      },
      {
          "id":2,
          "api":"group_list",
          "name":"bk_sops"
      }
  ],
  "result": true,
  "code": 0,
  "message": "OK"
}
```
###### 返回参数说明

| key  | 说明              | 类型   | 请求示例            |
| ---- | ----------------- | ------ | ------------------- |
| id  | 白名单记录ID           | int | 1 |
| api  | API名称           | string | grade_manage_create |
| system_id | 系统ID | string | bk_paas |




###### 请求地址

/api/v1/mgmt/management_api/white_list/

###### 请求方法

POST

###### 请求示例

```json
{
  "system_id": "bk_paas",
  "api": "group_update"
}
```

###### 请求参数说明

| key       | 说明    | 类型   | 是否必填 | 请求示例     |
| --------- | ------- | ------ | -------- | ------------ |
| system_id | 系统ID  | string | 是       | bk_paas      |
| api       | API名称 | string | 是       | group_update |

###### 返回示例

```json
{
    "data": {},
    "result": true,
    "code": 0,
    "message": "OK"
}
```



###### 请求地址

/api/v1/mgmt/management_api/white_list/\<int:id\>/

请求方法

DELETE



###### 请求参数说明

| key  | 说明              | 类型 | 是否必填 | 请求示例 |
| ---- | ----------------- | ---- | -------- | -------- |
| id   | 管理类API的记录ID | int  | 是       | 1        |



###### 返回示例

```json
{
    "data": {},
    "result": true,
    "code": 0,
    "message": "OK"
}
```
