### ISSUE TITLE
[SaaS] 协作开发: 管理后台一期-白名单-超级管理类 API

### ISSUE THREAD

**Issue by zhu327** [TencentBlueKing/bk-iam-saas#261]
相关Model

https://github.com/TencentBlueKing/bk-iam-saas/blob/master/saas/backend/api/admin/models.py#L19

**Comment by zhu327** [comment]
- api 选择, 可以已有中文的对应关系, 可以返回接口文档的链接, 通过枚举来返回
- app_cod直接输入
- CURD

**Comment by Canway-shiisa** [comment]
排期：
1.20211222 完成接口文档编写，根据文档review结果进行调整，确定最后方案
2.20211228 提交第一版PR

**Comment by Canway-shiisa** [comment]
##### 系统接口

复用/api/v1/systems/ 



##### API接口

###### 请求地址

/api/v1/open/admin/

###### 请求方法

GET

###### 返回示例

```json
{
  "data": [
      {	  "id":"group_member_list",
          "name":"获取用户组成员列表"
      },
      {
          "id":"group_list",
          "name":"获取用户组列表"
      }
  ],
  "result": true,
  "code": 0,
  "message": "OK"
}
```



###### 请求方法

POST

###### 请求示例

```json
{
  "app_code": "c4d7cb62-6b59-49b9-a94e-fc937ba9a111",
  "api": "group_member_list"
}
```

###### 请求参数说明

| key      | 说明      | 类型   | 是否必填 | 请求示例                             |
| -------- | --------- | ------ | -------- | ------------------------------------ |
| app_code | 应用TOKEN | string | 是       | c4d7cb62-6b59-49b9-a94e-fc937ba9a111 |
| api      | API名称   | string | 是       | group_member_list                    |

###### 返回示例

```json
{
  "result": true,
  "code": 0,
  "message": "OK"
}
```



###### 请求方法

DELETE

###### 请求示例

```json
{
  "app_code": "c4d7cb62-6b59-49b9-a94e-fc937ba9a111",
  "api": "group_member_list"
}
```

###### 请求参数说明

| key       | 说明      | 类型   | 是否必填 | 请求示例                             |
| --------- | --------- | ------ | -------- | ------------------------------------ |
| system_id | 应用TOKEN | string | 是       | c4d7cb62-6b59-49b9-a94e-fc937ba9a111 |
| api       | API名称   | string | 是       | group_member_list                    |

###### 返回示例

```json
{
  "result": true,
  "code": 0,
  "message": "OK"
}
```

**Comment by Canway-shiisa** [comment]
排期：
1.20211222 完成接口文档编写，根据文档review结果进行调整，确定最后方案
2.20210105 提交第一版PR
