### ISSUE TITLE
[SaaS] 协作开发: 管理后台一期-白名单-授权类 API

### ISSUE THREAD

**Issue by zhu327** [TencentBlueKing/bk-iam-saas#262]
相关Model

https://github.com/TencentBlueKing/bk-iam-saas/blob/master/saas/backend/api/authorization/models.py#L19

**Comment by zhu327** [comment]
1. 系统列表 已有
2. 操作列表 已有
3. 资源类型列表 -- 新增
4. 白名单列表, 按系统筛选, 系统名称, 操作名称, 资源类型名称, 可以与前端商量名称由前端填充
5. api CURD

**Comment by Canway-shiisa** [comment]
排期：
1.20211227 完成接口文档编写，根据文档review结果进行调整，确定最后方案
2.20211231 提交第一版PR

**Comment by Canway-shiisa** [comment]
#### 白名单-超级管理类API-开发方案

##### 系统接口

复用/api/v1/systems/ 

##### 操作接口

复用/api/v1/actions/?system_id=bk_paas



##### 资源类型列表接口【新增】

###### 请求地址

/api/v1/systems/resource_types/?system_id=bk_nonode



###### 请求方法

GET

###### 请求参数

| key       | 说明   | 类型   | 请求示例  |
| --------- | ------ | ------ | --------- |
| system_id | 系统ID | string | bk_nocode |

###### 返回示例

```json
{
    "data": [
        {
            "id": "project",
            "name": "应用"
        },
        {
            "id": "page",
            "name": "页面"
        },
        {
            "id": "action",
            "name": "操作"
        }
    ],
    "result": true,
    "code": 0,
    "message": "OK"
}
```



##### API接口

###### 请求地址

/api/v1/mgmt/white_list/apis/?api_type=authorization_api

###### 请求方法

GET

###### 请求参数

| key      | 说明    | 类型   | 请求示例          |
| -------- | ------- | ------ | ----------------- |
| api_type | API类型 | string | authorization_api |



###### 返回示例

```json
{
    "data": [
        {
            "api": "authorization_instance",
            "name": "实例授权"
        },
        {
            "api": "creator_authorization_instance",
            "name": "新建关联实例授权"
        }
    ],
    "result": true,
    "code": 0,
    "message": "OK"
}
```





##### API白名单接口

###### 请求地址

/api/v1/mgmt/white_list/authorization_apis/

###### 请求方法

GET

###### 返回示例

```json
{
    "data": {
        "count": 3,
        "results": [
            {
                "id": 73,
                "api_msg": {
                    "api": "authorization_instance",
                    "name": "实例授权"
                },
                "system": {
                    "id": "bk_cmdb",
                    "name": "配置平台"
                },
                "object_id": "starts_with:delete_comobj"
            },
            {
                "id": 72,
                "api_msg": {
                    "api": "authorization_instance",
                    "name": "实例授权"
                },
                "system": {
                    "id": "bk_cmdb",
                    "name": "配置平台"
                },
                "object_id": "starts_with:edit_comobj"
            },
            {
                "id": 71,
                "api_msg": {
                    "api": "authorization_instance",
                    "name": "实例授权"
                },
                "system": {
                    "id": "bk_cmdb",
                    "name": "配置平台"
                },
                "object_id": "starts_with:create_comobj"
            }
            
        ]
    },
    "result": true,
    "code": 0,
    "message": "OK"
}
```



###### 返回参数说明

| key       | 说明         | 类型 | 请求示例                                                     |
| --------- | ------------ | ---- | ------------------------------------------------------------ |
| id        | 白名单记录ID | int  | 1                                                            |
| api_msg   | API信息      | json | {<br/>                    "api": "authorization_instance",<br/>                    "name": "实例授权"<br/>                } |
| system    | 系统信息     | json | {<br/>                    "id": "bk_cmdb",<br/>                    "name": "配置平台"<br/>                } |
| object_id | 资源类型ID   | str  | starts_with:delete_comobj                                    |



###### 请求地址

/api/v1/mgmt/white_list/authorization_apis/

###### 请求方法

POST

###### 请求示例

```json
{
  "system_id": "bk_paas",
  "api": "creator_authorization_instance",
  "object_id":"app"
}
```

###### 

###### 请求参数说明

| key       | 说明       | 类型   | 是否必填 | 请求示例                       |
| --------- | ---------- | ------ | -------- | ------------------------------ |
| system_id | 系统ID     | string | 是       | bk_paas                        |
| api       | API        | string | 是       | creator_authorization_instance |
| object_id | 资源类型ID | string | 是       | app                            |



###### 返回示例

```json
{
    "data": {},
    "result": true,
    "code": 0,
    "message": "OK"
}
```



###### 请求地址

/api/v1/mgmt/white_list/authorization_apis/\<int:id\>/



请求方法

DELETE



###### 请求参数说明

| key  | 说明                    | 类型 | 是否必填 | 请求示例 |
| ---- | ----------------------- | ---- | -------- | -------- |
| id   | 授权类API的白名单记录ID | int  | 是       | 1        |



###### 返回示例

```json
{
    "data": {},
    "result": true,
    "code": 0,
    "message": "OK"
}
```
