### ISSUE TITLE
[SaaS]管理员身份下无权限跳转失败问题

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#264]
当用户在权限中心切换到管理员身份下，然后在SaaS侧下点击无权限跳转，跳转不会自动切换到普通用户身份下。

![image](https://user-images.githubusercontent.com/19284021/137082797-fcb82995-b3bf-4e3b-9003-00dc03a7a93a.png)

![image](https://user-images.githubusercontent.com/19284021/137082741-293af935-bcbc-4cc6-8022-6695953e61f8.png)

**Comment by huangpeng0428** [comment]
done
