### ISSUE TITLE
【前端】【优化】管理空间详情页链接直接访问会重定向到管理空间列表页

### ISSUE THREAD

**Issue by Canway-shiisa** [TencentBlueKing/bk-iam-saas#2665]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):
优化类需求

**bk-iam-saas SaaS版本/bk-iam后台版本(The versions used):**
最新版本仍旧存在该问题

**发生了什么(What happened):**
管理空间详情页链接直接访问会重定向到管理空间列表页（但！管理空间编辑页是可以直接访问的）

**期望是什么(What you expected to happen):**
目前存在一些上层saas进行开发的时候需要能直接访问管理空间详情页

**Comment by Xmandon** [comment]
前端支持，待验证
