### ISSUE TITLE
【前端】删除超级管理员成员后成功的弹窗无法自行关闭

### ISSUE THREAD

**Issue by Canway-shiisa** [TencentBlueKing/bk-iam-saas#2673]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):
BUG反馈

**bk-iam-saas SaaS版本/bk-iam后台版本(The versions used):**
最新版仍旧存在该问题

**问题描述:**
![删除超管成员异常](https://github.com/TencentBlueKing/bk-iam-saas/assets/90179140/c287f1af-e034-4134-ac5c-4909c9e5633d)

**期望是什么(What you expected to happen):**
删除成功后的弹窗需要可以自行关闭

**Comment by lhzzforever** [comment]
Done
