### ISSUE TITLE
【前端】模板关联用户组页面下拉到底部后翻页按钮显示异常

### ISSUE THREAD

**Issue by Canway-shiisa** [TencentBlueKing/bk-iam-saas#2676]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):
BUG反馈

**bk-iam-saas SaaS版本/bk-iam后台版本(The versions used):**
最新版仍旧存在该问题（saas 1.10.27）

**问题描述:**
查看模板关联的用户组，当用户组数量较多时，页面展示存在问题，无法看到翻页按钮，导致无法正常翻页查看

**问题相关截图:**

**Comment by lhzzforever** [comment]
Done
