### ISSUE TITLE
已关联用户组的人员模板在批量删除的时候可以成功被删除

### ISSUE THREAD

**Issue by Canway-shiisa** [TencentBlueKing/bk-iam-saas#2682]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):
BUG反馈

**bk-iam-saas SaaS版本/bk-iam后台版本(The versions used):**
当前最新版本仍旧存在该问题（saasV1.10.27）

**问题描述及相关截图:**
绑定了用户组的人员模板无法单独删除，但是使用页面批量删除按钮的时候没有做限制，可以勾选到已关联用户组的人员模板，并且可以成功删除

**期望是什么(What you expected to happen):**
前端和后台都要进行判断？前端不能允许绑定了用户组的人员模板可以进行批量删除，后台在实际删除也应该做校验

**Comment by lhzzforever** [comment]
Done
