### ISSUE TITLE
申请权限-选择关联操作后进行资源实例选择，在进行资源实例勾选后会自动填充关联操作的资源实例，但是在选择无限制的时候会失效

### ISSUE THREAD

**Issue by Canway-shiisa** [TencentBlueKing/bk-iam-saas#2706]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):
BUG反馈

**bk-iam-saas SaaS版本/bk-iam后台版本(The versions used):**
最新版本仍旧存在该问题（saas1.10.28）

**问题描述:**
在申请权限的时候，选择某一个操作，会自动勾选关联操作，后续在对操作进行资源实例选择的时候会自动同步填充关联操作的资源实例，但当我们勾选的资源实例为无限制的时候，该自动填充资源实例的功能就会失效
![无限制关联资源实例异常](https://github.com/TencentBlueKing/bk-iam-saas/assets/90179140/a914ed38-f3cc-4df6-90b3-af79e7bbc7c3)

**期望是什么(What you expected to happen):**
无论是勾选具体某些资源实例还是直接勾选无限制，应该保持一致，都能够进行关联操作的自动填充

**Comment by lhzzforever** [comment]
[图片]关联操作是后台给的，他也会返回这个操作下的资源实例数据

**Comment by lhzzforever** [comment]
![image](https://github.com/TencentBlueKing/bk-iam-saas/assets/46641918/28cc4017-59e8-4c0f-b752-4f628b1a4501)
![image](https://github.com/TencentBlueKing/bk-iam-saas/assets/46641918/28cc4017-59e8-4c0f-b752-4f628b1a4501)
![Uploading image.png…]()
![Uploading image.png…]()

**Comment by lhzzforever** [comment]
![企业微信截图_17181836599278](https://github.com/TencentBlueKing/bk-iam-saas/assets/46641918/33860108-5e0c-41ff-9e59-6dc52bd3b8bf)
![企业微信截图_17181836599278](https://github.com/TencentBlueKing/bk-iam-saas/assets/46641918/33860108-5e0c-41ff-9e59-6dc52bd3b8bf)
![企业微信截图_17181836599278](https://github.com/TencentBlueKing/bk-iam-saas/assets/46641918/33860108-5e0c-41ff-9e59-6dc52bd3b8bf)

**Comment by bevis-canway** [comment]
经过排查，上述现象未复现，但是发现一个新的缺陷。问题：依赖操作的资源实例只能与操作的资源实例同步新增，不能删减。例如，首次在操作上勾选3个资源实例时候，此时，依赖操作会同步回填3个一致的资源实例。然后，再次修改操作的资源实例为2个时候，依赖操作的资源实例仍然是原先的3个资源实例，表现为依赖操作的资源实例只能同步新增不能同步删减。

发现这个现象后，排查具体代码发现：相关依赖操作的处理逻辑只有ADD和UPDATE,无DELETE和RELATED。
代码位置：https://github.com/TencentBlueKing/bk-iam-saas/blob/0275f21ff813c1ba844733df17624ef9be19722e/saas/backend/apps/policy/views.py#L263-L288

**Comment by bevis-canway** [comment]
Uploading 录屏2024-06-25 17.57.16.mov…

**Comment by bevis-canway** [comment]
Uploading 录屏2024-06-25 17.57.16.mov…

**Comment by bevis-canway** [comment]
补充上面：
![权限中心依赖操作问题](https://github.com/TencentBlueKing/bk-iam-saas/assets/173782224/e5c30b76-530d-467f-93fb-d0759f3ae1f3)

**Comment by Canway-shiisa** [comment]
原先描述的问题无法复现，验证产生的新问题转TAPD单继续跟进
