### ISSUE TITLE
缺陷-【我的权限】页面，搜索框可以通过【ID】字段过滤，页面内无该字段信息。并且搜索为非数字后，多次弹屏报错

### ISSUE THREAD

**Issue by bevis-canway** [TencentBlueKing/bk-iam-saas#2771]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):
BUG反馈

**bk-iam-saas SaaS版本/bk-iam后台版本(The versions used):**
saas 1.10.28.   后台  1.12.14

**发生了什么(What happened):**
【我的权限】页面，搜索框可以通过【ID】字段过滤，页面内无该字段信息。并且搜索为非数字后，多次弹屏报错
![image](https://github.com/user-attachments/assets/6d2256de-e110-4f5e-9141-550e50010ec7)
![image](https://github.com/user-attachments/assets/aa7ce29a-cebc-47ce-a073-a8589846aae0)

**期望是什么(What you expected to happen):**
页面不显示【ID】字段，该过滤条件是否可以隐藏，字段校验失败的弹窗仅弹一次

**如何复现(How to reproduce it):**
在【我的权限】页面，搜索框选择【ID】过滤，输入非数字字符进行搜索。

**相关的日志详情(SaaS 及后台日志说明 https://bk.tencent.com/docs/document/6.0/160/8398)和截图等(Log & Screenshot):**
排查结论：四个接口抛出异常，导致四次弹窗。
接口报错：
{
    "result": false,
    "code": 1902412,
    "message": "参数校验失败: ID: 请填写合法的整数值。 (VALIDATE_ERROR)",
    "data": null
}

**备注(Anything else we need to know):**

**Comment by lhzzforever** [comment]
这里要不去掉id？使用id场景不多，或者要保留id的话，前端这边加个只能是数字类型的校验也行，看产品

**Comment by bevis-canway** [comment]
缺陷已修复在v1.10.33-beta.1，验证正常
