### ISSUE TITLE
[需求]bk-iam-saas打包脚本

### ISSUE THREAD

**Issue by MarsDy** [TencentBlueKing/bk-iam-saas#278]
FEATURE REQUEST：

bk-iam-saas 1.5.5/bk-iam 1.6.1

目前需要在开发者中心进行bk-iam-saas升级
bk-iam-saas 1.3.6升级到1.5.5

希望能提供1.5.5的打包脚本

**Comment by wklken** [comment]
麻烦走官方渠道获取iam smart包; 

目前是通过流水线构建(类似github action)的工具出包的, 不是简单的脚本

**Comment by MarsDy** [comment]
我们需要进行开源替换升级，所以需要自己打包。这块能配套一个打包脚本吗

**Comment by wklken** [comment]
暂时提供不了, 因为不是一个脚本, 而是一系列复杂的自动化步骤;

后续测试完成正式发布的release, 我们会将打好的包上传到github release页面, 届时可以下载到; 目前改造中
