### ISSUE TITLE
【优化需求】--【我的权限】页面搜索框，去掉无用的【ID】过滤字段

### ISSUE THREAD

**Issue by bevis-canway** [TencentBlueKing/bk-iam-saas#2781]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):

需求提交
**bk-iam-saas SaaS版本/bk-iam后台版本(The versions used):**
最新版本仍然有该缺陷

**发生了什么(What happened):**
我的权限页面，没有ID字段，过滤的时候会支持ID过滤
![image](https://github.com/user-attachments/assets/87068969-3a39-4b6a-8e59-76adbc1971d0)

**期望是什么(What you expected to happen):**
冗余ID字段隐藏

**如何复现(How to reproduce it):**

**相关的日志详情(SaaS 及后台日志说明 https://bk.tencent.com/docs/document/6.0/160/8398)和截图等(Log & Screenshot):**

**备注(Anything else we need to know):**

**Comment by lhzzforever** [comment]
Done
