### ISSUE TITLE
新建用户组->添加组权限时，选择多个权限模板后点击刷新，会将选择的操作保留 

### ISSUE THREAD

**Issue by bevis-canway** [TencentBlueKing/bk-iam-saas#2795]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):
BUG反馈

**bk-iam-saas SaaS版本/bk-iam后台版本(The versions used):**
最新版本仍存在
saas: 1.10.33-beta.1 后台版本：1.12.15

**发生了什么(What happened):**
缺陷描述：新建用户组->添加组权限时，选择多个权限模板后点击刷新，会将选择的操作保留

重现步骤：
选择多个模板
![image](https://github.com/user-attachments/assets/e5de4c89-de7d-4cdd-b590-5b46248a4a80)

点击刷新
![image](https://github.com/user-attachments/assets/b52bb188-dacb-42c8-8b25-3e2a46f7aa56)此时选择一个模板但却获取会将刷新前的模板
![image](https://github.com/user-attachments/assets/49725e27-270b-4e34-9555-501d753a45ac)

点击确认显示的模板是刷新前的
![image](https://github.com/user-attachments/assets/88f34fec-9b1b-4176-ae83-68640266ebff)

**期望是什么(What you expected to happen):**
刷新后，刷新前在页面勾选的权限模版能正常显示勾选状态。而不是后台是已勾选的状态，前端勾选状态被清除，造成误解。

**如何复现(How to reproduce it):**

**相关的日志详情(SaaS 及后台日志说明 https://bk.tencent.com/docs/document/6.0/160/8398)和截图等(Log & Screenshot):**

**备注(Anything else we need to know):**

**Comment by lhzzforever** [comment]
去掉刷新icon, 现在根据蓝鲸规范，异常状态下在表格里会有刷新文字，类似这种
![image](https://github.com/user-attachments/assets/ff17f7c4-ed7d-46ff-9cad-8649e358596f)

**Comment by bevis-canway** [comment]
修复版本v1.10.33版本，验证正常

**Comment by bevis-canway** [comment]
修复版本v1.10.33版本，验证正常

**Comment by bevis-canway** [comment]
去掉加载按钮
