### ISSUE TITLE
[SaaS] 社区问题记录

### ISSUE THREAD

**Issue by nannan00** [TencentBlueKing/bk-iam-saas#281]
### 1. 组织架构同步失败
https://bk.tencent.com/s-mart/community/question/3793
![企业微信截图_16342051911922](https://user-images.githubusercontent.com/17491932/138013064-aae7c067-afea-4dfb-b072-426141081034.png)

```
权限中心是每天凌晨定时全量同步用户管理里的组织架构，所以新用户第二天才能在权限中心看到

1. 需要确认权限中心里组织架构最近一次全量同步的时间
use bk_iam;
select * from organization_syncrecord order by id desc limit 10;

2. 若最近一次时间是昨天，而出问题的用户是今天新增的，则需要等到明天再重试，或者 以超级管理员身份进入权限中心的导航“用户”对组织架构进行手动全量同步

3. 如果最近一次失败，则需要查询 IAM SaaS celery日志，查询同步失败原因，解决后再进行一次手动全量同步

从日志可以看出这个问题应该是用户手动删除过DB导致的

解决方式：删除DB部分数据，然后立即到页面上去同步组织架构

use bkiam;

delete from subject_department;
```

### 2. 社区用户在修改域名域名端口（如：paas.bktencen.com---> paas.bktencent.org:8080），蓝鲸所有的产品都可以打开，只有权限中心打开是报了加载资源上有问题
![企业微信截图_16342678094906](https://user-images.githubusercontent.com/17491932/138013349-dc299441-12eb-44d6-bc06-f6a9aacd9290.png)

```
IAM SaaS 1.4.21 引入的BUG，已在版本1.5.8 解决了
```

**Comment by ganzaofang** [comment]
如https://bk.tencent.com/docs/document/6.0/160/8630页面中的案例：
```json
# action model
{
  "id": "develop_app",
  "name": "开发SaaS应用",
  "name_en": "develop app",
  "description": "一个用户是否能够开发SaaS",
  "description_en": "Is allowed to develop SaaS app",
  "type": "",
  "related_resource_types": [
    {
      "system_id": "bk_paas",
      "id": "app",
      "name_alias": "",
      "name_alias_en": "",
      "related_instance_selections": [
        {
          "system_id": "bk_paas",
          "id": "app_view"
        }
      ]
    }
  ],
  "version": 1
}

# instance selection model
{
  "id": "app_view",
  "name": "应用视图",
  "name_en": "app_view",
  "resource_type_chain": [
    {
      "system_id": "bk_paas",
      "id": "app"
    }
  ]
}
```
之前 resource_type_chain 只关联一层（即自己），现在实例视图的层级发生了改变多关联了一层project;
```json
# instance selection model
{
  "id": "task",
  "name": "任务实例",
  "name_en": "Task",
  "resource_type_chain": [
    {
      "system_id": "bk_sops",
      "id": "project"
    },
    {
      "system_id": "bk_sops",
      "id": "task"
    }
  ]
}
```

问题：
如果所有任务都有权限：
task._bk_iam_path_ starts_with /task,*/
那么变动后生成的路径为：
task._bk_iam_path_ starts_with /project,蓝鲸/task,*/
那么原来配置的策略权限路径是否需要全部更新： /task -> /project,蓝鲸/task，否则鉴权将出现问题。
原贴链接：https://bk.tencent.com/s-mart/community/question/3853?type=answer

**Comment by ganzaofang** [comment]
> > > 如 https://bk.tencent.com/docs/document/6.0/160/8630    页面中的案例：
> > 
> > 
> > > ```json
> > > #动作模型
> > > {
> > >   "id": "develop_app",
> > >   "name": "开发SaaS应用",
> > >   "name_en": "develop app",
> > >   "description": "一个用户是否能够开发SaaS",
> > >   "description_en": "Is allowed to develop SaaS app",
> > >   "type": "",
> > >   ”related_resource_types“: [
> > >     {
> > >       “ SYSTEM_ID ”： “ bk_paas ”，
> > >        “ ID ”： “应用程序”，
> > >        “ name_alias ”： “ ”，
> > >        “ name_alias_en ”： “ ”，
> > >        “ related_instance_selections ”：[
> > >         {
> > >           “ system_id ”： “ bk_paas ”，
> > >            “ id ”： “ app_view ”
> > >         }
> > >       ]
> > >     }
> > >   ],
> > >   “版本”： 1
> > > }
> > > 
> > > # 实例选择模型
> > > {
> > >   “ id ”： “ app_view ”，
> > >    “ name ”： “应用视图”，
> > >    “ name_en ”： “ app_view ”，
> > >    “ resource_type_chain ”：[
> > >     {
> > >       “ system_id ”： “ bk_paas ”，
> > >        “ id ”： “ app ”
> > >     }
> > >   ]
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 之前 resource_type_chain 只关联一层（即自己），现在实例视图的层级发生了改变多关联了一层project;
> > > ```json
> > > # 实例选择模型
> > > {
> > >   " id " : " task " ,
> > >    " name " : "任务实例" ,
> > >    " name_en " : " Task " ,
> > >    " resource_type_chain " :[
> > >     {
> > >       “ system_id ”： “ bk_sops ”，
> > >        “ id ”： “项目”
> > >     },
> > >     {
> > >       “ system_id ”： “ bk_sops ”，
> > >        “ id ”： “任务”
> > >     }
> > >   ]
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 问题：
> > > 如果所有任务都有权限： task._bk_iam_path_ starts_with /task,_/
> > > 那么变动后生成的路径为： task._bk_iam_path_ starts_with /project,蓝鲸/task,_/
> > > 那么原来配置的策略权限路径是否需要全部更新： /task -> /project,蓝鲸/task，否则鉴权将出现问题。
> > > 原贴链接：https://bk.tencent.com/s-mart/community/question/3853?type=answer
> 
> 应该是理解有误:
> 
> * 实例视图只有一层, 表示就是一个平铺的列表, 不可能选择到根节点或中间节点, 只会配置出`x.id in [1,2,3]` 这类
> * 任务实例task这个是两层的, 勾选项目下的具体实例, 得到 `task.bk_iam_path starts_with /project,蓝鲸/  AND x.id in [1,2,3]`; 如果只勾选项目, 得到`task.bk_iam_path starts_with /project,蓝鲸/`;
> 
> 一层变两层, 理论上原先配置的策略会`更大`, 因为没有`限制`; 可以根据实际需求决定要不要删除或迁移

描述的是 task._bk_iam_path_ starts_with 由 /task,*/ 变为 /project,蓝鲸/task,*/ ，那这个 starts_with肯定不生效，所以不存在“原先配置的策略会更大”的情况，这种情况是实例视图（ resource_type_chain ）向上添加父节点导致的，对于这种情况你们这边是怎么考虑的？

**Comment by ganzaofang** [comment]
权限中心查看所有用户组是显示有用户存在，但点逐一进去组后，发现没有一个用户，提示暂无数据。尝试过同步组织架构信息，没有效果
![image](https://user-images.githubusercontent.com/30789292/139610576-f6fc5ca7-bd1b-4802-8819-cc9e1b5480c2.png)
![image](https://user-images.githubusercontent.com/30789292/139610603-c930c541-4416-4301-a117-364f9099ddb2.png)
查看appo 机器上的/data/bkce/paas_agent/apps/logs/bk_iam/celery.log
![image](https://user-images.githubusercontent.com/30789292/139610639-d2822d16-a7d6-4ec3-b71d-b0c5bdc144f0.png)

**Comment by wklken** [comment]
@ganzaofang 目前这个数量是异步同时的, 实时删除这个count目前不会实时更新(排期开发中)

**Comment by ganzaofang** [comment]
给用户组授权的时候出现以下报错
![image](https://user-images.githubusercontent.com/30789292/139611983-12df4357-9ac4-49d9-bd75-b1f2992e7995.png)
appo机器的 /data/bkce/paas_agent/apps/logs/bk_iam/bk_iam.log日志信息：
![image](https://user-images.githubusercontent.com/30789292/139612013-e2d4846b-1401-453c-a83e-057276e525a0.png)
原贴地址：https://bk.tencent.com/s-mart/community/question/3958?type=answer

**Comment by zhu327** [comment]
@ganzaofang 接入系统fetch_instance_info 查询display_name 返回的是none导致

**Comment by zhu327** [comment]
https://github.com/celery/celery/issues/3729

**Comment by nannan00** [comment]
> @ganzaofang 接入系统fetch_instance_info 查询display_name 返回的是none导致

IAM SaaS 版本 >= 1.5.0 已优化
https://github.com/TencentBlueKing/bk-iam-saas/blob/217600fa6e5fd466fff9c33c20c4dbd7c69f77d9/saas/backend/service/resource.py#L106

**Comment by ganzaofang** [comment]
编辑权限模板后，一直显示编辑中
社区版版本：6.0.5
权限中心saas：V1.4.24 
后台 ：1.7.7
![image](https://user-images.githubusercontent.com/30789292/166880593-5ba67444-0458-4cb4-984e-fba9abe05cf2.png)
原贴地址：https://bk.tencent.com/s-mart/community/question/7421?type=answer

**Comment by zhu327** [comment]
> 编辑权限模板后，一直显示编辑中 社区版版本：6.0.5 权限中心saas：V1.4.24 后台 ：1.7.7 ![image](https://user-images.githubusercontent.com/30789292/166880593-5ba67444-0458-4cb4-984e-fba9abe05cf2.png) 原贴地址：https://bk.tencent.com/s-mart/community/question/7421?type=answer

建议升级到saas 1.5.8 以上版本, 增加了后台任务重试机制
https://github.com/TencentBlueKing/bk-iam-saas/blob/v1.5.8/saas/backend/long_task/tasks.py#L225

**Comment by ganzaofang** [comment]
bk_iam版本1.10.4，我们后台调用paas登录接口，将认证后的token值添加进请求体的cookie中，调用蓝鲸权限中心查询用户组的接口（接口来源，前台抓包获得），可以获得数据，但是当查询用户组内的成员时，就会报错"1902403:您没有执行该操作的权限"

初步排查：我们使用postman测试发现，bk_iam版本为1.7.7的环境，是可以通过只填加认证token来获得数据，但是在1.10.4版本上不仅要添加认证token，还需要添加另外一个"bkiam_sessionid"的cookie才能获得数据。但是存在另外一个问题，就是在后台接口调用获得的sessionId无法生效，只有从浏览器上找出来的sessionId才能正常获得数据。
原贴地址：https://bk.tencent.com/s-mart/community/question/7788
![image](https://user-images.githubusercontent.com/30789292/171098551-84478d5d-773c-40e9-8219-af9fada4a5f3.png)
![image](https://user-images.githubusercontent.com/30789292/171098632-0179925a-6d7d-469e-987b-08f83f1a0994.png)

**Comment by zhu327** [comment]
> bk_iam版本1.10.4，我们后台调用paas登录接口，将认证后的token值添加进请求体的cookie中，调用蓝鲸权限中心查询用户组的接口（接口来源，前台抓包获得），可以获得数据，但是当查询用户组内的成员时，就会报错"1902403:您没有执行该操作的权限"
> 
> 初步排查：我们使用postman测试发现，bk_iam版本为1.7.7的环境，是可以通过只填加认证token来获得数据，但是在1.10.4版本上不仅要添加认证token，还需要添加另外一个"bkiam_sessionid"的cookie才能获得数据。但是存在另外一个问题，就是在后台接口调用获得的sessionId无法生效，只有从浏览器上找出来的sessionId才能正常获得数据。 原贴地址：https://bk.tencent.com/s-mart/community/question/7788 ![image](https://user-images.githubusercontent.com/30789292/171098551-84478d5d-773c-40e9-8219-af9fada4a5f3.png) ![image](https://user-images.githubusercontent.com/30789292/171098632-0179925a-6d7d-469e-987b-08f83f1a0994.png)

查询用户组的成员需要有分级管理员的身份, 这个身份是保存在session中的, 所以需要sessionid

**Comment by ganzaofang** [comment]
社区版6.0.4 bkiam_saas 1.4.24 iam后台  1.7.7, Microsoft Active Directory用户权限授权不生效，蓝鲸本创建的本地帐户正常
![image](https://user-images.githubusercontent.com/30789292/184779471-28fe5bc6-a02f-45f0-a961-b418ede97099.png)
![image](https://user-images.githubusercontent.com/30789292/184779522-edacc5b1-ef6c-47da-9ff4-bfe657f68597.png)
权限中心是否支持给 Microsoft Active Directory 用户授权

**Comment by zhu327** [comment]
权限中心的用户来自于用户管理, 请按以下步骤检查用户数据:

1. 先确认用户管理是否有同步到Microsoft Active Directory 用户, 如果没有从用户管理同步入手解决问题
2. 如果用户管理有, 到权限中心的组织架构页面查询有没有对应的人, 如果没有点击同步尝试从用户管理同步数据
3. 如果同步有问题, 贴同步日志到这里, 如果没问题, 还是找不到人, 联系用户管理处理
4. 如果同步完成后找到人, 授权应该会正常
