### ISSUE TITLE
[SaaS]权限交接需求

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#302]
当用户离职或者转岗后，需要把个人权限转接给下一位。

**Comment by Xmandon** [comment]
https://jhtf53.axshare.com

**Comment by wklken** [comment]
1. 似乎涉及到itsm单据流程? (拆单合单)
2. 用户组的交接, 如果交给 3 个人, 会生成 3 个单据?
3. 自定义权限交接?
4. 成为分级管理员目前有对接 ITSM 审批? 3 个分级管理员交接给 3 个人, 会生成 9个单据?

**Comment by Xmandon** [comment]
> 1. 似乎涉及到itsm单据流程? (拆单合单)
> 2. 用户组的交接, 如果交给 3 个人, 会生成 3 个单据?
> 3. 自定义权限交接?
> 4. 成为分级管理员目前有对接 ITSM 审批? 3 个分级管理员交接给 3 个人, 会生成 9个单据?

一期，整体权限交接，只交接给1人，只涉及一个审批流程，审批流程涉及通用角色：申请人本人（企业大部分可能交接不需要审批）、leader、超级管理员等，不涉及分级管理员、系统管理员审批角色。

**Comment by Xmandon** [comment]
https://1i9wag.axshare.com/#id=5gs9s9&p=%E4%BA%A4%E6%8E%A5%E5%8E%86%E5%8F%B2&g=1
原型刷新

**Comment by Xmandon** [comment]
https://smn03t.axshare.com
原型刷新

**Comment by Xmandon** [comment]
刷新原型：
https://tz6neo.axshare.com/#id=c1ur3a&p=%E6%9D%83%E9%99%90%E4%BA%A4%E6%8E%A5&g=1
