### ISSUE TITLE
[SaaS]依赖操作问题

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#306]
问题描述：

`执行流水线`的依赖操作是`查看流水线`，当用户已经拥有这两个自定义操作权限时，如果用户需要申请新的流水线权限，用户先在`查看流水线`操作下选择了a流水线，然后在`执行流水线`操作下选择a流水线，这个时候系统会应用“依赖操作”的规则自动勾选`查看流水线`操作下重新选择a流水线，这个时候`查看流水线`操作下a流水线变成不可删除（这是bug，应该可删除），导致用户提交申请的时候，只提交了`执行流水线`权限，没有提交`查看流水线权限`。

**Comment by huangpeng0428** [comment]
done
