### ISSUE TITLE
[Engine] 项目开源

### ISSUE THREAD

**Issue by zhu327** [TencentBlueKing/bk-iam-saas#328]
11月中开始

**Comment by wklken** [comment]
需确认, 有空搞, 没空转给我

-----

相关并行事项:
- 去笛卡尔积
- 容器化相关事项
- 接入 apigateway, 同步数据
- iam-engine开源 (需要二进制支持部署)

**Comment by wklken** [comment]
附加事项: 社区版及企业版 3.1 需要部署同学支持
