### ISSUE TITLE
[bug] 分级管理员用户组模板授权报错, 系统: bk_itsm 操作: project_view

### ISSUE THREAD

**Issue by zhu327** [TencentBlueKing/bk-iam-saas#379]
多个系统, bk_itsm, bk_sops, 存在同名的project_view, 在合并选择的时候, itsm的project_view会选择到bk_sops的project

**Comment by zhu327** [comment]
现在先合并选择, 然后展开提交

**Comment by zhu327** [comment]
经排查是由于依赖操作导致的问题:

1. 在除了分级管理员的授权范围的选择可以选择多个系统外, 其它的场景都只能选择同一个系统的操作, 所以直接使用操作id作为依赖操作的匹配项没有问题
2. 但是在分级管理员这里可以选择多个系统, 同名的操作id会导致依赖操作出现错乱, 需要前端在匹配时使用系统id与操作id一起匹配完成依赖操作的填充

**Comment by huangpeng0428** [comment]
已修复
