### ISSUE TITLE
[SaaS]环境属性方案原型

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#385]
优先实现支持时间窗口的方案

**Comment by wklken** [comment]
https://bk.tencent.com/docs/document/6.0/160/8440

操作分为两类:
1. 关联资源
2. 不关联资源

理论上, 不关联资源的也需要支持`环境属性`

即, 支持`只有 8:00-20:00 才能访问开发者中心`

------------------

所以设计上需要同时考虑

------------------
问题: 后台不关联资源的操作, 目前是没有存表达式的, 届时怎么处理????? @zhu327

**Comment by Xmandon** [comment]
https://2g3zyg.axshare.com/#id=pd5w34&p=%E6%9D%A1%E4%BB%B6&g=1

**Comment by wklken** [comment]
1. 生效条件, 是可选的, 而且我们也倾向于让用户不要填; 所以交互上, 需要优化下; 目前的设计看着是必填的;
2.生效条件, 时间范围和时间周期, 以及另外三个, 是可以叠加的,  `AND`关系

**Comment by Xmandon** [comment]
更新原型
https://puuth9.axshare.com

**Comment by zhu327** [comment]
> https://bk.tencent.com/docs/document/6.0/160/8440
> 
> 操作分为两类:
> 
> 1. 关联资源
> 2. 不关联资源
> 
> 理论上, 不关联资源的也需要支持`环境属性`
> 
> 即, 支持`只有 8:00-20:00 才能访问开发者中心`
> 
> 所以设计上需要同时考虑
> 
> 问题: 后台不关联资源的操作, 目前是没有存表达式的, 届时怎么处理????? @zhu327

不关联资源类型的操作暂不支持配置环境属性, 对后台的相关逻辑冲击比较大

**Comment by Xmandon** [comment]
刷新原型：
https://3p1efy.axshare.com

**Comment by wklken** [comment]
#432

**Comment by Xmandon** [comment]
刷新原型
https://atmwzq.axshare.com

**Comment by zhu327** [comment]
同一条策略中多个resource_group如果配置的时区有差异会导致当前的计算逻辑有问题

比如, 用户之前的时区是`上海`配置了环境属性, 后来用户把时区修改为`纽约`了, 然后修改了同一条策略, 增加了一组, 这个时候配置的时区理论应该是`纽约`, 但是会导致鉴权有问题

单前取策略的时区, 取的是第一条

**Comment by wklken** [comment]
限制, 一条策略只能有一个时区, 即, 必须检查一致性

**Comment by Xmandon** [comment]
补充展示页面 @Xmandon

**Comment by Xmandon** [comment]
补充条件展示原型
https://5b29s3.axshare.com/#id=kfgeji&p=%E6%88%91%E7%9A%84%E6%9D%83%E9%99%90%E5%B1%95%E7%A4%BA&g=1

**Comment by wklken** [comment]
已完成, close

**Comment by Xmandon** [comment]
补充申请单
https://lirqrb.axshare.com/#id=9u1h1y&p=%E5%B8%A6%E6%9D%A1%E4%BB%B6%E7%9A%84%E7%94%B3%E8%AF%B7%E5%8D%95&g=1
