### ISSUE TITLE
[SaaS]权限交接功能实现

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#398]
原型issue https://github.com/TencentBlueKing/bk-iam-saas/issues/302#issuecomment-968481776

**Comment by Canway-shiisa** [comment]
1. 用户组权限交接：基于现有的/api/v1/users/groups/ 改造，增加个标识字段enabled给前端，如果加入方式是通过组织，则enabled为0，标识该权限不可交接；
  Q1：[图片][图片]设计这里的“来源”是否就是原来接口的“所属分级管理员”
2. 自定义权限交接：复用 /api/v1/policies/systems/ 
3. 分级管理员交接：基于 /api/v1/roles/grade_managers/改造
4. 超级管理员交接：基于 /api/v1/roles/super_manager/members/改造
5. 系统管理员交接：基于 /api/v1/roles/system_manager/ 改造

6.[图片]权限交接的提交；【权限移除和给交接人授权放置在一个事务里面处理】
6.1 用户组权限、自定义权限 这里可以参考用户组授权，和添加自定义权限部分
6.2 管理员部分的权限交接部分，调用iam后台接口进行subject_id的替换

**Comment by nannan00** [comment]
> 1. 用户组权限交接：基于现有的/api/v1/users/groups/ 改造，增加个标识字段enabled给前端，如果加入方式是通过组织，则enabled为0，标识该权限不可交接；
>    Q1：
>    ![image](https://user-images.githubusercontent.com/90179140/142375768-bf4d278b-fb2c-423a-b9da-0630d789d058.png)
>    ![image](https://user-images.githubusercontent.com/90179140/142375803-8f17f465-c33e-4c2b-93ff-823910a69a98.png)
>    =》设计这里的“来源”是否就是原来接口的“所属分级管理员”
> 2. 自定义权限交接：复用 /api/v1/policies/systems/
> 3. 分级管理员交接：基于 /api/v1/roles/grade_managers/改造
> 4. 超级管理员交接：基于 /api/v1/roles/super_manager/members/改造
> 5. 系统管理员交接：基于 /api/v1/roles/system_manager/ 改造
> 
> ![image](https://user-images.githubusercontent.com/90179140/142375861-5402413a-c976-4ec9-9030-ece4e0d6d396.png) 权限交接的提交；【权限移除和给交接人授权放置在一个事务里面处理】 6.1 用户组权限交接、自定义权限交接 这里可以参考用户组授权，和添加自定义权限部分逻辑 6.2 管理员部分的权限交接部分，调用iam后台接口进行subject_id的替换

1. 本身/api/v1/users/groups/接口就是通过department_id是否为0来判断是继承组织的，还是直接加入的，对于继承组织的，则不可交接
Q1: 是滴，设计里的用户组来源就是 原来接口的“所属分级管理员

2. 自定义权限交接，可以直接使用 /api/v1/policies/systems/ 和 /api/v1/policies/

3. 分级管理员交接，可直接使用 /api/v1/accounts/user/roles/ 接口

4/5. 超级管理员和系统管理员交接需要单独接口

6. 需要考虑
    - 交接过程应该是一个比较耗时操作，得考虑使用Celery任务来实现，可以考虑每种交接为一个小任务，包括移除操作者的原有每种类型的权限，然后有个可以展示的页面来提醒进度，这样可能更有利于查看和重试
 
    - 交接过程中异常后，如何处理
    - 交接过程的考虑加锁，避免并行并发多个交接

**Comment by Canway-shiisa** [comment]
@Xmandon Edwin，辛苦看下jianan 评论第6点这边的异步场景

**Comment by Canway-shiisa** [comment]
@Xmandon 辛苦看下 @nannan00 评论第6点中的异步场景~

**Comment by zhu327** [comment]
1. 用户交接的逻辑: 从用户组的成员中删除当前的用户, 用户组新增成员被交接人
2. 自定义权限交接逻辑: 查询当前用户删除自定义权限(通过policy_id), 删除这些poliy_id的权限, 对被交接人授权这些权限
3. 角色的交接逻辑: 删除role中的当前的用户, 添加被交接人

**Comment by Canway-shiisa** [comment]
> > 1. 用户组权限交接：基于现有的/api/v1/users/groups/ 改造，增加个标识字段enabled给前端，如果加入方式是通过组织，则enabled为0，标识该权限不可交接；
> >    Q1：
> >    ![image](https://user-images.githubusercontent.com/90179140/142375768-bf4d278b-fb2c-423a-b9da-0630d789d058.png)
> >    ![image](https://user-images.githubusercontent.com/90179140/142375803-8f17f465-c33e-4c2b-93ff-823910a69a98.png)
> >    =》设计这里的“来源”是否就是原来接口的“所属分级管理员”
> > 2. 自定义权限交接：复用 /api/v1/policies/systems/
> > 3. 分级管理员交接：基于 /api/v1/roles/grade_managers/改造
> > 4. 超级管理员交接：基于 /api/v1/roles/super_manager/members/改造
> > 5. 系统管理员交接：基于 /api/v1/roles/system_manager/ 改造
> > 
> > ![image](https://user-images.githubusercontent.com/90179140/142375861-5402413a-c976-4ec9-9030-ece4e0d6d396.png) 权限交接的提交；【权限移除和给交接人授权放置在一个事务里面处理】 6.1 用户组权限交接、自定义权限交接 这里可以参考用户组授权，和添加自定义权限部分逻辑 6.2 管理员部分的权限交接部分，调用iam后台接口进行subject_id的替换
> 
> 1. 本身/api/v1/users/groups/接口就是通过department_id是否为0来判断是继承组织的，还是直接加入的，对于继承组织的，则不可交接
>    Q1: 是滴，设计里的用户组来源就是 原来接口的“所属分级管理员
> 2. 自定义权限交接，可以直接使用 /api/v1/policies/systems/ 和 /api/v1/policies/
> 3. 分级管理员交接，可直接使用 /api/v1/accounts/user/roles/ 接口
> 
> 4/5. 超级管理员和系统管理员交接需要单独接口
> 
> 1. 需要考虑
>    
>    * 交接过程应该是一个比较耗时操作，得考虑使用Celery任务来实现，可以考虑每种交接为一个小任务，包括移除操作者的原有每种类型的权限，然后有个可以展示的页面来提醒进度，这样可能更有利于查看和重试
>    * 交接过程中异常后，如何处理
>    * 交接过程的考虑加锁，避免并行并发多个交接

3. 分级管理员这里，直接使用 /api/v1/accounts/user/roles/ 接口返回用户角色列表的话，缺少原型中展示的描述信息：
![image](https://user-images.githubusercontent.com/90179140/142408094-ad1651e8-9774-4f2a-a0dc-d4fe45f9e75b.png)
，这里直接使用 /api/v1/roles/grade_managers/ 这个接口会不会更好？
4.5. 同3，超级管理员和系统管理员这里分别使用 /api/v1/roles/super_manager/members/ 和 /api/v1/roles/system_manager/ 接口是否可以？
6. 如果使用celery任务来实现，是否需要增加任务状态记录表等其他相关的记录（具体还有哪些，有没有可以复用或者参考的模块）；原有的长时任务记录表部分是否就是实现这个记录？

**Comment by zhu327** [comment]
3. 可以修改这个/api/v1/accounts/user/roles/增加相关信息, 这里是用户自己的role, 与/api/v1/roles/grade_managers/ 不同
4. 同上, 一个接口搞定, 如果要区分, 前端自行处理

**Comment by nannan00** [comment]
3. 缺少信息，可以在/api/v1/accounts/user/roles/上增加，需要理解，不同接口的用户身份是不一样的，有些接口，比如/api/v1/roles/super_manager/ 是切换到超级管理员身份才可以调用，否则会失败的，权限交接是普通用户身份下进行的

4/5.  不能复用接口，可以新增一个接口实现

**Comment by Canway-shiisa** [comment]
## 权限交接开发方案

1. 用户组权限交接

复用/api/v1/users/groups/

- 其中，加入方式根据department_id标识，department_id为0则是直接加入的，否则就是继承组织的，继承组织的，则不可交接

2. 自定义权限交接

复用/api/v1/policies/systems/ 

复用/api/v1/policies/

3. 分级管理员

复用/api/v1/accounts/user/roles

4. 系统管理员、超级管理员

新增一个接口，返回管理员类型与成员列表



5. 异步交接

5.1 新增交接记录表，包含表字段有【id，created_time，updated_time，executor【request.user.username】，status：记录交接状态，存在 成功、失败、交接中三种状态，exact_info：记录其他信息   {交接阶段:"用户组权限{XXX}移除/用户组权限{XXX}授予"，"交接权限类型":"包括三类，用户组权限类型、自定义权限类型、分级管理员权限类型，系统管理员权限类型，超级管理员权限类型"，"错误信息": ""}】



5.2 用户组权限交接

- 生成需要交接的用户组权限列表

```
[用户组权限A，用户组权限B, 用户组权限C]
```

- 循环用户组权限列表 

  - 将用户组A权限授权给被交接人
  - 在用户交接记录表中添加交接记录    

  ```
  status=HandOverStatus.Running.value,exact_info={type:"group", stage:"用户组A授权", error_msg:""}
  ```

  - 授权成功，进行返回并更改用户交接记录表中的交接记录状态

  ```
  status=HandOverStatus.SUCCESS.value,exact_info={type:"group", stage:"用户组A授权", error_msg:""}
  ```

  - 移除交接人在用户组A的用户组权限
  - 在用户交接记录表中添加交接记录

  ```
  status=HandOverStatus.Running.value,exact_info={type:"group", stage:"用户组A权限移除", error_msg:""}
  ```

  - 移除成功，进行返回并更改用户交接记录表中的交接记录状态

  ```
  status=HandOverStatus.SUCCESS.value,exact_info={type:"group", stage:"用户组A权限移除", error_msg:""}
  ```

  - 循环处理用户组权限B、用户组权限C

...



5.3 自定义权限交接

- 生成需要交接的自定义权限列表

```
[自定义权限A，自定义权限B, 自定义权限C]
```

- 循环自定义权限列表 

  - 将用户组A权限授权给被交接人
  - 在用户交接记录表中添加交接记录    

  ```
  status=HandOverStatus.Running.value,exact_info={type:"policies", stage:"自定义权限A授权", error_msg:""}
  ```

  - 授权成功，进行返回并更改用户交接记录表中的交接记录状态

  ```
  status=HandOverStatus.SUCCESS.value,exact_info={type:"policies", stage:"自定义权限B授权", error_msg:""}
  ```

  - 移除交接人的自定义A权限
  - 在用户交接记录表中添加交接记录

  ```
  status=HandOverStatus.Running.value,exact_info={type:"policies", stage:"自定义权限A移除", error_msg:""}
  ```

  - 移除成功，进行返回并更改用户交接记录表中的交接记录状态

  ```
  status=HandOverStatus.SUCCESS.value,exact_info={type:"policies", stage:"自定义权限B移除", error_msg:""}
  ```

  - 循环处理自定义权限B、自定义权限C

...



5.4 角色权限交接

- 生成分级管理员列表

  ```
  [分级管理员1,分级管理员2,分级管理员3]
  ```

- 将被交接人添加到分级管理员1
- 在用户记录交接表中添加交接记录

```
status=HandOverStatus.Running.value,exact_info={type:"grade_managers", stage:"分级管理员1授权", error_msg:""}
```

- 授权成功，进行返回并更改用户交接记录表中的交接记录状态

```
status=HandOverStatus.Success.value,exact_info={type:"grade_managers", stage:"分级管理员1授权", error_msg:""}
```

- 将交接人从分级管理员1中移除

- 在用户交接记录表中添加交接记录

```
status=HandOverStatus.Running.value,exact_info={type:"grade_managers", stage:"分级管理员1移除", error_msg:""}
```

- 移除成功，进行返回并更改用户交接记录表中的交接记录状态

```
status=HandOverStatus.SUCCESS.value,exact_info={type:"grade_managers", stage:"分级管理员1移除", error_msg:""}
```

**Comment by zhu327** [comment]
5.3 自定义权限的交接分系统, 一个系统内的所有policies一次性交接, 不是按单条来的

---

- 可以详细阅读下具体的代码, 贴一下各个交接的部分需要使用到的, biz的方法, 考虑下现有的biz的方法是否能用到上面列到的逻辑中, 会不会有问题
- 另外如果交接过程中如果出现fail如何处理, 可以考虑下, 不需要现在就做
- 用户提交交接只是一个request, 只有一个request_id, 考虑下如何将请求与以上记录的零散的记录关联起来

**Comment by nannan00** [comment]
5.1 ： 交接记录表，需要考虑查询的便利性，比如需要查询哪些用户组等已经在交接中的，这时候打开交接页面应该会出现禁止勾选，但目前设计的extra_info字段的值是json，无法快速查询
- 每一个用户组、每条自定义权限、每一个分级管理员 都可以独立互不影响的进行交接，表模型涉及是需要考虑这个点

实际实现时，注意代码的抽象，定义每种类型交接类型的 handle和retry方法 以及记录的更新等


需要补充 异步任务的生命周期：任务粒度，如何创建，如何执行(细节：调用哪些已有函数)，异常如何处理(retry机制如何运行)

**Comment by wklken** [comment]
5.1 新增交接记录表，包含表字段有【id，created_time，updated_time，executor【request.user.username】，status：记录交接状态，存在 成功、失败、交接中三种状态，exact_info：记录其他信息 {交接阶段:"用户组权限{XXX}移除/用户组权限{XXX}授予"，"交接权限类型":"包括三类，用户组权限类型、自定义权限类型、分级管理员权限类型，系统管理员权限类型，超级管理员权限类型"，"错误信息": ""}】

-----

表设计可以单独放, 以表格/列表的方式(而不是平铺)更清晰

- id
- created_time
- updated_time
- executor : request.user.username
- status:  成功、失败、交接
- exact_info: 记录其他信息 {交接阶段:"用户组权限{XXX}移除/用户组权限{XXX}授予"，"交接权限类型":"包括三类，用户组权限类型、自定义权限类型、分级管理员权限类型，系统管理员权限类型，超级管理员权限类型"，"错误信息": ""}】

-----

逻辑的伪代码描述, 可以更进一步, 哪一步, 调用哪个模块的那个方法(这样有助于反向去了解代码的功能, 也能在第一时间review出是否有问题)

**Comment by Canway-shiisa** [comment]
## 权限交接开发方案

### 数据库设计方案

1. 交接任务表

   ![image-20211124174036441](C:\Users\canway\AppData\Roaming\Typora\typora-user-images\image-20211124174036441.png)

   

2. 交接明细表

![image-20211124192153946](C:\Users\canway\AppData\Roaming\Typora\typora-user-images\image-20211124192153946.png)



3. 需要探讨的点

- 过程状态要不要记录：目前是通过交接任务表(HandOverTask)记录整个交接过程的状态，并通过交接明细表记录了交接过程的具体明细，但是缺乏用户组权限/自定义权限/角色权限，各个类别权限交接的单独状态；
- 交接明细表(HandOverDetail)中，目前的设计是记录了permission_name，这个是否需要存储(比如用户组权限中用户组A的名字会不会变更，是否影响)



### 接口设计方案

1. 用户组权限交接

复用/api/v1/users/groups/

- 其中，加入方式根据department_id标识，department_id为0则是直接加入的，否则就是继承组织的，继承组织的，则不可交接

2. 自定义权限交接

复用/api/v1/policies/systems/ 

复用/api/v1/policies/

3. 分级管理员

复用/api/v1/accounts/user/roles

4. 系统管理员、超级管理员

新增一个接口，返回管理员类型与成员列表



5. 异步交接

![image-20211123162055530](C:\Users\canway\AppData\Roaming\Typora\typora-user-images\image-20211123162055530.png)

5.1 交接接口

- url：/api/v1/handover/

- method：post
- in：

```json
{
  "executor": "zhangsan",

  "transferor": "lisi",

  "reason": "reason for handover ",

  "handover_info":{
      				"group": [{"id":"5","name":"paas用户组"}, {"id":"2","name":"数据平台"}],
      
                    "custom":[{"id":"app-mgmt","name":"应用配置中心"},{"id":"bkiam_demo","name":"蓝鲸权限"}],
      
    				"super_man":[{"id":1,"name":"告警中心","description":""},{"id":2,"name":"告警中心"}],

					"system_man":[{"id":3,"name":"告警中心","description":""},{"id":4,"name":"告警中心"}],

					"grade_man":[{"id":13,"name":"告警中心","description":""},{"id":14,"name":"告警中心"}]
 			
                   }

}
```

- out：

```json
{
	
  "message": "OK",

  "code": 0,

  "data": {"id": 1},	# 返回交接任务记录Id

  "result": **true**,
}
```

- 大致逻辑：

```
class HandOverViewSet():
	def post(self, request):
        # 异步执行任务
        handover_info = json.loads(request.data.handover_info)	
		try:
            cache.lock()  # 使用非阻塞型分布式锁 避免任务重复执行 
            handover_task = HandOverTask.objects.create(executor=executor,transferor=transferor,status=RUNNING,handover_info=handover_info) 创建任务记录
            
            handover_task_id = hanover_task.id 
            permission_hand_over.delay(handover_task_id)

		except..:
			handover_task = HandOverTask.objects.create(executor=executor,transferor=transferor,status=Faild,handover_info=handover_info) 创建任务记录
		handover_task_id = hanover_task.id 
		

	
@task
def permission_hand_over(handover_task_id):

	handover_info = HandOverTask.objects.filter(id=handover_task_id).values('handover_info')	
	for permission_category in handover_info：	# 循环交接类别列表
    	handover_info_detail = handover_info["permission_category"]
    	
         # 权限交接
         try:
         	execute_handover(permission_category, handover_info_detail)
         	
         execpt:
         	logging.error()
         	
    HandOverTask.objects.filter(id=handover_task_id).update(status=SUCCESS)	# 创建任务记录    
   	return Response({"data":handover_task_id})


 
def execute_handover(permission_category, handover_info_detail):
	execute_handover_map = {
		"group": handover_group,
		"custom": handover_custom,
        "super_man": handover_super_manager,
        "system_man": handover_system_manager,
        "grade_man": handover_grander_manager
	}
	
	handover = execute_handover_map.get(permission_category)
	if handover:
		handover(handover_info_detail)
	else:
		logging.error()
		return Response({})
	
       
def handover_group(handover_info_detail):
	'''用户组权限交接'''
	# 需要交接的用户组权限id列表
	group_ids = [group.id for group in handover_info_detail]
	for group in group_list:
		grant_group_per(group_ids)
		remove_group_per(group_ids)

def grant_group_per(group_ids):
		try:
			biz.group.GroupBiz.GroupService.add_members()   # 用户组权限A添加被交接人
			HandOverDetail.objects.create(			handover_task_id=handover_task_id,status=Success,permission_category="group",op_tyep="grant"... )	#权限交接详情表记录
		except ...:
			HandOverDetail.objects.create(				handover_task_id=handover_task_id,status=Faild,permission_category="group",op_tyep="grant"... )	#权限交接详情表记录

def remove_group_per(group_ids):
		try:
        	biz.group.GroupBiz.GroupService.remove_members()    # 移除交接人在用户组A的用户组权限
        		HandOverDetail.objects.create(
        			handover_task_id=handover_task_id,status=Success,permission_category="group",op_tyep="remove"... )	#权限交接详情表记录
        except ...:
        	HandOverDetail.objects.create(
        		handover_task_id=handover_task_id,status=Faild,permission_category="group",op_tyep="remove"... )	#权限交接详情表记录

        
def handover_custom(handover_info_detail):
	'''自定义权限交接'''
	system_ids = [system.id for system_info in handover_info_detail]
	for system_id in system_ids:
#	通过api/v1/policies/?system_id= 拿到策略id列表
		policy_ids = []
		grant_policy_per(policy_ids)
		remove_policy_per(policy_ids)
    	
def grant_policy_per(policy_ids):
    	try:	# 授权指定系统下策略权限给被交接人
			biz.application.ApprovedPassApplicationBiz._grant_action()
			HandOverDetail.objects.create(
				handover_task_id=handover_task_id,status=Success,permission_category="custom",op_tyep="grant",permission_info=policy_ids... )	#权限交接详情表记录
		except ...:
			HandOverDetail.objects.create(
				handover_task_id=handover_task_id,status=Faild,permission_category="custom",op_tyep="grant",permission_info=policy_ids... )	#权限交接详情表记录

def remove_policy_per(policy_ids):
		try：		# 删除当前用户指定系统下策略
            通过api/v1/policies/?system_id= 拿到策略id列表
            biz.policy.PolicyOperationBiz.delete_by_ids()
        	HandOverDetail.objects.create(
				handover_task_id=handover_task_id,status=Success,permission_category="custom",op_tyep="remove",permission_info=policy_ids... )	#权限交接详情表记录
		except ...:
			HandOverDetail.objects.create(
				handover_task_id=handover_task_id,status=Faild,permission_category="custom",op_tyep="remove",permission_info=policy_ids... )	#权限交接详情表记录
	
	
def handover_super_manager(handover_info_detail):
	'''角色权限交接'''
	# 拿到用户的超级管理员角色id列表
	
	role_ids = [role.id for role in handover_info_detail]

	for role_id in role_ids:
		grant_super_per()
		remove_super_per()
		

def grant_super_per(role_id)：
		try：
            biz.role.RoleBiz.add_super_manager_member()	# 将被交接人添加为超级管理员角色
            HandOverDetail.objects.create(
                        handover_task_id=handover_task_id,status=Success,permission_category="super_man",op_tyep="grant"... )	#权限交接详情表记录
        except ...:
            HandOverDetail.objects.create(
                andover_task_id=handover_task_id,status=Faild,permission_category="super_man",op_tyep="grant"... )	#权限交接详情表记录

def remove_super_per(role_id):
		try：
			biz.role.RoleBiz.delete_super_manager_member()   #删除交接人的超级管理员角色
			HandOverDetail.objects.create(
				handover_task_id=handover_task_id,status=Success,permission_category="super_man",op_tyep="remove"... )	#权限交接详情表记录
			
		except..:
			HandOverDetail.objects.create(
				handover_task_id=handover_task_id,status=Success,permission_category="super_man",op_tyep="remove"... )	#权限交接详情表记录


def handover_grade_manager(handover_info_detail):
	'''角色权限交接'''
	role_ids = [role.id for role in handover_info_detail]
	for role_id in role_ids:
		grant_grade_per(role_ids)
		remove_grade_per(role_ids)

def grant_grade_per(role_ids):
    	try
	    	biz.role.RoleBiz.add_grade_manager_members()	# 将交接人添加为分级管理员成员
	    	HandOverDetail.objects.create(
				handover_task_id=handover_task_id,status=Success,permission_category="grade_man",op_tyep="grant"... )	#权限交接详情表记录
	    except...:
	    	HandOverDetail.objects.create(
				handover_task_id=handover_task_id,status=Success,permission_category="grade_man",op_tyep="grant"... )	#权限交接详情表记录

def remove_grade_per(role_id):
	    try:
	    	biz.role.RoleBiz.delete_member()    #角色删除成员
	    	HandOverDetail.objects.create(
				handover_task_id=handover_task_id,status=Success,permission_category="grade_man",op_tyep="remove"... )	#权限交接详情表记录
	    except...:
	    	HandOverDetail.objects.create(
				handover_task_id=handover_task_id,status=Success,permission_category="grade_man",op_tyep="remove"... )	#权限交接详情表记录
	    	
 
def handover_system_manager(handover_info_detail):
	'''角色权限交接'''
	role_ids = [role.id for role in handover_info_detail]
	for role_id in role_ids:
		grant_system_per(role_id)
		remove_system_per(role_id)

 
def grant_system_per(role_id)：
    	try:
    		# biz模块新增 增加系统管理员成员的逻辑
    		biz.role.RoleBiz.add_system_manager_members()	# 修改系统管理员
    		HandOverDetail.objects.create(
				handover_task_id=handover_task_id,status=Success,permission_category="system_man",op_tyep="grant"... )	#权限交接详情表记录
    	except...:
    		HandOverDetail.objects.create(
				handover_task_id=handover_task_id,status=Success,permission_category="system_man",op_tyep="grant"... )	#权限交接详情表记录
         
def remove_system_per(role_id):         
    	try:
    		biz.role.RoleBiz.delete_member()	# 角色删除成员
    		HandOverDetail.objects.create(
				handover_task_id=handover_task_id,status=Success,permission_category="system_man",op_tyep="remove"... )	#权限交接详情表记录
    	except...:
    		HandOverDetail.objects.create(
				handover_task_id=handover_task_id,status=Success,permission_category="system_man",op_tyep="remove"... )	#权限交接详情表记录
	
```



5.2 当次交接状态接口

- url：/api/v1/handover/<handover_task_id\>
- method：get

- in：handover_task_id

- out：

```json
{ 

  "message": "OK",

  "code": 0,

  "data": {
      	   "executor":"zhangsan",
  		   "transferor"："lisi",
           "reason": "交接理由",
          	"status":"success"
  			},

  "result": **true**
}
```



5.3当次交接记录明细接口【分页】

- url：/api/v1/handover/<handover_task_id\>/detail

- method：get

- in：id，limit, offset

- out

```json
{

  "message": "OK",

  "code": 0,

  "data":{
      	  count:2, 
          results:
            [
              {"permission_category":"group","permission_id":123, "permission_name":"用户组权限A","status":"success","error_info":"","operate_type":"grant",permission_detail=[]},
              {"permission_category":"custom","permission_id":123, "permission_name":"用户组权限A","status":"faild","error_info":"","operate_type":"remove",permission_detail=[1234,1233,1235]} ],
         },
    
  "result": **true**

}
```



5.4交接记录列表【分页】

- url：/api/v1/handover/<executor\>
- method：get

- in：executor，limit, offset

- out

```
{ 

  "message": "OK",

  "code": 0,

  "data":{count:2, 
  		  result:[{
      	   "executor":"zhangsan",
  		   "transferor"："lisi",
           "reason": "交接理由",
          	"status":"success"
  			},
  			{
      	   "executor":"zhangsan",
  		   "transferor"："wangwu",
           "reason": "交接理由",
          	"status":"success"
  			}]
  		}

  "result": **true**

}
```

**Comment by zhu327** [comment]
1. 自定义权限提交得信息需要记录system_id, policy_id
2. 交接的接口不需要executor, 从request.user中获取
3. cache.lock()想清楚到底要锁什么东西, 理论上提交的信息不能再重复提交, 但是未交接的信息可以再交接
4. 异步执行的化, try - except 还有用吗?
5. 出于安全方面的考虑, 用户提交的信息, 包括用户组, 自定义权限, 管理员, 数据在入库前都需要再次做校验, 是否是request.user本身的信息, 杜绝提交其它人的信息
6. 交接的逻辑需要使用biz的相关方法, 而不是 biz.svc的方法
7. 自定义权限的交接不是`biz.application.ApprovedPassApplicationBiz._grant_action()`, 需要使用PolicyOperationBiz的`alter`方法
8. 从伪代码看代码逻辑都是try - except, 是否存在滥用, 代码在逻辑上是否能抽象, 比如GroupHandoverHandler类
9. 交接记录上能否详细的说明交接的步骤, 单前做到哪一步, 先不要考虑并行执行任务, 考虑做成步骤, 保证交接的过程能完成, 用户能明确知道
10. 交接的记录, 用户只能看到自己的记录列表, 是否管理员能看到所有的记录, 需要产品确认

**Comment by nannan00** [comment]
1. 表设计问题：一次提交 不代表是一个交接任务，可以直接存储为每个独立的交接任务
    - request_id是否有必要记录DB?
    - 为什么需要将一次提交的所有数据都存储到handover_info里，那如果多次交接，如何保证多次里的交接内容不重复呢？
    - 字段permission_xxx需要重新考虑一下，本身表名已经体现了权限交接，这样命名不是很合适

2. 对交接接口需要校验 其中的用户组、自定义权限、分级管理员是否本人拥有的，是否已过期等，若用户都没有权限，则不能交接，否则相当于越权操作

3. 对于过期的权限（比如用户组成员、自定义权限），如何处理？不交接的话，需要考虑页面展示时，不可交接

4. 分布式锁的使用有问题，在分布式锁里，去调用执行异步任务，没有意义，无法解决相同交接内容出现在多个任务的问题，应该没有必要使用到分布式锁

5. 注意代码的抽象 和 复用，可以定义每种类型交接类型的handle和retry方法 以及记录的更新等，每种交接的逻辑都是很相似的，都是添加和删除两个步骤，需要考虑抽象复用

6. try-except 严重滥用，需要重新考虑一下

**Comment by zhu327** [comment]
交付时间 12-10

1. 确认saas代码是否ready
2. 确认前端是否完成开发
3. 确认交付时间是否delay
