### ISSUE TITLE
[容器化] 触发用户管理同步用户

### ISSUE THREAD

**Issue by zhu327** [TencentBlueKing/bk-iam-saas#414]
应该在web启动以后启动同步, 用app_ready?, k8s的job过重了

**Comment by wklken** [comment]
如果用job, 需要改成 django command

-----

未来可能需要考虑, 做成强同步, 即, 用户管理没有 ready, 会一直重试, 直到成功;

**Comment by zhu327** [comment]
- [ ] 1. celery queue prefix
- [ ] 2. metric指标前缀
- [ ] 3. 外部redis密码渲染问题
- [ ] 4. 拆分helm, 写readme交付
- [ ] 5. 用户管理同步job, 改为同步, 设置上限
