### ISSUE TITLE
[SaaS]无权限跳转小问题

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#419]
![image](https://user-images.githubusercontent.com/19284021/138390316-9f8debe4-a42c-48a8-93f3-434a746c9075.png)
![image](https://user-images.githubusercontent.com/19284021/138390341-49de7c8e-21db-4497-912b-cdcd04ebae84.png)
然后，双指滑动浏览器返回，出现以下界面。
![image](https://user-images.githubusercontent.com/19284021/138390413-3ecd0727-db6b-4afc-a8b8-caed2efb2d0c.png)

**Comment by lhzzforever** [comment]
done
