### ISSUE TITLE
[讨论] 临时权限

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-iam-saas#433]
# 临时权限

## 背景

某些业务场景下, 需要短时的权限.

例如, 申请两个小时内可以登录某台主机, 申请 8 个小时内可以执行某个发布脚本等

相当于现在的`长时`的权限, `短时`权限的生命周期更短, 用完即废弃, 如需再使用需要再次申请; 可以进行`时间上`更精细的权限管控; 

并且, 由于与目前`长时`生效的权限在管控上差异较大, 所以, 独立出`临时`权限的概念, 并在整体上做支持

## 基本概念

- 临时权限跟普通权限没有任何差别, 有效期非常短, 必须`<24小时`, 或者`<8 小时`
- 一个人一个操作, 可以同时申请多条临时权限, 最多同时有 100 条? (影响鉴权性能)
- 临时权限是彼此独立的, 不做合并等判断, 例如, 第一次申请10 台主机权限, 第二次可以再重复申请其中 1 台的权限;
- 临时权限在产品上有独立的申请入口, 以及独立的查看分类
- [重要] 生命周期: 申请, 审批, 生效, 过期; 不允许编辑, 不允许`续期`;  
- 可以查看`3天之内`的`临时权限`; `3天之前`的临时权限会被彻底回收(物理删除)
- 产品侧, 在查看`已过期`的临时权限, 可以设置交互支持快速重新申请.
- 临时权限, 在申请审批通过的时刻, 做一次`审计`记录; 明确记录策略及其`过期时间`
- [重要] 只有个人能申请`临时权限`, 组/部门不支持配置`临时权限`
- 临时权限不需要`接入系统`主动开启, 而是所有系统生效

## TODO 讨论

1. 有没有差别? 是否做产品`能力`上的差异. (期望一致, 但是环境属性的时间类不希望有, 意义不大)
2. 有效期限制需要拍板, `<24 小时`? `<8 小时`?
3. 一个人一个操作临时权限数量限制? 100 条? 还是更小? 100 条也会有问题, 例如一天内连续调试申请了超过 100 条, 并且此时不用的还没有过期. 主动删?
4. 临时权限要不要判断`重复`? 例如重复申请一台主机的编辑权限, 有效期不一样/一样. 如果要判断, 用什么标识判断?
5. 有主权限, 是否还能够申请临时权限? 例如有任意主机编辑权限, 然后去申请`某台`主机的临时权限.
6. 可以查看`几天`内的临时权限? `几天`之前的直接删除?
7. 临时权限是否需要`接入系统`开启, 还是全部生效? 这是一个通用需求还是相对小众的系统需求?

## 技术实现

```sql
CREATE TABLE `policy` (
  `pk` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `subject_pk` int(10) unsigned NOT NULL,
  `action_pk` int(10) unsigned NOT NULL,
  `expired_at` int(10) unsigned NOT NULL,
  `expression` mediumtext NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`pk`),
  KEY `idx_subject_action_expire` (`subject_pk`,`action_pk`,`expired_at`),
  KEY `idx_expired_at` (`expired_at`),
  KEY `idx_created_at` (`created_at`)
)
```

表:

- 独立存储一张表, 避免频繁增删对主表有影响
- 临时权限就不区分 policy-expression表, 只存一张表, 有一个expression字段!

缓存:

- 临时权限的缓存TTL 短, 不考虑复用, 不考虑更新
- `subject_pk - action_pk => count`, 插入时, 更新 为 1; 鉴权先获取
    - 为 0 则表示 100%没有不需要查; 
    - 为 1 需要去查, 不确定有没有及是否过期
        - 查不到, 更新为 0
        - 查到了, 不需要更新
- `tmp_policy`怎么缓存? 查到 10 条, 全部cache到一个list? 过期时间多少? 实际会逐步过期掉(不能单条单条cache). 反复update cache 有问题(应该自然失效) 

鉴权:

- 鉴权需要先判断`系统-人-操作`有没有配置临时权限, 没有则跳过; 整体鉴权多 1-2 次查询
- 是分为两个阶段计算, 还是像以往一样, 聚合所有策略计算
    - 两个阶段: 先计算普通权限, 无权限再计算临时权限
    - 一个阶段: 捞取普通权限+临时权限, 计算或返回 (这个更统一?)

debug:

- `?debug` 的时候, 需要将临时权限上下文(ID/内容/has_tmp_perm=true)等同样的方式写入debug信息
- 临时权限的`api.log`中有标志, 标识是否有临时权限生效; (用于后续问题排查)

清理

- 定时任务, 每 10 分钟跑一次, 清理临时权限; 并且是一批批的删, 而不是一条 SQL 删(避免系统抖动)

其他:

- policy_list/policy_get需要支持查询临时权限
- 是否入engine? 怎么入?

**Comment by wklken** [comment]
临时权限就不区分 policy-expression表, 只存一张表, 有一个expression字段!

**Comment by Xmandon** [comment]
有主权限, 是否还能够申请临时权限? 例如有任意主机编辑权限, 然后去申请某台主机的临时权限.
------
用户在申请某个实例权限下的时候，我们可以做下鉴权，提示用户已经有权限了

**Comment by Xmandon** [comment]
临时权限是否需要接入系统开启, 还是全部生效? 这是一个通用需求还是相对小众的系统需求?
-----
临时权限是用户使用需求，所以是全部生效

**Comment by Xmandon** [comment]
刷新原型
https://3i6i79.axshare.com

**Comment by wklken** [comment]
- 第一期环境属性只有: `时间`, 相当于第一期临时权限不需要支持`环境属性`
- 到期时间`已过期`, 需要鼠标放上去能看到精确的过期时间
- 需要决策: 过期多久后会被彻底删除
- 需要支持: `一键删除` 所有已过期的临时权限 (单系统? 跨系统?)
- 临时权限的数量上限是多少? 超过限制无法申请, 需要提示交互, 并引导其去删除已过期的)
- 审批流程需要重点考虑下, 现在复用, 未来切分的需求

**Comment by wklken** [comment]
- 第一期不支持环境属性
- 过期之后, 3 天之前被定时任务删除;  
- 先做10条, 包含已过期的; (只要没被删除的都算)
- 申请单类型, 要加一个`临时权限申请`; 审批流先留口子, 未来会独立配置
- 有效期<24 小时
- 申请时不做已有权限判断, 可以重复申请

**Comment by wklken** [comment]
待解决问题:
1. 临时权限的缓存问题
2. 如何做审计? 


-----

移除当前迭代, 开始时再处理

**Comment by nannan00** [comment]
![image](https://user-images.githubusercontent.com/17491932/146150534-2ddbe056-65cd-4b16-951b-91d9d9a9ddeb.png) 
是否考虑连同过期时间一起cache，使用时Cache取出来后再判断一下即可，这样也就只需要在增加时使缓存失效即可

**Comment by nannan00** [comment]
![image](https://user-images.githubusercontent.com/17491932/146151219-4550a177-2581-4f5f-88b1-0834acd06201.png)

应该不需要10分钟这么频繁吧，1个小时？或半个小时？

**Comment by wklken** [comment]
暂时搁置, 环境属性处理完之后, 开始做这块的逻辑

**Comment by wklken** [comment]
鉴权时, 可以缓存 
`{ system / action / subject - 临时权限count }`, 非 0 则表示要去算

**Comment by wklken** [comment]
可以使用redis bitmap实现

**Comment by zhu327** [comment]
临时权限在saas侧的存储与清理同样需要考虑, saas的表比后台的表大很多, 虽然不影响鉴权的性能, 但是随之时间的推移, 过多的数据会影响查询的性能
