### ISSUE TITLE
[工具支持] 导出具有某些操作的某些资源实例权限的用户列表

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#436]
关联issue https://github.com/TencentBlueKing/bk-iam-saas/issues/275

**Comment by wklken** [comment]
## 背景

权限中心后台存的是表达式, 是一个范围, 类似`业务 A 下的所有主机`, `业务 A 集群 B 下system=linux`的主机

所以, 拿某台主机, 想要查询所有有权限的用户列表, 是无法做到的.

## 解决方案

> 拿到对应系统的app_code/app_secret, 或者注册一个app_code/app_secret并刷新到所有系统的system clients中(https://bk.tencent.com/docs/document/6.0/160/8442?r=1)

然后, 就能`模拟`这个系统的身份, 调用权限中心接口

### 1. 操作维度

- 需求: 获取拥有某个操作权限的所有用户列表
- 实现: 以系统的身份, 拉取这个操作的所有策略列表
- 需要数据: 系统id, APP_code/app_secret, 操作id
- 接口文档: https://bk.tencent.com/docs/document/6.0/160/8454
- 注意: 
    - 这个接口返回所有策略, subject是可能重复的
    - subject有用户user/用户组group, group只有groupName/groupID, 没有里面包含的members

### 2. 资源维度

- 需求: 获取某个操作某个资源的有权限的用户列表
- 实现: 以系统的身份, 使用用户+操作+资源调用鉴权接口鉴权
- 需要的数据: 系统id, APP_code/app_secret, 所有用户列表, 操作id, 资源 ID 及属性(如果开启了属性鉴权的话)
- 接口文档:  https://bk.tencent.com/docs/document/6.0/160/8456  (有批量接口)
- 注意: 
    - 需要对应系统资源的 ID(而不是名称), 需要理解对应系统的权限模型, 鉴权

**Comment by wklken** [comment]
## 这个需求不依赖于iam-search-engine! engine也解决不了这个问题

**Comment by wklken** [comment]
@Xmandon 尽早决策

**Comment by wklken** [comment]
并且需要周知风险

**Comment by wklken** [comment]
第一期: 操作+实例, 不能分页, 页面导出搜索结果

-------
- 单操作, 目前做不到, 只能自己用脚本, 以对应系统的身份查询所有策略列表 https://bk.tencent.com/docs/document/6.0/160/8454

**Comment by Xmandon** [comment]
已跟用户沟通，目前评估实现不了，先实现页面部分的功能。

**Comment by Xmandon** [comment]
结论：工具在那时不需要支持，页面功能先提供给客户
