### ISSUE TITLE
[容器化] migrate sql 优化

### ISSUE THREAD

**Issue by zhu327** [TencentBlueKing/bk-iam-saas#438]
现有的sql文件中指定了db的数据库name为bkiam, 而在values中是可能配置非bkiam名称的数据库的, 这就导致migrate可能会没有生效

为了处理这个问题, 先把sql文件中的bkiam去掉

后续最终的解决方式:

把sql-migrate的二进制直接集成到bkiam的基础镜像中, 把去掉bkiam的的sql文件直接打到基础镜像中, 直接在基础镜像中执行migrate操作

**Comment by zhu327** [comment]
- 先去掉sql文件中所有的db name解决可能出现migrate未生效的问题

**Comment by wklken** [comment]
这个方案待优化为: 将sql-migrate和主项目打在一个镜像, 每次出包, 把仓库中sql文件打入镜像. 这样就不需要在helm charts中多维护了一份sql文件

**Comment by zhu327** [comment]
半天

**Comment by zhu327** [comment]
1. 从sqlmigrate的docker image中拷贝二进制
2. 从仓库中sed sql, 并拷贝到image中
3. 更新helm chart的migrate逻辑
   - 替换二进制的路径
   - 替换sql文件的路径
   - 删除sql与sql的configmap

**Comment by wklken** [comment]
补充: 更新 helm charts中最佳实践, 在原先一节补充相关文档说明
