### ISSUE TITLE
临时权限方案原型设计

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#441]
关联issue：https://github.com/TencentBlueKing/bk-iam-saas/issues/433

**Comment by Xmandon** [comment]
刷新原型
https://3i6i79.axshare.com

**Comment by wklken** [comment]
https://github.com/TencentBlueKing/bk-iam-saas/issues/433#issuecomment-993134303https://github.com/TencentBlueKing/bk-iam-saas/issues/433#issuecomment-993134303

**Comment by Xmandon** [comment]
补充申请单
https://4dk64t.axshare.com/#id=owqw1l&p=%E4%B8%B4%E6%97%B6%E6%9D%83%E9%99%90%E7%94%B3%E8%AF%B7%E5%8D%95&g=1
