### ISSUE TITLE
[文档] 官网文档API调用方式统一为APIGateway

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-iam-saas#46]
抹掉 直调+ESB 的方式;  统一

**Comment by wklken** [comment]
本次整体切换apigateway的迭代中, 一并推动升级

**Comment by wklken** [comment]
容器化版本发布前, 更新文档中apigateway的接入方式

**Comment by wklken** [comment]
duplicated: https://github.com/TencentBlueKing/bk-iam-saas/issues/28

**Comment by zhu327** [comment]
官网文档已增加apigw相关选项, 并说明在7.0后要用apigw
