### ISSUE TITLE
[SaaS] 涉及Policy结构变化后的申请单据内容调整

### ISSUE THREAD

**Issue by nannan00** [TencentBlueKing/bk-iam-saas#478]
Policy的结构变化，其产品形态也不一样，需要调整在ITSM里的申请单据内容

### Policy结构变化
1. 支持笛卡尔积，即一个Action对应多组权限
2. 支持环境属性

### 涉及变更的申请单据类型
1. 申请自定义权限（包括续期）
2. 申请加入用户组（包含续期）
3. 申请分级管理员创建
4. 申请分级管理员更新

需要待产品确定产品的最终形态才可以进行

**Comment by zhu327** [comment]
![b5570fa2e4acda7ab7d22742f47c727](https://user-images.githubusercontent.com/873883/147184994-98eeda42-e922-4593-aa59-018725090d17.jpg)

**Comment by zhu327** [comment]
申请单使用第一种方式展示, 1个操作只有一条, 然后通过弹窗来展示
