### ISSUE TITLE
[SaaS] 升级核心依赖第三方包

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-iam-saas#480]
放在 #479 之后

1. pydantic
2. drf
3. requests
4. json库
5. celery
6. redis
7. 其他

确保核心包都到最新版本, 确保没有 breaking changes导致问题, 确保线上能无缝升上去

**Comment by zhu327** [comment]
以下版本已经是python 3.6能支持的最新版本

```
django-celery-beat==2.2.1
django-redis==5.2.0
pydantic==1.9.2
redis==4.3.5
requests==2.27.1
```

以下版本为最新:

```
django==3.2.16
djangorestframework==3.14.0
```
