### ISSUE TITLE
[Backend] 继承关系计算优化

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-iam-saas#481]
目前: 一个人最多加入 100 个组

原因: 组是全局的, 会使得成员继承所有组权限

根本原因: 接入系统使用的时候, 组是`独享`的, 根本没有考虑隔离

--------

此时会导致, 100个组限制可能放开

1. 产品上, 是否考虑组隔离?
2. 实现上, 加入组/退出组生效时间需要`延迟`, 例如 1 分钟
3. 有没有其他优化方案

**Comment by Xmandon** [comment]
重点是API开放后，没有限制使用会加剧问题的产生

**Comment by Xmandon** [comment]
1. 用户组定位
2. 实例权限限制1万个优化，目前个别用户超过几千个已经出现慢查询的情况

**Comment by wklken** [comment]
## 两个阶段

### 1. 获取 人 - 组关系

> 最大结果集: 1 + 100 + DEPTs * 100 

数据来源:
1. 人的 subject_pk
2. 人 - 组列表
3. 人 - 部门 - 组
    - 3.1 人 - 部门列表
    - 3.2 部门 - 组

1/2/3.1 可以快速获取; 

问题在于: `3.2 部门 - 组`, 这里用了redis pipeline; `执行次数=部门数`

### 2. subject_pks + action_pk 查询策略大表

> memory 5min -> redis 30min (pipeline hget) -> db(in 操作)

最大的问题: 
- subject_pks 集合过大, 没有在第一时间缩小范围
- 到redis会获取所有的, 并set, 包括空的(防止下一次穿透到db)

**Comment by wklken** [comment]
## 解决问题 1

问题 1 的瓶颈在于, 部门列表 获取 组列表; 是一个pipeline行为; 

假设一个subject-group限制为 1000, 那么这里会变成 `1 + 1000 + N*1000`; 由于 N 不可控, 每次鉴权都会pipeline访问

---------

优化效果: 一次pipeline(N次get, N=用户所处的部门数), 优化成一次sorted-set get + [缓存未命中, pipeline N次get)

> localcache 30min -> rediscache 12 hours -> database

变更成三级缓存的方案, 由于subject_pk本身是一个整数, 是有固定特征的.

假设 10w人(100000), 划分成每 1000 个为一组的区间(100 个组)
- changelist key为当前subject_pk所处的区间编号;
- 每次变更一个subject_pk的group, 将这个key加入到changelist

问题: 一个用户加入一个group, 会导致同一个区间的dept的changelist感知到变更, 理论上应该隔离的?  即, 将changelist区分为user / dept => 这样就能最小化影响?

**Comment by wklken** [comment]
## 解决问题 2: subject_pks + action_pk 查询策略大表

目标: 保证数据正确的前提下, 减少对redis/mysql的压力

subject_pks可能是 1000 甚至 5000, 会导致的问题:  
1. pipeline中get的命令过多
2. 查询policy大表的sql语句中, `where subject_pks in []`列表可能超大, 导致慢查询

需要缩小范围, 降低1-2 个数量级;

------

目标

```
user -> subject_pks
action_pk + subject_pks -> policies
```

----

**问题:** 怎么滤掉 没有配置这个 action_pk的用户组pks, 缩小集合?  注意, 需要保证数据一致性

```
# 表结构
| subject_pk(only group)    |    action_pk |   count |

```

1. 每天更新一次
2. 涉及用户组授权更新一次

此时数据不准

鉴权:
1. 查到, 肯定有
2. 查不到, 也不一定没有?

**Comment by wklken** [comment]
## subject_pks + action_pk  实现逻辑

```sql
CREATE TABLE `subject_action_count` (
  `pk` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `subject_pk` int(10) unsigned NOT NULL,
  `action_pk` int(10) unsigned NOT NULL,
  `count` int(10) unsigned NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`pk`),
  UNIQUE KEY `idx_uk_subject_action` (`subject_pk`,`action_pk`)
);
```

sql

```sql
# 查询count:
SELECT subject_pk, action_pk, count(*) FROM policy WHERE subject_pk=2 AND action_pk=1 GROUP BY subject_pk, action_pk;

# 首次插入:

INSERT INTO subject_action_count(subject_pk, action_pk, count) 
SELECT subject_pk, action_pk, count(*) FROM policy WHERE subject_pk=2 AND action_pk=1 GROUP BY subject_pk, action_pk;

# insert or update:

INSERT INTO subject_action_count(subject_pk, action_pk, count) 
SELECT subject_pk, action_pk, count(*) FROM policy WHERE subject_pk=2 AND action_pk=1 GROUP BY subject_pk, action_pk 
ON DUPLICATE KEY UPDATE count=values(count);
```


参考资料:
- [ON DUPLICATE KEY](https://dev.mysql.com/doc/refman/8.0/en/insert-on-duplicate.html)
` VALUES(col_name) in the ON DUPLICATE KEY UPDATE clause refers to the value of col_name that would be inserted`

**Comment by wklken** [comment]
## 最终的瓶颈

> 继承关系过滤掉没有配置的组之后, 不会成为瓶颈.

新的瓶颈: 如果一个用户继承了 1000 个组, 这 1000 个组都配置了权限, 那么每次鉴权都会**计算**, 这是无法优化的

主要问题:  某些项目, 大量使用用户组管理权限, 但是每个用户组都会配置一模一样的权限; 当人/部门继承这批用户组的权限后, 计算量无法避免. **权限中心没有也不会有业务/项目/模块等等维度数据**, 从操作层面区分不开

**Comment by wklken** [comment]
## 增补流程

## 不存在, 则增补:

此时, 竞争状态: 1) 已经有, 更新为新 2)没有, 插入

```sql
INSERT INTO subject_action_count(subject_pk, action_pk, count) 
SELECT subject_pk, action_pk, count(*) FROM policy WHERE subject_pk=2 AND action_pk=1 GROUP BY subject_pk, action_pk 
ON DUPLICATE KEY UPDATE count=values(count);
```

## 存在, 删减策略

此时走增补流程:
- 删除后还有策略, 增补成功
- 删除后空, 增补失败  => 需要额外多调用一次更新

```sql
update subject_action_count t1 set t1.`count` = (select count(*) from policy where subject_pk=2 AND action_pk=1) where subject_pk=2 AND action_pk=1;
```

## 定时更新

直接遍历`subject_action_count`表, 全量更新

```sql
update subject_action_count t1 set t1.`count` = (select count(*) from policy where subject_pk=2 AND action_pk=1) where subject_pk=2 AND action_pk=1;
```
