### ISSUE TITLE
[Backend] action支持隐藏/删除

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-iam-saas#483]
接入系统有需求

1. 删除一个 action(封装组合接口)
2. 在页面隐藏一个 action, 用户无法申请

-----

另外:
- do_migrate没有支持 delete action policies 的行为

**Comment by Xmandon** [comment]
action 支持隐藏的几个场景：
1. 自定义权限配置
2. 分级管理员创建选范围
     - 配置权限模版
     - 用户组配置权限
3. 系统管理员创建用户组
4. 超级管理员创建用户组
------
1、2、3、4 都是可选
@zhu327

**Comment by zhu327** [comment]
<img width="929" alt="image" src="https://user-images.githubusercontent.com/873883/234817998-6b729fa6-2581-43ba-8650-a1eacc827afd.png">

**Comment by lhzzforever** [comment]
这里前端根据两个字段区分是否时外部接入系统，如： source=externalApp和system_id=bk_ci， source的值是固定值

**Comment by lhzzforever** [comment]
Done
