### ISSUE TITLE
[SaaS] 去blueapps

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-iam-saas#536]
> 简化代码, 降低复杂度

目标:
1. 去掉blueapps目录
2. 去掉blueking目录

并且同时支持多环境;

-----

- 登录依赖/account等
- 配置文件

**Comment by zhu327** [comment]
1. 梳理v3中使用到的环境变量
2. 梳理v2中使用到的环境变量
3. 重新规划下配置文件的处理
4. 删除blueapps

3天

**Comment by zhu327** [comment]
- TE版本处理
- 出包测试
