### ISSUE TITLE
[规划] 2022 年上半年权限中心规划

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-iam-saas#538]

**Comment by Xmandon** [comment]
## 产品
权限中心：

【功能新增】
临时权限
管理后台
	API白名单
	通知设置
	屏蔽设置：系统、操作、自定义、用户组屏蔽
	清理策略：过期数据、长期未使用策略、系统侧实例数据删除
	系统管理：系统下线、编辑操作等一系列环节
	全局视角管理http://gitlab-paas.open.oa.com/iam/issue/-/issues/1821
自定义权限申请支持分级管理员审批
模型变更API
权限交接二期
	对接审批流程
	目标人通知/接收机制
RBAC方案（产品定位，评估收益，待定）
权限获得实现“邀请”制（待评估）http://gitlab-paas.open.oa.com/iam/issue/-/issues/1807

【体验优化】
批量修改分级管理员、用户组权限（场景：系统增加了操作，如何同步到所有用户组）
初始化权限设定（企业版部署后，可以给到一些常用的模板和用户组）
组织架构同步优化 http://gitlab-paas.open.oa.com/iam/issue/-/issues/1722
忽略路径名字显示问题
	1. 无法知道实例节点属于哪个业务/项目
	2. 多个业务/项目下相同的实例，选择的时候只会出现一条记录 http://gitlab-paas.open.oa.com/iam/issue/-/issues/2422
审计优化
用户组推荐优化（如何更智能，优化方案待定）
续期页面交互优化 http://gitlab-paas.open.oa.com/iam/issue/-/issues/2360
拓扑实例搜索优化 http://gitlab-paas.open.oa.com/iam/issue/-/issues/2322
系统操作变更如何推送给分级管理员 http://gitlab-paas.open.oa.com/iam/issue/-/issues/2256
通知优化 
http://gitlab-paas.open.oa.com/iam/issue/-/issues/2202
http://gitlab-paas.open.oa.com/iam/issue/-/issues/2179
http://gitlab-paas.open.oa.com/iam/issue/-/issues/2098
属性选择优化 http://gitlab-paas.open.oa.com/iam/issue/-/issues/2101
自定义已有权限交互优化 http://gitlab-paas.open.oa.com/iam/issue/-/issues/1973
分级管理员申请编辑时内容显示优化 http://gitlab-paas.open.oa.com/iam/issue/-/issues/1947
继承组织的权限无法退出问题 http://gitlab-paas.open.oa.com/iam/issue/-/issues/1720
其他优化类：http://gitlab-paas.open.oa.com/iam/issue/-/issues/840



【支持】
蓝盾权限对接优化

**Comment by wklken** [comment]
#197
