### ISSUE TITLE
组权限删除问题

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#544]
![image](https://user-images.githubusercontent.com/19284021/146119204-e0faaacc-93a6-43e4-b625-8f65c358d541.png)

参数校验失败: 策略ID，多个以英文逗号分隔: 该字段不能为空。

**Comment by huangpeng0428** [comment]
done

**Comment by huangpeng0428** [comment]
复现不了 是不是网速的问题
