### ISSUE TITLE
[Backend]  清理未被引用的expression表数据

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-iam-saas#55]
需要确保 尽量减少对现有系统带来的影响; 尽量降低或规避风险!

- 对现有系统鉴权的影响(性能/频率/锁表等)
- 尽量防止误删(宁可不删或慢删, 也不能 删错)

**Comment by wklken** [comment]
优先级提升, 1.15 或者后一个版本需要出去

**Comment by zhu327** [comment]
难点:

- 如何保证并发的情况下, 在删除数据的同时, 可能数据已经被读取但是还没有被引用, 删除后再被引用的情况, 没有外键约束

原则:

- 可以删除失败, 但是不能错误的删除

**Comment by zhu327** [comment]
可能需要进行到Y2022M01

**Comment by zhu327** [comment]
- 对未被引用的数据先标记， 新增一个tinyint字段作为标记
- 创建表达式时， 查询复用的expression筛选被标记的数据
- 删除时选择标记过后一段时间内的数据，并且判断pk是否被引用

**Comment by wklken** [comment]
方案 2 改一下,  更新signature使其无法被引用

问题: 第一个sql 有没有并发问题吗? 

```sql
# 1. 确保不会被引用到
UPDATE expression set signature = 'timestamp' WHERE pk NOT IN (SELECT expression_pk FROM policy)

# 2. 删除
DELETE from expression where signature = 'timestamp' 
```

**Comment by zhu327** [comment]
现有的expression表中有type类型，0 自定义， 1 模板策略，如果新增一个type 为2， 或者其它的数值，更新时直接更新为新的值， 然后，删除时做筛选

**Comment by zhu327** [comment]
```sql
ALTER TABLE `bkiam`.`expression` MODIFY COLUMN `type` SMALLINT(5) signed NOT NULL DEFAULT 0;
```

**Comment by zhu327** [comment]
定时任务流程

1. 更新未被引用的
UPDATE expression SET type=-1 WHERE type=1 AND pk NOT IN (SELECT expression_pk FROM policy)

2. 更新因并发查询导致更新的
UPDATE expression SET type=1 WHERE type=-1 AND pk NOT IN (SELECT expression_pk FROM policy) AND updated_at < ?

3. 删除真正未被引用的数据
DELETE FROM expression WHERE type=-1 AND pk NOT IN (SELECT expression_pk FROM policy) AND updated_at < ?

**Comment by zhu327** [comment]
- saas增加调用后台清理api任务

**Comment by zhu327** [comment]
sql: IN (SELECT expression_pk FROM policy)

- 考虑是否用join可行，是否会更好
- 用SELECT EXISTS是否会更好

**Comment by zhu327** [comment]
调研结果：

```
SELECT * FROM expression WHERE pk NOT IN (SELECT expression_pk FROM policy); 2.43

ALTER TABLE `policy` ADD INDEX `idx_expression_pk` (`expression_pk`);

SELECT * FROM expression LEFT JOIN policy ON expression.pk = policy.expression_pk WHERE policy.expression_pk IS NULL; 3.40

SELECT * FROM expression WHERE NOT EXISTS (SELECT * from policy WHERE expression.pk=policy.expression_pk); 2.73
```

使用join或者exists都依赖于新建的索引，policy/expression表数量都大于150万
