### ISSUE TITLE
[SaaS]  分布式锁 lock 重构

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-iam-saas#565]
> 统一抽象, 统一实现, 统一的引用

**Comment by zhu327** [comment]
1~2天

**Comment by zhu327** [comment]
锁场景:

1. 权限交接同时只能有一个交接任务
2. 全量同步组织架构只能有一个任务
3. 同一个subject授权/回收只能有一个在执行, 排队
4. 某些类型的长时任务, 需要限制同一时间只有一个任务被创建

**Comment by zhu327** [comment]
问题:

1. 锁的key生成方式不统一, 需要有一个统一的对象方法提供锁的key生成, 锁类型的枚举值, 附加数据的参数
2. 区分非阻塞与阻塞锁的使用

---

涉及到的相关Model:

- TaskDetail
- PermTemplatePreUpdateLock
- SyncRecord
- GroupAuthorizeLock

看看能不能提取成某种模式处理
