### ISSUE TITLE
[APIGateway] 容器化版本需要自动注册所有网关到 APIGateway

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-iam-saas#57]
7.0 现有版本需要实现, 因为我们要推动所有内部产品切换到 APIGateway

**重要**: 如果 7.0 没有支持, 后面再推动的话, 需要推两次; (让他们新版 helm 或环境变量直接配置apigateway网关即可)

**Comment by wklken** [comment]
第三/四阶段实现; 并在iwiki上写相关文档, 然后我们统一推动切换

**Comment by zhu327** [comment]
### 容器化接入apigw

https://git.woa.com/bk-tools/apigw-manager

http://gitlab-paas.open.oa.com/Infrastructure/apigateway-dashboard/blob/staging/bin/sync_apigw_definitions.sh

**Comment by wklken** [comment]
需要提高下优先级

**Comment by wklken** [comment]
https://github.com/TencentBlueKing/bkpaas-python-sdk/tree/master/sdks/apigw-manager

**Comment by wklken** [comment]
#435 
close
