### ISSUE TITLE
[SaaS] Redis配置支持哨兵和单机模式

### ISSUE THREAD

**Issue by nannan00** [TencentBlueKing/bk-iam-saas#586]
参考标准运维

![image](https://user-images.githubusercontent.com/17491932/146871316-8afffb6c-230d-46d5-b97f-8a5bfa7823b4.png)

sentinel支持的时候，记得实现上，connections string要支持配置list   多个ip:port 

不能只支持配一个 host:port 这样

**Comment by zhu327** [comment]
2022下半年规划

**Comment by zhu327** [comment]
升级 django-redis 到 5.2 最新版本

**Comment by zhu327** [comment]
celery 支持 sentinel 需要升级到 4.0 以上

**Comment by zhu327** [comment]
https://github.com/TencentBlueKing/bk-iam-saas/issues/718

一起处理

**Comment by zhu327** [comment]
需要测试下哨兵模式
