### ISSUE TITLE
2022规划 API/管理后台/优化点汇总

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-iam-saas#618]

**Comment by wklken** [comment]
## API

**Comment by wklken** [comment]
## 管理后台

**Comment by wklken** [comment]
## 后端优化项

> 优先处理用户咨询量较大的点, 另外需要考虑错误码/错误信息/日志的完备程度, 尽量在源头就有明确的错误

**Comment by wklken** [comment]
## 产品

### 超级管理员全局视图

- 用户组
- 分级管理员

**Comment by zhu327** [comment]
权限拷贝: 两个操作依赖实例视图完全一致/或无资源依赖, 接入系统如何进行拷贝? (1. 是否可以无压力地先poicy list再授权 2.提供接口是否有价值?) => 目前授权的问题是: 查回去的策略无法理解, 无法将数据修改后直接调用授权接口

---

可以基于现有的关联操作的逻辑/权限模板更新从已有数据拷贝的逻辑来实现
