### ISSUE TITLE
接口废弃及回收

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-iam-saas#619]
- /api/v1/open/management/groups/%s/members/

超级管理类:
- 查询用户组列表   `GET /api/c/compapi/v2/iam/admin/groups/`   => 待定, 这个有过滤功能, 利于管理
- 查询用户组成员列表  `GET /api/c/compapi/v2/iam/admin/groups/{group_id}/members/ `  => 待定, 这个会返回有效期, 用于页面管理功能(续期等)
- 查询 Subject 加入的用户组列表 `GET /api/c/compapi/v2/iam/admin/subjects/{subject_type}/{subject_id}/groups/ `

**Comment by nannan00** [comment]
https://github.com/TencentBlueKing/bk-iam-saas/issues/619
