### ISSUE TITLE
[文档] API文档完善

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-iam-saas#642]
- 授权接口, 是否支持过期时间. 是支持的, 文档中需要补充 expired_at字段的说明
字段是expired_at，值是整型，表示时间戳，单位是秒

- 批量授权接口 https://bk.tencent.com/docs/document/6.0/160/8450, `paths=[]`表示任意

**Comment by wklken** [comment]
https://bk.tencent.com/docs/document/6.0/160/8450

授权接口也支持`type=group`?

开白名单, 可以调用接口给人/组授权
问题: 这个接口只能授本系统的操作权限, 还是也能授其他系统的操作权限

**Comment by nannan00** [comment]
- 文档调整：Open API 分页参数Limit/Offset调整为Page/PageSize，并注释版本依赖，包括APIGateway文档
  - [文档] API文档完善 https://github.com/TencentBlueKing/bk-iam-saas/issues/642
  - 新增OpenAPI的配套：官网API文档、ESB配置文件、APIGateway接入等

**Comment by nannan00** [comment]
https://github.com/TencentBlueKing/bk-iam-saas/issues/40

**Comment by zhu327** [comment]
2022下半年规划

**Comment by zhu327** [comment]
rbac 相关文档:

rbac鉴权时, /auth 立即生效, /query由于存在表达式计算, 目前是 30s 生效

实际两个接口同时请求, 鉴权结果可能会不一致;  例如加完权限, 跳往 A 页面鉴权/auth有权限, 跳往 B 页面鉴权/query无权限 => 用户体验不好

所以, 给调用系统的建议是, 同一个业务操作逻辑的多次鉴权, 建议使用尽量一致的方式(尽量要么都使用/auth, 要么都是用/query, 不混用)

**Comment by zhu327** [comment]
创建分级管理员, 返回数据修正

**Comment by zhu327** [comment]
FAQ:

itsm 申请单详情 url 是从 itsm 通过 sn 动态拿到的

**Comment by zhu327** [comment]
剩下:

policy list api 增加rbac相关说明

**Comment by zhu327** [comment]
模型注册apigateway + auth_type
