### ISSUE TITLE
[运维] 上云环境切换容器化

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-iam-saas#661]
- 开发环境
- 预发布环境
- 正式环境

--------

涉及, 新版容器化部署, 切换使用现有的redis/mysql, 并且需要确保服务无缝切换

需要关注lb的转发

**Comment by wklken** [comment]
完成交接

**Comment by wklken** [comment]
暂时不动, 未来有资源后交接

**Comment by zhu327** [comment]
缺后台的helm新版本部署,先close
