### ISSUE TITLE
人员信息补充组织架构信息

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#695]
<img width="1216" alt="企业微信截图_39d208f7-246d-4503-b104-27f62c9491fe" src="https://user-images.githubusercontent.com/19284021/150059451-25bc5e8f-d93a-4345-96be-15ecc476f32e.png">

**Comment by zhu327** [comment]
![image](https://user-images.githubusercontent.com/873883/154051028-a033e0f9-49d6-423c-bfe7-51381a2f09c4.png)

---

在去笛卡尔积的分支上开发, 开发联调环境测试 @huangpeng0428

**Comment by huangpeng0428** [comment]
done
