### ISSUE TITLE
如何build S-mart

### ISSUE THREAD

**Issue by lvhaoran88** [TencentBlueKing/bk-iam-saas#696]
我根据s-mart安装包规则构建了一SaaS部署包，在pip download -d {pkgs_dir} -r requirements.txt。但是requirements中好多包都在腾讯的pip源中找不到。请一份构建S-mart的步骤

**Comment by wklken** [comment]
smart包请联系蓝鲸的运营同学申请包, 并不是pip download就可以的, 而是涉及前端构建/后端构建/使用目标部署系统pip download(否则无法离线安装)/打包等等;
