### ISSUE TITLE
[方案] 临时权限

### ISSUE THREAD

**Issue by zhu327** [TencentBlueKing/bk-iam-saas#712]
- 后台实现
- SaaS实现

---

先规划, 后实现, 评估时间/风险

---

规划

## 后台

- [ ] #778 
- [ ] #779 

## SaaS

- [ ] #797 
- [ ] #798 
- [ ] #799 

---

deadline 2022-03-15

**Comment by zhu327** [comment]
https://github.com/TencentBlueKing/bk-iam-saas/issues/712

**Comment by zhu327** [comment]
## SaaS侧 -- 权限配置

1. 申请临时权限
   - 不显示现有的临时权限, 只能新增, 不支持环境属性(但是要预留设计)
   - 申请单按照自定义的申请流程走, 有独立的申请单类型
2. 临时权生效授权
   - 直接创建新的临时权限的数据, 不做合并
3. 我的权限 - 临时权限
   - 临时权限列表, 按系统查询, 同一个操作可以有多条数据
   - 过期时间要求能精确到具体的时间(与时区有关)
4. 删除临时权限
5. 重新申请临时权限 -- 确认是否要有批量操作, 单前每条数据点一下不科学
6. 清理临时权限, 定时任务, 请求3天前过期的临时权限

**Comment by zhu327** [comment]
过期时间申请后就不变, 可以直接在SaaS表中存一份

**Comment by zhu327** [comment]
### 后台

#### 权限配置

1. 新增临时权限创建接口
2. 新增临时权限删除接口
3. 新增查询subject该系统的SaaS policy接口, 同ListSystemPolicy

#### 鉴权

TODO

**Comment by zhu327** [comment]
zset

**Comment by zhu327** [comment]
### action_pk 整体缓存

key = system + subject_pk

1. 授权时创建policy，删除 key 的 cache
2. 鉴权时，判断key有没有值， 没有值 select action_pk from tmp_policy where subject_pk = ? and action_pk in (?) and expired_at > ? set缓存， 过期时间半小时，返回value
3. 获取value后判断 action_pk 是否在集合中
4. 如果再则查询临时权限，不在直接返回

**Comment by nannan00** [comment]
key = subject_pk + action_pk
value = [object(expression,expired_at), ...]

1. 查询缓存
  - 查询key缓存，缓存不存在，则查询DB [ select expression, expired_at from tmp_policy where subject_pk = ? and action_pk = ? and expired_at > ? ] , 然后set缓存，过期时间半个小时

2. 删除缓存
  - 对应 subject_pk + action_pk的临时权限创建时，删除key的缓存

**Comment by zhu327** [comment]
缓存的设置

1. 查询subject_pk + action_pk查询db得到 AuthPolicy
2. redis system + subject_pk, filed action_pk 整体缓存，缓存的过期时间为查询的权限最大过期时间，还需要考虑查询为空时缓存的处理
3. 内存缓存同redis，过期时间设置为查询到权限的最大过期时间

---

缓存的过期

1. 授权时有新的 subject_pk + action_pk 被授权时，清除redis缓存
2. 权限删除时，对应action_pk的缓存要删除
3. 内存缓存的删除方式通知方式， 使用changlist, 授权时/删除时写入操作时间， changlist range 的时间区间怎么考虑？
	- 缓存的设置时间, 到当前时间的range
	- zset的清理规则: 好像不能清???

1. policy的缓存也只存1分钟, 通知机制完全与policy的内存缓存一致

---

1. 全内存缓存的问题: 内存占用变大
2. redis缓存的问题, 本身权限的过期时间比较短, 缓存的数据可能大部分都是过期的的, 导致无效的缓存

---

缓存空值的问题

1. 查询时缓存的空值, 在并发授权时, 清理缓存在前, 设置空值缓存在后, 会导致鉴权错误的失败, 这里临时权限的变更频率预估会大于正常权限, 所以风险变大

**Comment by zhu327** [comment]
### 方案1

鉴权

1. 判断鉴权的action_pk是否在授权的操作列表中
    - 获取 system + subject_pk 为 key 的缓存数据
    - 如果没有缓存则从db中获取 select action_pk from tmp_policy where subject_pk = ? and action_pk in (?) and expired_at > ?
    - 如果不在列表中, 则直接返回空的Policy array
2. 查询用户的临时权限列表
    - 获取 system + subject_pk 的 hash 中 action_pk 为field的策略数据
    - 遍历以上策略数据筛选出未过期的数据
    - 如果缓存中没有从数据库中拉取
    - redis中的过期时间为数据库查询的策略的最大值
    - 内存缓存只缓存1分钟, changlist来保证最新
    - 如果查询的策略列表为空, 需要清空第一步创建的缓存

---

二级缓存

1. 内存, 1分钟
2. redis, 策略列表中过期时间最大的值

清理缓存

1. 授权时需要清理以上2个key的缓存, 并对changlist做修改
2. 删除权限时需要清理以上2个key的缓存, 并对changlist做修改

**Comment by zhu327** [comment]
方案2

鉴权

1. 从db查询所有有权限的操作列表
2. 以 system+subject_pk作为可以action_pk作为field 缓存 以上查询的policy_pk + 过期时间的列表
3. 遍历policy列表, 以pk为key存到内存缓存中

---

1. 查询redis中的policy_pk列表, 筛选出未过期的policy_pk
2. 从内存缓存中拿poliy_pk对应的缓存数据, miss的从db拿

---

清理缓存

内存缓存不管, 过期时间为策略过期时间, 清理system+action_pk的key
