### ISSUE TITLE
[SaaS] 评估permission_logger是否可以去掉

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-iam-saas#721]
audit 理论上记录了所有审计信息, 是否有必要使用permission_logger另外记录?

如果可以去掉, 抹除包括配置的所有信息

**Comment by wklken** [comment]
排查权限问题的时候, 因为audit目前在数据库中且只有管理员可以访问, 所以运维及开发不会第一时间关注

除非, 能够进一步精准定位到权限变更事件(目前audit太弱了)

**Comment by zhu327** [comment]
2022下半年规划

**Comment by zhu327** [comment]
整体去除, 暂未看到该日志在debug时的作用
