### ISSUE TITLE
[SaaS&Backend] 评估所有对外API StatusCode调整为Restful API 规范的影响

### ISSUE THREAD

**Issue by nannan00** [TencentBlueKing/bk-iam-saas#736]
评估后台和SaaS 接口status code协议调整为Restful API规范后，对调用方的影响（只调整）

**Comment by wklken** [comment]
- 前端
- sdk
- 非 sdk

**Comment by wklken** [comment]
先评估: 后台协议切换, saas是否能无缝, 否则需要提前做兼容

------

**Comment by wklken** [comment]
saas 代码已兼容; 

移出这个迭代
------

TODO:
1. 评估后台协议变更, sdk对接/直接鉴权 API 接口, 这两块的影响
2. 评估saas协议变更
    - 2.1 前端是否支持
    - 2.2 调用 saas API 的是否支持

**Comment by wklken** [comment]
- SDK 已处理
- saas 与前端(处理中): https://github.com/TencentBlueKing/bk-iam-saas/pull/897

**Comment by wklken** [comment]
- [ ] SaaS API切换到标准的 status code
- [ ] Backend API切换到标准status code

**Comment by wklken** [comment]
前端先切换

**Comment by wklken** [comment]
- 前端->saas 接口: 已经切换
- sdk已经兼容

-----

- saas api没切
- 后台 api没切

**Comment by wklken** [comment]
新的接口都切换了

**Comment by zhu327** [comment]
v2接口已切换
