### ISSUE TITLE
[SaaS] 补充审计操作类型中的对应中文描述

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-iam-saas#766]
```
group.member.renew
group.policy.update
user.policy.update


urser.role.delete
template.preupdate.create
template.preupdate.delete
template.update.commit


admin.api.allow.list.config.create
admin.api.allow.list.config.delete

authorization.api.allow.list.config.create
authorization.api.allow.list.config.delete
management.api.allow.list.config.create
management.api.allow.list.config.delete
```

**Comment by zhu327** [comment]
group.member.renew -- 用户组成员需求
group.policy.update -- 用户组修改权限
user.policy.update -- 用户修改权限


urser.role.delete  -- 用户退出管理员
template.preupdate.create -- 权限模板预更新创建
template.preupdate.delete -- 权限模板预更新删除
template.update.commit -- 权限模板更新提交


admin.api.allow.list.config.create -- ADMIN-API白名单创建
admin.api.allow.list.config.delete -- ADMIN-API白名单删除

authorization.api.allow.list.config.create -- 授权类API白名单创建
authorization.api.allow.list.config.delete -- 授权类API白名单删除
management.api.allow.list.config.create -- 管理类API白名单创建
management.api.allow.list.config.delete -- 管理类API白名单删除
