### ISSUE TITLE
[发布计划] 环境属性

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-iam-saas#772]
- [x] SaaS 出最新包, 确认变更点(同上次)
- [x] 后台出最新包, 确认变更点(同上次)
- [x] 确认下是否有测试需求/有没有测试资源
- [x] 容器化版本, 前后台更新到最新
- [x] 除上云版正式环境, 其他版本更新到最新
- [x] 观察日志一周(到二月底, 期间关注用户反馈)
- [x] review一周的日志,确认saas 及后台没有 500

**Comment by zhu327** [comment]
#### 测试重点关注

1. 无权限跳转申请
2. 申请单创建/审批
3. 关联权限生成(申请权限时, 被依赖的权限自动创建)
4. 权限模板更新增加操作时, 修改用户组的授权信息, 批量从其它的操作复制实例

**Comment by zhu327** [comment]
#### 版本

backend: 1.10.1
saas: 1.7.1
engine: 1.0.4

**Comment by zhu327** [comment]
3.2 SaaS日志排查

- [ ] paasce-test
- [ ] paasee-test
- [ ] 上云预发布

**Comment by wklken** [comment]
- iam.log本身stdout/stderr是否有异常信息
- iam_api.log/iam_web.log中,  status=200 + error=1 的异常日志

-----

可以做规则用grep直接从日志文件中捞取(发布新版的时间开始到现在)

**Comment by zhu327** [comment]
- 周四发布
- 准备发布预案

**Comment by zhu327** [comment]
后台镜像版本: 1.10.2
- 有SQL需要执行

SaaS版本: 1.7.6

---

发布风险:

- 如果有新增的权限被配置,或者修改,回滚前需要清理,需要备份数据库可能

**Comment by zhu327** [comment]
发布计划：

0. 发布公告

时间：16:45

内容：

2. 发布bkiam backend

时间：17:00

步骤：

检查：

3. 发布bkiam saas

时间：17:30

步骤：

检查：

**Comment by zhu327** [comment]
已发布，观察日志
