### ISSUE TITLE
[API] 调用分析

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-iam-saas#773]
目前各个接入系统调用`/api/v1/open`是否合理?

由于是post, 看不到详情, 看调用记录, 短时间内可能重复调用一个接口

需要分析及优化
1. 是否合理? 
2. 是否是重复调用? 是的话能否优化 (由于业务侧问题)
3. admin能否不调用授权相关接口(建议)
4. 是否调用了管理类接口进行`鉴权类`行为? 

----

本质上, 是希望降低api负载

**Comment by nannan00** [comment]
# API分析


| API | 类型 | 简介 | 限制 | 用途 | 负载  | 使用情况 & 合理性评估 |
|-----|------|------|:-----|:-----|:------|:----------------------|
|  [POST] /application/   |   无权限跳转   |      |      |      |       |                       |
|  [POST] /authorization/instance/   |   授权API   |      |      |      |       |                       |
|   [POST] /authorization/path/  |    授权API  |      |      |      |       |                       |
|   [POST] /authorization/batch_instance/  |  授权API    |      |      |      |       |                       |
|  [POST] /authorization/batch_path/   |   授权API   |      |      |      |       |                       |
|  [POST] /resource_creator_action/   |  授权API    |      |      |      |       |                       |
|   [POST] /batch_resource_creator_action/  |  授权API    |      |      |      |       |                       |
|  [POST] /resource_creator_action_attribute/   |   授权API   |      |      |      |       |                       |
|  [POST] /management/grade_managers/   |   接入系统管理类API   |      |      |      |       |                       |
|  [GET] /management/grade_managers/{grade_manager_id}/members/   |   接入系统管理类API   |      |      |      |       |                       |
|   [POST] /management/grade_managers/{grade_manager_id}/members/  |   接入系统管理类API   |      |      |      |       |                       |
|  [DELETE] /management/grade_managers/{grade_manager_id}/members/   |   接入系统管理类API   |      |      |      |       |                       |
|  [GET] /management/grade_managers/{grade_manager_id}/groups/   |   接入系统管理类API   |      |      |      |       |                       |
|   [POST] /management/grade_managers/{grade_manager_id}/groups/  |  接入系统管理类API    |      |      |      |       |                       |
|  [PUT] /management/groups/{group_id}/   |   接入系统管理类API   |      |      |      |       |                       |
|  [DELETE] /management/groups/{group_id}/   |   接入系统管理类API   |      |      |      |       |                       |
|   [GET] /management/groups/{group_id}/members/  |   接入系统管理类API   |      |      |      |       |                       |
|  [POST] /management/groups/{group_id}/members/   |   接入系统管理类API   |      |      |      |       |                       |
|  [DELETE] /management/groups/{group_id}/members/   |   接入系统管理类API   |      |      |      |       |                       |
|  [POST] /management/groups/{group_id}/policies/   |   接入系统管理类API   |      |      |      |       |                       |
|  [GET] /management/users/grade_managers/   |   接入系统管理类API   |      |      |      |       |                       |
|  [GET] /management/users/grade_managers/{grade_manager_id}/groups/   |   接入系统管理类API   |      |      |      |       |                       |
|  [POST] /management/groups/applications/   |   接入系统管理类API   |      |      |      |       |                       |
|  [GET] /admin/groups/   |   超级管理类API   |      |      |      |       |                       |
|  [GET] /admin/groups/{group_id}/members/   |   超级管理类API   |      |      |      |       |                       |
|  [GET] /admin/subjects/{subject_type}/{subject_id}/groups/   |   超级管理类API   |      |      |      |       |                       |

**Comment by nannan00** [comment]
# SaaS Open API 调用分析

## 无权限跳转API
### 1. [POST] /application/ 无权限跳转
#### 简介
接入系统在其产品页面，用户无权限时自动生成跳转到IAM申请对应权限的URL

#### 限制
无，任何App都可以使用

#### 负载 & 使用情况 & 合理性评估
- 当前QPS是每小时3500，最高时是每小时5000
- 大部分请求耗时在 70-500ms，但也存在少量请求在 1 - 2s
- 接口涉及回调接入系统查询资源名称，若被频繁调用，可能会导致引发接入系统的请求量过大
- 不合理的地方：大部分请求都只是对单一资源实例单一操作，而这样会导致短时间内一个用户可能需要请求多次审批，接入系统没有合理评估到用户所需的权限集合，所以可以推动接入系统提供权限集合给到用户申请而不是单一权限

## 授权/回收 API
> 所有授权接口，只是针对操作有关联资源实例的，无法对不关联资源实例的操作授权

### 2. [POST] /authorization/instance/
#### 简介
单Action单实例的授权或回收

#### 限制
接入系统只能授权其自身系统的权限

#### 负载 & 使用情况 & 合理性评估
几乎无请求量，应该是大部分系统使用了批量接口

### 3.

**Comment by wklken** [comment]
- 所有`未实现`的, 且已经开放到外部的 API, 优先级提升, 优先处理(存量数据不管, 增量进不来就行, 并且可配置)
- 性能差且调用量比较大的top 5, 一起进一步分析, 确定瓶颈
- 合理性分析/能否下架等, 结合产品/需求以及未来接口的规划考虑

**Comment by zhu327** [comment]
- 评估一下优化目标, 可能的容量, 考虑下预案
