### ISSUE TITLE
待跟进项

### ISSUE THREAD

**Issue by zhu327** [TencentBlueKing/bk-iam-saas#801]
1. 临时权限 -- 再次申请的逻辑
![image](https://user-images.githubusercontent.com/873883/155643978-ec0ab490-2d50-4887-9917-81ee66a23900.png)

2. 管理后台整体设计, 关联管理后台的用户认证

#750

3. 协作开发待确认项

#713

**Comment by Xmandon** [comment]
临时权限 -- 再次申请的逻辑
--------
当用户的临时权限过期，发起再次申请时：跳转临时权限申请页面，自动填充需要再次申请的权限操作和实例。
