### ISSUE TITLE
[SaaS] 长耗时后台任务拆分处理

### ISSUE THREAD

**Issue by zhu327** [TencentBlueKing/bk-iam-saas#820]
长耗时后台任务如果超过30分钟, 会触发rabbitmq默认配置30分钟无ack自动删除channel的规则, 需要评估长耗时任务拆分细化处理

**Comment by wklken** [comment]
- 新版mq已禁用
- 过期邮件通知的, 拆碎打散指派给子worker处理

-------
应该反向扫, 从策略表里面查询配置了权限的人, 而不是从组织架构里面捞所有人

**Comment by wklken** [comment]
从policy表查询distinct subject之后处理

**Comment by zhu327** [comment]
SELECT DISTINCT subject_pk FROM policy WHERE template_id = 0 AND expired_at < 1

命中不了索引, 可能不能直接使用

**Comment by zhu327** [comment]
role 表 2000+
group 表 5000+
user 表 13000+

**Comment by zhu327** [comment]
explain select distinct subject_pk from subject_relation where policy_expired_at< 1;

**Comment by wklken** [comment]
<img width="754" alt="image" src="https://user-images.githubusercontent.com/2002216/170647262-e7fbbbb2-4e47-44eb-ae57-d1e0c829c361.png">

需要优化, 优先级高
1. 只检查, 配置了权限的用户
2. 尽量缩小扫描范围
3. 尽量批量查询, 而部署逐个查询

-----

1. 降低对后台压力
2. 降低对 db 压力

**Comment by zhu327** [comment]
2022下半年规划

**Comment by zhu327** [comment]
https://github.com/TencentBlueKing/bk-iam-saas/issues/1252

**Comment by zhu327** [comment]
### 1. 用户的过期提醒

1. saas policy表查询有权限的人
2. 后台查询过期GroupSubject关系, 分页拉取
3. 遍历通过set在循环逻辑中去重

### 2. 角色的用户组有成员过期提醒

1. 后台查询过期GroupSubject关系, 分页拉取
2. 通过用户组于角色的关系, 反查角色信息
3. 通过group set/role set在循环逻辑中去重
