### ISSUE TITLE
[SaaS] 组织架构同步数据清理与测试

### ISSUE THREAD

**Issue by nannan00** [TencentBlueKing/bk-iam-saas#821]
1. 单元测试
2. 集成测试，各种场景：父子部门调换、先删除后加部门等等

**Comment by zhu327** [comment]
- 梳理用户管理同步过程中可能需要清理的数据
   - [ ] 用户组与部门/用户的关系
   - [ ] 角色成员
   - [ ] 角色的授权范围

**Comment by zhu327** [comment]
https://github.com/TencentBlueKing/bk-iam-saas/issues/209

**Comment by zhu327** [comment]
https://github.com/TencentBlueKing/bk-iam-saas/pull/1760/files

**Comment by zhu327** [comment]
- 需要补充删除用户时需要同时删除用户所属的角色, 与角色的授权范围
