### ISSUE TITLE
[SaaS] API性能评估&优化汇总

### ISSUE THREAD

**Issue by nannan00** [TencentBlueKing/bk-iam-saas#851]
# API 优化项
> API分析：https://github.com/TencentBlueKing/bk-iam-saas/issues/773
### 1. 数据对象限制
* 支持环境变量配置限制项
* 限制项
  - 所有系统可创建最多3000个分级管理员
  - 一个分级管理员可添加的成员个数：100
  - 一个用户可加入的分级管理员个数：100
  - 一个分级管理员可创建的用户组个数: 100

### 2. 性能优化

* 接口列表

| API | 请求量 | 耗时 |
| ---- | ---- | ---- | 
| 新建关联实例授权 | 当前每秒QPS是在10以内，每小时请求量 100以内 | 大部分请求耗时在300ms - 1000ms，还有15%的请求耗时在1-4s |
| 新建关联属性授权 | 当前每秒QPS是在10以内，每小时请求量 300以内 | 大部分请求耗时在300ms - 1000ms，还有10%的请求耗时在1-4s |
| [POST] /application/ 无权限跳转 | 当前每秒最高QPS是10，每小时请求量 3000 - 5000 | 大部分请求耗时在100-300ms，但也存在2%的请求在 400ms - 2s | 
|查询分级管理员用户组列表| 1天请求量2万+, 平均每秒QPS在10以内 | 大部分请求在200ms以内 | 
| 查询用户组成员列表 | 1天请求量10万+，平均每秒QPS在10以内 |  大部分请求在200ms以内 |
|  用户组授权 | 1天请求量在100以内 | 耗时在300-500ms | 

* 进一步评估每个API性能
  - 压测现有API，出压测报告
  - 使用PYINSTRUMENT测试每个API耗时点
  - 使用蓝鲸 OTEL测试每个API耗时点

* 通用优化
  - API认证鉴权缓存
      - System-Client认证
      - API-Permission白名单鉴权
  - DB 优化
    - 索引 - 目前SaaS DB的表未特别做过SQL索引的优化
    - SQL语句 - 目前SaaS上大部分ORM查询都是Select *，可以进行优化

### 3. 合理性评估
* 需评估下架的接口
  - 授权API
      - [POST] /authorization/instance/
      - [POST] /authorization/path/
      - [POST] /authorization/batch_instance/
      - 批量拓扑授权已可以代替以上三个接口

  - 用户在某个分级管理员下加入的用户组
    - [GET] /management/users/grade_managers/{grade_manager_id}/groups/
    - 3月8日蓝盾切换到新接口后已无数据，是否考虑下架？目前该接口性能比较差，涉及查询多个DB数据的IN查询
  - 获取用户加入的用户组列表（包括递归）
    - [GET] /admin/subjects/{subject_type}/{subject_id}/groups/
    - 目前该接口的返回并没有特别附加信息，是否可考虑直接使用后台的接口代替？目前SaaS是递归查询用户及其部门的所有用户组，然后取并集，涉及多次调动后台，性能比较差

* 接入方可能未合理使用
  - 查询分级管理员下的用户组列表
    - [GET] /management/grade_managers/{grade_manager_id}/groups/
    - 1天请求量2万+, 平均每秒QPS在10以内，大部分请求在200ms以内，但每天9点-9点10分这10分钟内都有5000+次请求
    - 不合理：可能蓝盾提供了相关接口给到第三方，需要调用具体使用场景，避免不合理的使用
  - 查询用户组成员列表
    - [GET] /management/groups/{group_id}/members/
    - 1天请求量10万+，平均每秒QPS在10以内，大部分请求在200ms以内，但但每天9点-9点10分这10分钟内都有7000+次请求
    - 不合理：可能蓝盾提供了相关接口给到第三方，需要调用具体使用场景，避免不合理的使用
  - 以上两个接口调用场景：
    - 蓝盾提供OpenAPI支持添加用户组成员，但确实先查询分级管理员下用户组列表，在根据用户组名称匹配到对应用户组ID，然后再调用IAM添加用户组成员接口
        - 蓝盾侧优化：在根据用户组名称匹配用户组ID时，不调用接口，而是直接查询蓝盾DB维护的用户组名称与ID的关系
    - 流水线配置了通知用户组，先查询先查询分级管理员下用户组列表，在根据用户组名称匹配到对应用户组ID，然后再查询对应用户组的成员，最后发送通知
        - 蓝盾侧优化：在根据用户组名称匹配用户组ID时，不调用接口，而是直接查询蓝盾DB维护的用户组名称与ID的关系
        - IAM侧优化：是否考虑提供用户组查询成员的非管理类API

**Comment by wklken** [comment]
- 用户在某个分级管理员下加入的用户组 / 获取用户加入的用户组列表（包括递归） 
    - 这两个接口需要考虑是否有管理需求? (后台只返回`当前有效的`, 无法进行管理!)
    - 如果下, 需要同步更新上云版网关列表,以及外部版网关注册资源及文档
- 是否考虑提供用户组查询成员的非管理类API
    - 可以提供, 必要的(相当于用户组的概念都后台的实现), 但是需要考虑, 目前用户组接口都是`有效`的结果, 过期的没处理, 如果搜索, 需要考虑支持 有效/过期

**Comment by nannan00** [comment]
https://github.com/TencentBlueKing/bk-iam-saas/issues/773

**Comment by nannan00** [comment]
#### 上云24小时内请求量与耗时

| API | 请求量 | 耗时<100|耗时1xx| 耗时2xx| 耗时3xx| 耗时4xx|耗时500+|
| ---- | ---- | ---- |  ---- | ---- | ---- | ---- | ---- | 
| application | 82542 | 11.81% | 65.5% | 19.39% | 1.89% | 0.39% | 1.01% |
| authorization_resource_creator_action_attribute | 3582 | 0% | 10.5% | 37.16% | 17.95% | 8.12% | 26.26% | 
| authorization_resource_creator_action | 645 | 0% | 0% | 3.26% | 16.12% | 23.1% | 57.52% |

**Comment by nannan00** [comment]
#### 新建关联实例接口每个功能的耗时分布

| 功能 | 耗时 | 调用 | 优化 |
| ---- | ---- | ---- | ---- | 
| 数据转换 | 304ms | cpu耗时86ms |
| | 183ms | 1次 iam.list_action | 考虑后台缓存？|
| | 35ms | 2次 iam.list_resource_type | 添加缓存，减少为1次请求 |
| 授权 | 225ms | cpu耗时 98ms | 
| | 43ms | 1次 iam.alter_policies |  |
| | 18ms |1次 db.update_db_policies| |
| | 37ms |2次 iam.list_system_policy | |
| | 29ms |1次 db.query_policy|  |
| 查询新建关联操作 | 11ms |1次 iam.get_resource_creator_actions | 
| 审计 | 127ms | cpu耗时25ms|
| | 73ms | 1次 表存在判断 | 缓存表是否存在的结果？使用全局Dict维护每个月的Class |
| | 29ms | 1次 保存审计信息 | 
| 认证 | 133ms | 
| | 69ms | 1次 esb.get_api_public_key | 已有缓存，只有第一次耗时 |
| | 27ms | 1次 decode_jwt | 添加缓存？相同jwt token缓存结果？ |
| | 27ms | 1次  db._get_or_create_user |
| 鉴权 | 26ms | 
| | 20ms | 1次 iam.list_client | 添加缓存 |
| | 6ms | 2次 db.api_allow_list |

**Comment by nannan00** [comment]
新建关联接口的性能与策略数据量本身成正比，大策略的话，每个环节都慢
1. 从后台拉取慢
2. 策略保存后台慢 
3. pydantic deepcopy慢
4. 审计信息save慢

**Comment by nannan00** [comment]
1. 后台拉取慢问题 => 原先解决权限模型这类拉取慢, 对于所有 saas 功能及api都有优化
2. 审计信息save慢的问题 => 寻找更好的方式，比如[异步](https://docs.djangoproject.com/en/4.0/topics/async/) 等等方式
