### ISSUE TITLE
临时权限体验汇总

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#858]

**Comment by Xmandon** [comment]
- [ ] 
<img width="1665" alt="image" src="https://user-images.githubusercontent.com/19284021/158497695-d7c443cf-4814-4091-8a12-6e589368317d.png">

**Comment by Xmandon** [comment]
- [ ] 
<img width="1368" alt="image" src="https://user-images.githubusercontent.com/19284021/158498915-4fe2f742-3fd3-4fa1-aa1f-70ef33894729.png">
<img width="1641" alt="image" src="https://user-images.githubusercontent.com/19284021/158498963-fa474ccf-f851-4901-9b5e-4a4e35c2ebea.png">

**Comment by Xmandon** [comment]
- [ ] 
<img width="1889" alt="image" src="https://user-images.githubusercontent.com/19284021/158499870-da4a68ba-fa27-4bcf-b8c8-27bf92004370.png">

<img width="1850" alt="image" src="https://user-images.githubusercontent.com/19284021/158499797-ea9618fa-9c83-487f-b2b2-bc820016fbc9.png">

**Comment by huangpeng0428** [comment]
done
