### ISSUE TITLE
[讨论] 操作影响的scope

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-iam-saas#872]
TLDR: 使用操作属性scope_* 来切分细粒度的业务维度

现有操作:

- action = pipeline_edit
    - resource_type = pipeline

子操作:

- sub_action = pipeline_edit
    - resource_type = pipeline
    - scope_type = project
    - scope_id = 123

**Comment by wklken** [comment]
规则:
1. scope_type/scope_id可选, 默认接入系统不开启, 需要显式指定开启
2. 问题: 配置权限怎么配置? 
3. 鉴权: 带了scope_type/scope_id的, 鉴权时, 需要系统传入 `scope_type/scope_id` 作为 `操作`的`属性`

**Comment by wklken** [comment]
如果一个action只能配置一种scope_type, 那么问题不大

如果能配置多种, 例如pipeline-> scope_type=[pipeline_set, project]

那么鉴权的时候, 如果只传了project, 那么不一定有权限(因为不知道之间的关系)

**Comment by wklken** [comment]
问题: 是否允许`scope_type:*`(没有配置), 或者`scope_type=A, scope_id=*`(配置了)

**Comment by zhu327** [comment]
如果只现在顶层资源类型的scope范围内呢，即scope只有项目

**Comment by wklken** [comment]
这里的scope有个跟resource type chain重叠的地方:

`项目1 - 流水线组 2 -流水线 3`

本身配置流水线编辑的时候, 其scope_type就只能是 上面这两个中的一个
