### ISSUE TITLE
权限中心 - 可观测性实现分析

### ISSUE THREAD

**Issue by zhu327** [TencentBlueKing/bk-iam-saas#875]
计划事项：

1. 查询的接口增加metric相关的查询方式，通过label能直接查询到数据（是否成功）

2. 后台回调延时计算

3. 确定指标的时间周期

4. 确定指标的计算方式

5. 需要确定交付的方式

6. ITSM的接口调用latency需要有申请单类型的metric

问题：

1. 我的申请
   - 查询申请单状态成功率，回调查询的成功率吗
   - A: 是
2. 我的申请/我的审批
   - 跳转ITSM系统就是一个链接，在这里我们记不了时间
   - A: 已删除
3. 系统接入
   - 新增接入系统成功率 -- 这个数据在后台，联合计算
   - 需要确认这里是指saas的接入页面相关的数据，还是接入系统实际在后台接入的数据
   - A: saas页面功能
4. 申请加入用户组/用户组
   - 都有查询用户组列表相关的数据，当前是没有区分的，也不好区分
   - 用户组这里为什么有调用用户管理的相关数据
   - A: 不区分
5. 指标中的Error用来做什么
   - A: 不需要error的数据, 只要成功率就行
7. 用户
   - 调用用户管理的接口有很多，这里的延迟需要细分还是统一处理，Error也一样
   - A: 算平均
8. 资源权限管理
   - 是指哪里的接口？
   - A: 管理员页面接口
9. 管理员
   - 人员选择器在前端直接拉取，拿不到延时数据
   - A: 已删除

**Comment by wklken** [comment]
- SaaS后台指标只是因为我们项目上划分, 具体计算的时候, 是可以放一起算的; (都算iam的指标)
- 不涉及业务逻辑的东西, 例如审批通过成功率之类的
- 粒度, 刚开始可以粗, 但是核心链路的, 可以考虑切分独立; 底层metrics可能是一个, 只是过滤和聚合的条件有差异;

**Comment by zhu327** [comment]
修改ErrorCodes, 异常中补充 status code

> https://github.com/TencentBlueKing/bk-iam-saas/blob/master/saas/backend/common/error_codes.py#L90

修改后, web/openapi 都会生效, 需要确认下对openapi的影响

**Comment by zhu327** [comment]
web api 请求成功率计算

django_http_responses_total_by_status_view_method_total{method="GET",status="200",view="group.group"} 7.0

计算方式: status 200是成功, 剔除4xx的请求, 5xx的是不成功

**Comment by zhu327** [comment]
component 组件依赖延迟

bkiam_component_request_duration_milliseconds_bucket{component="itsm",le="50.0",method="GET",path="/api/c/compapi/v2/itsm/get_services/",status="200"} 0.0

**Comment by zhu327** [comment]
回调接入系统延迟计算

bkiam_callback_request_duration_milliseconds_bucket{function="fetch_instance_info",le="200.0",method="post",path="/bcsapi/v4/iam-provider/v1/projects/",resource_type="project",status="200",system="bk_bcs_app"} 331.0

**Comment by zhu327** [comment]
后台api响应时间

bkiam_api_request_duration_milliseconds_bucket{client_id="bk-cmdb2020",method="GET",path="/api/v1/model/systems/bk_cmdb/token",service="iam",status="200",le="1000"} 31333

**Comment by zhu327** [comment]
后台api响应状态
