### ISSUE TITLE
当前问题

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-iam-saas#883]
本质问题:
1. 继承关系(组/角色), 没有隔离, 例如系统隔离/资源层面的隔离, 导致继承关系计算量大(所有都需要筛选出来)
2. 以action为主体, 过期时间只有一个, 所有资源存在表达式中;

**Comment by Xmandon** [comment]
2. 以action为主体, 过期时间只有一个, 所有资源存在表达式中;
-----
即使资源不存在表达式里，是不是也没法直接感知到实例，像 *、范围这种授权，我们即使要捞实例计算也得从接入系统再请求一次。

**Comment by zhu327** [comment]
新版本使用system做隔离
