### ISSUE TITLE
bkci需求

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#885]
- [x] 1. 支持流水线级别授权方案
- [x] 2. op配置默认用户组策略模板时，需对所有存量项目用户组进行数据刷新
- [x] 3. 权限action动态注册方案
- [x] 4. 根据过期时间来计算即将过期和已过期的状态
- [x] 5. 针对即将过期用户，普通用户可以主动申请续期
- [x] 6. 针对即将过期的用户，管理员可以主动给他续期
- [ ] 7. 权限中心屏蔽所有蓝盾项目的权限操作（在权限中心屏蔽蓝盾系统的所有展示）

**Comment by wklken** [comment]
5/6 接口:  
1. 生成一个续期申请单
2. 主动续期
@nannan00

**Comment by zhu327** [comment]
需求已经变更
