### ISSUE TITLE
一些优化点

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#886]
- [ ] <img width="423" alt="image" src="https://user-images.githubusercontent.com/19284021/160277450-f0e717d8-aeb6-4881-a43c-0708a6c9548a.png">

分类

发起需求
	- 权限申请
	- 临时权限申请

工作台
	- 我的申请
	- 我的审批
	- 我的权限
	- 我的分级管理员

开发者
	- 系统接入

**Comment by Xmandon** [comment]
分级管理员-用户组-添加人员，组织架构人员搜索框目前不能使用，前端先屏蔽掉入口。

**Comment by huangpeng0428** [comment]
done
