### ISSUE TITLE
推荐自定义权限优化

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#949]
### 场景
当用户没有“编辑”权限的时候，当前推荐会自动把它的依赖操作“查看”也一起推荐，但是反过来，如果用户没有“查看”权限，这时候只会推荐“查看”，不会推荐它的关联权限“编辑、删除、执行”等，我们需要实现后面这种。

### 解决方案一（处理太麻烦，而且不能cover所有合理场景，废弃！）
1. 针对“单个依赖资源”、非“新建”类的操作：不管用户申请哪个操作权限，都把关联实例的关联权限一起推荐，包括操作关联了多个资源类型的，比如：用户需要“执行方案编辑权限”，可以一起推荐的权限有：执行方案查看、执行方案删除、执行方案执行、执行方案查看、执行方案同步（新建不会落入该规则，但是新建有新建关联授权，所以够了）。
2. 针对“新建”类的操作：该类操作都是关联上级资源类型，比如“脚本新建”关联的资源类型是“业务”，此时也适合用第1条规则。
3. 针对“关联多资源类型”的操作：比如“执行方案运行”关联了“执行方案、主机”两个操作，如果用户需要这个权限，我们的推荐规则是，默认选择“第一个资源类型”相关的操作？？
4. 针对“无关联实例”的操作，无需处理。

### 解决方案二
以最小操作分组为单位来推荐，简单高效，覆盖场景基本全了。
<img width="2515" alt="image" src="https://user-images.githubusercontent.com/19284021/163301055-41701b70-ff8d-4837-8a2f-0d7e99e03768.png">

### 前端适配
<img width="2053" alt="image" src="https://user-images.githubusercontent.com/19284021/163299060-dc125af9-e341-4fa0-adf9-28ef19884906.png">

**Comment by zhu327** [comment]
![image](https://user-images.githubusercontent.com/873883/163341802-81bd7fe7-8b35-41ac-b113-59de9c0189b8.png)

**Comment by zhu327** [comment]
- 前端需要处理推荐的规则, 从actions列表中获取数据后展示
- 无权限实例的自动填充需要判断操作关联的资源类型是否一样, 如果一样则自动填充, 如果不一样, 需要留空

**Comment by zhu327** [comment]
- 需要定义一个结构来表达有关联的资源类型，与无关联的只有操作的数据
    - 可能返回policies与actions，分别返回

**Comment by zhu327** [comment]
1. 查询action groups， 匹配到申请的策略数据对应的分组
2. 使用关联操作的生成类型相同的关联操作的数据，返回未生成的操作与生成的policies

**Comment by zhu327** [comment]
![image](https://user-images.githubusercontent.com/873883/164141038-ec0d3f4f-76f5-4867-9a8d-5336e20f5c15.png)

**Comment by zhu327** [comment]
测试用数据
bk_job
f3419dba47964a6b8a3e7467ff685b5e

**Comment by zhu327** [comment]
/policies/related_policy/ to /policies/related/
