### ISSUE TITLE
[部署] 数据与模型部署方案

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-iam-saas#950]
模型集中化注册, 但是支持数据分布式管控

当前先通过网关进行流量切分

1. url 需要带system_id
2. 相关表的主键会重复, 相关的cache会不会有问题
3. 如何注册, 在saas如何区分
4. APIGateway 怎么分流
5. 刚开始全部放一起, 未来需要切分独立, 如何处理? 

-------

**Comment by wklken** [comment]
一套独立的`子权限中心后台`, 可以存储并管理多个系统的鉴权

- bk_ci 独立一套
- bk_job和bk_cmdb独立一套

**Comment by wklken** [comment]
数据层面的都得分开存, 防止saas变成中心化的

**Comment by nannan00** [comment]
需要考虑分布式部署后的稳定性、监控等等

**Comment by wklken** [comment]
可以多想想, 目前es的节点, 加入集群后, 落到任意节点的请求会路由到新节点(相当于自运维)

**Comment by nannan00** [comment]
RBAC 的OpenAPI  尽量由后台提供

用户 -> SaaS Web -> IAM Backend 如何基于SystemID路由 ？
Client -> SaaS API -> IAM  Backend 如何基于SystemID路由 ？

**Comment by nannan00** [comment]
RBAC方案已变更，不实施分布式部署
