### ISSUE TITLE
管理员可以给用户添加自定义权限

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#955]
待补充设计稿

**Comment by zhu327** [comment]
1. 添加的权限必须在管理员的授权范围内
2. 只能添加， 不能修改删除，删除会可能会导致越权，如果一定要删除管理员管理范围的权限，需要对能删除的部分做区分，逻辑过于复杂

**Comment by Xmandon** [comment]
评审后决定不错，结论：从上而下的管理模式体现组织意志，管理员可能希望当下可以快速添加权限，但长期来说不利于维护管理，会给自己或者其他管理者埋坑，所以，此需求不合理，不处理。
