### ISSUE TITLE
权限申请支持“权限获得者”为其他用户或组织

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#956]
待补充设计稿

**Comment by Xmandon** [comment]
超出分级管理员授权范围的控制规则

**Comment by zhu327** [comment]
1. 不能为组织， 组织不支持自定申请
2. 批量用户申请需要遍历没有用户的已有权限，可能会导致申请单据不一样， 需要针对每个创建不同的申请单

**Comment by zhu327** [comment]
1. 按现有的申请逻辑, 遍历被申请的用户创建申请单, 如果为已有权限则跳过

2天
