### ISSUE TITLE
[课程] 开发接入权限中心

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-iam-saas#961]

**Comment by xinshou857** [comment]
能详细说一下接入权限中心的操作嘛

**Comment by wklken** [comment]
@xinshou857 
之前已经有录播的课程, 可以配合文档一起看, https://ke.qq.com/course/3414659/12592290064505475

**Comment by xinshou857** [comment]
> @xinshou857 之前已经有录播的课程, 可以配合文档一起看, https://ke.qq.com/course/3414659/12592290064505475

但他直接就对文件进行了操作
