### ISSUE TITLE
[SaaS]实例审批人

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#98]

**Comment by Xmandon** [comment]
1. itsm创建审批流程，其中审批角色为“引用变量”，该变量需要在流程实例化的时候传值进去
![image](https://user-images.githubusercontent.com/19284021/131937822-cd5f74aa-08ad-4099-a913-a7c8cbd7982f.png)

2. 权限中心支持针对系统的实例审批配置（表示接入系统支持实例级别审批）
3. 用户在接入系统申请实例权限的时候，需要给1中的变量传递对应实例的“审批人”

**Comment by Xmandon** [comment]
方案梳理：
1. 接入系统注册资源类型的时候标记该资源类型是否支持资源实例审批人
2. itsm创建默认审批流程，审批节点增加条件分支，当资源类型支持“实例审批人”时，审批节点为“实例审批人”，不支持则走自定义权限分支。
3. 当用户申请具体实例时，统一走实例审批人，如果选择的是路径或者属性，实例审批人为“项目管理员”，即 权限中心的分级管理员审批

**Comment by zhu327** [comment]
1. [ ] 阅读当前代码中的拆单/合单逻辑
2. [ ] 了解ITSM审批流程中分支逻辑处理方式
3. [ ] 评估当前需要改动的时间成本

**Comment by zhu327** [comment]
自定义申请单创建流程:

1. 查询申请的所有操作的所有审批流程, 并填充流程中需要的审批人信息
2. 根据审批流程是否相同/审批人是否相同, 合并多个操作的申请单信息
3. 循环创建拆分出来的申请单

**Comment by zhu327** [comment]
回调接口扩展:

https://bk.tencent.com/docs/document/6.0/160/8428

需要支持属性 `_bk_iam_approver_`

**Comment by zhu327** [comment]
1. 遍历获取所有的资源实例并去重, 使用resource_type分组
2. 分组查询所有资源实例的审批人
3. 遍历申请策略, 拆分为单个实例维度的策略, 并对每个策略配置审批信息
4. 根据审批信息反向分组相同审批信息的所有操作列表
5. 合并同一审批信息下相同操作的操作的策略

问题:

1. 其实不需要分支, 有一个固定的资源审批人流程
2. 如果申请的是路径, 不是实例, 怎么处理?

**Comment by zhu327** [comment]
工作量评估:

1. 新增实例审批默认流程设置(api/前端)
1. 后端实例审批人处理逻辑

3~4天

**Comment by zhu327** [comment]
与分级管理员搜索相关的问题:

- 默认的分级管理员审批流程中可以配置从接入系统回调拿审批人还是从分集管理员的范围拿审批人

**Comment by zhu327** [comment]
- 自定义权限的默认审批流程, 与操作的审批流程当前是操作的审批流程优先
